Repository blockscout/blockscout, pull requests merged in 2018-12, with the labels that each got.

#1164 Fix pagination issue on inventory tab at Token's page
  apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1160 Ganache ignores internal transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/ganache.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/explorer/config/dev/ganache.exs
  apps/explorer/config/prod/ganache.exs
  apps/explorer/config/test/ganache.exs
  apps/indexer/config/dev/ganache.exs
  apps/indexer/config/prod/ganache.exs
Labels: in progress, ready for review

#1150 feat: support tracing via spandex
  .credo.exs
  README.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/config/dev.exs
  apps/block_scout_web/config/prod.exs
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/tracer.ex
  apps/block_scout_web/mix.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/ethereum_jsonrpc/config/dev.exs
  apps/ethereum_jsonrpc/config/prod.exs
  apps/ethereum_jsonrpc/config/test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/tracer.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/config/config.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/tracer.ex
  apps/explorer/mix.exs
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/lib/indexer/tracer.ex
  apps/indexer/mix.exs
  mix.exs
  mix.lock
Labels: in progress

#1153 GraphQL supports querying internal transactions
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/internal_transaction.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/transaction.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/scalars.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/node_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/explorer/lib/explorer/graphql.ex
  apps/explorer/test/explorer/graphql_test.exs
Labels: in progress, ready for review

#1173 Add CORSPlug
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/mix.exs
  mix.lock
Labels: in progress, ready for review

#1170 Add a cache to count the addresses with balance > 0.
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/counters/block_validation_counter.ex
  apps/explorer/test/explorer/chain/address_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/addresses_with_balance_counter_test.exs
Labels: in progress, ready for review

#1168 Allows other sites to open blockscout in iframe
  apps/block_scout_web/lib/block_scout_web/plug/allow_iframe.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
Labels: in progress, ready for review

#1179 change the inventory controller test file to exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.exs
Labels: in progress, ready for review

#1176 GraphQL API token_transfers query
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/token_transfer.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/test/block_scout_web/schema/query/node_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/token_transfers_test.exs
  apps/explorer/lib/explorer/graphql.ex
  apps/explorer/test/explorer/graphql_test.exs
Labels: in progress, ready for review

#1175 Fix randomly failing test
  apps/explorer/test/explorer/chain/address/token_test.exs
Labels: in progress

#1169 fix skipped feature tests
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/__tests__/pages/address/internal_transactions.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/address/internal_transactions.js
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
Labels: in progress, ready for review

#1172 fix: match more explicitly on ABI decoding result
  apps/explorer/lib/explorer/chain/log.ex
Labels: in progress

#1178 Add primary names to accounts page
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
Labels: in progress

#1180 Refactor transactions page
  apps/block_scout_web/assets/__tests__/pages/transactions.js
  apps/block_scout_web/assets/js/pages/transactions.js
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
Labels: in progress, ready for review

#1182 async load and remove infinite scroll from pending transactions
  apps/block_scout_web/assets/__tests__/pages/pending_transactions.js
  apps/block_scout_web/assets/js/pages/pending_transactions.js
  apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
Labels: in progress, ready for review

#1162 Add pagination and async load to blocks page
  apps/block_scout_web/assets/__tests__/pages/blocks.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/pages/blocks.js
  apps/block_scout_web/assets/js/pages/reorgs.js
  apps/block_scout_web/assets/js/pages/uncles.js
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
Labels: in progress, ready for review

#1008 Add balance history tab to address page
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_coin-balance-tile.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/coin_balance_history_chart.js
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/pages/address/coin_balances.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_by_day_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/event_handler.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/_coin_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_coin_balance_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_coin_balance_by_day_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_coin_balance_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/coin_balance.ex
  apps/explorer/test/explorer/chain/address/coin_balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1191 Fix realtime address balance update
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/address/transactions.js
  apps/block_scout_web/assets/js/socket.js
Labels: in progress, ready for review

#1190 Fix realtime indexer's 'no skips prevention' bug
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: in progress, ready for review

#1196 fix overlapping names on token transfers
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
Labels: in progress, ready for review

#1205 Fix Block Validated page to show all tabs
  apps/block_scout_web/assets/css/components/_nav_tabs.scss
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_validation_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Labels: in progress, ready for review

#1209 ETS streaming
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/counters/block_validation_counter.ex
  apps/explorer/lib/explorer/counters/token_holders_counter.ex
  apps/explorer/lib/explorer/counters/token_transfer_counter.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: bug :bug:, enhancement, in progress

#1210 Include date in addition to time in log format
  apps/block_scout_web/config/config.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/explorer/config/config.exs
  apps/indexer/config/config.exs
  config/config.exs
Labels: enhancement, in progress

#1194 Ensures consensus is valid for parent blocks
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
Labels: in progress, ready for review

#1211 Include fetcher in logger metadata
  .credo.exs
  apps/block_scout_web/config/config.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/explorer/config/config.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/buffered_task.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/pending_transaction/fetcher.ex
  config/config.exs
Labels: enhancement, in progress

#1197 Improve token balances fetching for specific addresses
  apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/address/token_balance.ex
  apps/explorer/test/explorer/chain/address/current_token_balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1186 Fix Address Trasaction query
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20181212115448_add_indexes_to_token_transfers.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: bug :bug:, in progress, ready for review, testing

#1207 Improve docs in the application
  README.md
  apps/block_scout_web/assets/js/lib/redux_helpers.js
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/address/token_balance.ex
Labels: in progress

#1214 Metadata instead of prose
  apps/block_scout_web/config/config.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/explorer/config/config.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/logger.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  config/config.exs
Labels: enhancement, in progress

#1218 Log timeout in PendingTransaction fetcher instead of crashing
  apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Labels: bug :bug:, in progress

#1217 Fix picking wrong clause for fetch_token_balances_from_blockchain
  apps/indexer/lib/indexer/token_balances.ex
Labels: bug :bug:, in progress, ready for review

#1224 Don't log when queue is unavailable in Indexer.Block.InvalidConsensus.Worker
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/token_transfer/uncataloged/worker.ex
Labels: bug :bug:, in progress, ready for review

#1184 Save reward data from blockchain call
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/block_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_beneficiary.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity/fetched_beneficiaries_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block/emission_reward.ex
  apps/explorer/lib/explorer/chain/block/reward.ex
  apps/explorer/lib/explorer/chain/block/reward/address_type.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/import/block_rewards.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/priv/repo/migrations/20181206200140_rename_block_rewards_to_emission_rewards.exs
  apps/explorer/priv/repo/migrations/20181206200312_create_new_block_rewards.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/address/coin_balances.ex
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: in progress, ready for review

#1230 Use lag windowing function to reduce missing block time
  apps/explorer/lib/explorer/chain.ex
Labels: bug :bug:, in progress, ready for review, team: architecture

#1233 Label all steps in Block.Fetcher implementations
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: bug :bug:, in progress, ready for review

#1244 Missed error pattern change in #1233
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: bug :bug:, in progress

#1239 Use reraise and __STACKTRACE__ to reraise safe_insert_all errors
  apps/explorer/lib/explorer/repo.ex
Labels: enhancement, in progress

#1242 Import stages
  .credo.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/import/runner.ex
  apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex
  apps/explorer/lib/explorer/chain/import/runner/block_rewards.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/logs.ex
  apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex
  apps/explorer/lib/explorer/chain/import/runner/tokens.ex
  apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/import/stage.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/import/stage/addresses.ex
  apps/explorer/lib/explorer/logger.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
Labels: bug :bug:, in progress

#1226 Use address_current_token_balances in address tokens tab
  apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_token_view_test.exs
  apps/explorer/lib/explorer/chain/address/token.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/test/explorer/chain/address/token_test.exs
Labels: in progress, ready for review

#1240 validator metadata retrieval and display
  apps/block_scout_web/lib/block_scout_web/templates/address/_validator_metadata_modal.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/address/name.ex
  apps/explorer/lib/explorer/validator/metadata_importer.ex
  apps/explorer/lib/explorer/validator/metadata_processor.ex
  apps/explorer/lib/explorer/validator/metadata_retriever.ex
  apps/explorer/priv/repo/migrations/20181213111656_add_metadata_field_to_address_names.exs
  apps/explorer/priv/validator_contracts_abi/metadata.json
  apps/explorer/priv/validator_contracts_abi/validators.json
  apps/explorer/test/explorer/validator/metadata_importer_test.exs
  apps/explorer/test/explorer/validator/metadata_retriever_test.exs
Labels: in progress, ready for review

#1245 Fix Jason decode error validating contracts
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/smart_contract/publisher.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/package-lock.json
  apps/explorer/package.json
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Labels: in progress, ready for review

#1252 Convert DBConnection.ConnectionError tcp recv: closed to {:error, :timeout}
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/repo.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
Labels: bug :bug:, enhancement, in progress, ready for review, team: architecture

#1254 Chunk pending transactions
  apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Labels: bug :bug:, in progress, ready for review, team: architecture

#1256 Don't use step variable twice
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: bug :bug:, in progress

#1255 Only query for coin balance when channel connected
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
Labels: bug :bug:, in progress, ready for review

#1249 Add reward value of a block in the tile and overview section.
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/views/block_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block/reward.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#1261 Include import_id and transaction_id in logger metadata
  apps/block_scout_web/config/config.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/explorer/config/config.exs
  apps/indexer/config/config.exs
  config/config.exs
Labels: bug :bug:, in progress, ready for review, team: architecture

#1260 Use where clause for on_conflict to only write tuples that are different
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/rolling_window_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex
  apps/explorer/lib/explorer/chain/import/runner/block_rewards.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/logs.ex
  apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex
  apps/explorer/lib/explorer/chain/import/runner/tokens.ex
  apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/validator/metadata_importer_test.exs
  apps/explorer/test/explorer/validator/metadata_retriever_test.exs
  apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
Labels: bug :bug:, in progress, team: architecture

#1265 Increase DB transaction timeout to account for Eth Mainnet performance
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/dev/ganache.exs
  apps/explorer/config/dev/geth.exs
  apps/explorer/config/dev/parity.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/prod/ganache.exs
  apps/explorer/config/prod/geth.exs
  apps/explorer/config/prod/parity.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain/import.ex
  apps/indexer/config/dev/ganache.exs
  apps/indexer/config/dev/geth.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/ganache.exs
  apps/indexer/config/prod/geth.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/sequence_test.exs
Labels: bug :bug:, enhancement, in progress, team: architecture

#1271 Add ON CONFLICT to derive_transaction_forks
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Labels: bug :bug:, enhancement, in progress, team: architecture

#1273 Allow block numbers to exceed missing block search range by > 1
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: bug :bug:, enhancement, in progress, ready for review, team: architecture

#1270 feat: restart on heartbeat timeout
  README.md
  rel/vm.args
Labels: in progress

#1275 Counter the need for counter queries by using COUNT(*) and adding indexes
  apps/block_scout_web/test/block_scout_web/controllers/address_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/counters/block_validation_counter.ex
  apps/explorer/lib/explorer/counters/token_transfer_counter.ex
  apps/explorer/priv/repo/migrations/20181221143000_create_blocks_miner_hash_index.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/counters/block_validation_counter_test.exs
  apps/explorer/test/explorer/counters/token_transfer_counter_test.exs
Labels: bug :bug:, in progress, ready for review

#1269 get rewards of blocks already indexed without rewards
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/test/explorer/chain/block_test.exs
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/explorer/chain/wei_test.exs
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/block/uncataloged_rewards/importer.ex
  apps/indexer/lib/indexer/block/uncataloged_rewards/processor.ex
  apps/indexer/test/indexer/block/uncataloged_rewards/importer_test.exs
Labels: in progress, ready for review

#1267 Decrease BlockScoutWeb.EventHandler message queue
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web/application.ex
  apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex
  apps/block_scout_web/lib/block_scout_web/event_handler.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
  apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/events/publisher.ex
  apps/explorer/lib/explorer/chain/events/subscriber.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/test/explorer/chain/events/publisher_test.exs
  apps/explorer/test/explorer/chain/events/subscriber_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1268 Implement emission reward tile
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/js/pages/address/transactions.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/pending_transactions.js
  apps/block_scout_web/assets/js/pages/transactions.js
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/channels/reward_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_emission_reward_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/reward_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block/reward.ex
  apps/explorer/lib/explorer/chain/events/publisher.ex
  apps/explorer/lib/explorer/chain/events/subscriber.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1280 Use info style in verify contract message
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
Labels: ready for review

#1264 Show token price in USD
  apps/block_scout_web/assets/js/lib/currency.js
  apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_token_balance_view.ex
  apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_token_balance_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/currency_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/overview_view_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/known_tokens/known_tokens.ex
  apps/explorer/lib/explorer/known_tokens/source.ex
  apps/explorer/lib/explorer/known_tokens/source/my_ether_wallet.ex
  apps/explorer/lib/explorer/market/market.ex
  apps/explorer/test/explorer/known_tokens/known_tokens_test.exs
  apps/explorer/test/test_helper.exs
  config/test.exs
Labels: in progress, ready for review

#1281 Async loading to block list in the home page
  apps/block_scout_web/assets/README.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
Labels: in progress, ready for review

#1278 market history chart load async
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/controllers/chain/market_history_chart_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/chain/market_history_chart_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/chain_view_test.exs
  apps/explorer/lib/explorer/exchange_rates/source.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
Labels: in progress, ready for review

#1282 Remove buttons to show raw input/logs
  apps/block_scout_web/assets/css/components/_transaction-input.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/swappable_item.js
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#1284 Update Parity Sokol node tests
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/parity/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_download_block_1_downloads_the_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_duplicate_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_pending.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_saves_the_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/ethereumex_extensions_trace_transaction_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_duplicate.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_earliest.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_integer.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_latest.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_string.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_receipt_perform_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1_with_contract_creation.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_binds_internal_transactions.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_from_address.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address_from_creates.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction_with_a_bad_hash.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_failed.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_out_of_gas.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_pending.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_receipt.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_saves_the_transaction.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_saves_the_association.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_txn_without_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_updates_the_association.json
Labels: in progress
