Repository blockscout/blockscout, pull requests merged in 2018-11, with the labels that each got.

#1022 address type is printed weird on smart contracts
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
Labels: in progress, ready for review

#1030 Infinite scroll on address transactions page
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/__tests__/pages/blocks.js
  apps/block_scout_web/assets/__tests__/pages/pending_transactions.js
  apps/block_scout_web/assets/__tests__/pages/transaction.js
  apps/block_scout_web/assets/__tests__/pages/transactions.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/blocks.js
  apps/block_scout_web/assets/js/pages/pending_transactions.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/js/pages/transactions.js
  apps/block_scout_web/assets/js/utils.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
Labels: in progress, ready for review

#1033 Add GraphiQL link to topnav
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#1032 Adds hash to GraphQL block object
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/test/block_scout_web/schema/query/block_test.exs
Labels: in progress, ready for review

#1031 GraphQL API query to get addresses by hash
  apps/block_scout_web/lib/block_scout_web/resolvers/address.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/scalars.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
Labels: in progress, ready for review

#1028 Add configurable block transformers
  .circleci/config.yml
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/request_coordinator_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket/web_socket_client_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/transform.ex
  apps/indexer/lib/indexer/block/transform/base.ex
  apps/indexer/lib/indexer/block/transform/clique.ex
  apps/indexer/lib/indexer/block/util.ex
  apps/indexer/mix.exs
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/transform/base_test.exs
  apps/indexer/test/indexer/block/transform/clique_test.exs
  apps/indexer/test/indexer/block/transform_test.exs
  apps/indexer/test/indexer/block/uncle/fetcher_test.exs
  apps/indexer/test/indexer/block/util_test.exs
  mix.lock
Labels: in progress, ready for review

#1040 Performance improvements to generation of top accounts page
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1034 Add gettxinfo API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Labels: in progress

#1035 Design Touch-ups
  apps/block_scout_web/assets/css/_code.scss
  apps/block_scout_web/assets/css/_typography.scss
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/js/lib/try_api.js
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: design, enhancement, in progress, ready for review

#1050 Fix no schema on GraphiQL
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
Labels: in progress, ready for review

#1009 Optmize address transactions page
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review, testing

#1045 Add smart_contract field to address object
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/scalars.ex
  apps/block_scout_web/lib/block_scout_web/schema/scalars/JSON.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/explorer/lib/explorer/chain.ex
  mix.lock
Labels: in progress, ready for review

#1048 import addresses when importing token balances
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
Labels: in progress, ready for review

#1063 Remove the 'pending transactions' from the address transaction page.
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1065 Neutral BlockScout theme and logo
  apps/block_scout_web/assets/css/theme/_neutral_variables.scss
  apps/block_scout_web/assets/css/theme/_variables.scss
  apps/block_scout_web/assets/static/images/blockscout_logo.svg
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: design, enhancement, in progress

#1059 feat: decode transaction input on overview
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_transaction-input.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/clipboard_buttons.js
  apps/block_scout_web/assets/js/lib/swappable_item.js
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/support/factory.ex
  mix.lock
Labels: in progress

#1057 Add GraphQL API references to RPC API docs
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
Labels: in progress, ready for review

#1058 Infinte scroll on blocks and transactions pages
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/__tests__/pages/blocks.js
  apps/block_scout_web/assets/__tests__/pages/pending_transactions.js
  apps/block_scout_web/assets/__tests__/pages/transactions.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/infinite_scroll_helpers.js
  apps/block_scout_web/assets/js/lib/redux_helpers.js
  apps/block_scout_web/assets/js/lib/utils.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/blocks.js
  apps/block_scout_web/assets/js/pages/pending_transactions.js
  apps/block_scout_web/assets/js/pages/reorgs.js
  apps/block_scout_web/assets/js/pages/transactions.js
  apps/block_scout_web/assets/js/pages/uncles.js
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/pending_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
Labels: in progress, ready for review

#1076 Load first page of address transactions asynchronously
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
Labels: in progress, ready for review

#1073 Update dependencies in README
  README.md
Labels: in progress

#1062 Add 404 page for not found blocks
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/404.html.eex
  apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
Labels: in progress, ready for review

#1081 Fix project timeline link on README
  README.md
Labels: in progress

#1071 transaction not found page and transaction hash invalid page
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/invalid.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/not_found.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
Labels: in progress, ready for review

#1079 Fix performance issue in address page
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
Labels: in progress, ready for review

#1090 Fix pattern matching error when transaction does not loads to_address.smart_contract
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
  apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
Labels: bug :bug:, in progress, ready for review

#1072 Geth internal transactions
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/internal_transaction_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/calls.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth/call_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth/calls_tests.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/internal_transaction/type.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/priv/repo/migrations/20181107164103_eip6.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/address/coin_balances.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/test/indexer/address/coin_balances_test.exs
Labels: enhancement, in progress, ready for review, team: architecture

#1094 Extract input from Parity call traces
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20181108205650_additional_internal_transaction_constraints.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: bug :bug:, in progress

#1078 Improve Token.Fetcher to retries and log functions that raised error
  apps/explorer/config/config.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/lib/explorer/token/metadata_retriever.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/explorer/test/explorer/token/metadata_retriever_test.exs
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/token/fetcher_test.exs
  config/config.exs
Labels: in progress, ready for review, testing

#1096 Add `dev` dependency to cowboy in the `ethereum_jsonrpc` app
  apps/ethereum_jsonrpc/mix.exs
Labels: bug :bug:, in progress

#1102 Support Parity 2.1 pending tag output
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
Labels: bug :bug:, in progress, ready for review

#1098 Improve TokenBalance.Fetcher to ignore the ones that always raise errors
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
  apps/indexer/test/indexer/token_balances_test.exs
Labels: in progress, ready for review

#1100 GraphQL support to get transactions by address
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/address.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/transaction.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/addresses_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/node_test.exs
  apps/explorer/lib/explorer/graphql.ex
  apps/explorer/test/explorer/graphql_test.exs
  mix.lock
Labels: in progress, ready for review

#1105 fetch_beneficiaries/2 works with all reward types
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
Labels: in progress, ready for review

#1118 Update README with Other Projects
  README.md
  blockscout.png
Labels: in progress

#1119 feat: fix ABI decoding, and decode tx logs
  apps/block_scout_web/assets/css/components/_transaction-input.scss
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_log_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/abi_encoded_value_view_test.exs
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/test/explorer/chain/log_test.exs
  mix.lock
Labels: in progress

#1113 Add unit price to address details page
  apps/block_scout_web/assets/js/lib/currency.js
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1095 Async task to check token metadata
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/test/explorer/chain/token_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/token/metadata_updater.ex
  apps/indexer/lib/indexer/token/supervisor.ex
  apps/indexer/test/indexer/token/metadata_updater_test.exs
Labels: in progress, ready for review

#1103 async load token transfers
  apps/block_scout_web/assets/.eslintrc
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/async_listing_load.js
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/token_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
Labels: in progress, ready for review

#1126 Fix typo in "validation count" reducer when loading state.
  apps/block_scout_web/assets/js/pages/address.js
Labels: bug :bug:, in progress, ready for review

#1138 Fix CircleCI Tests and add Ganache as default Client
  README.md
  apps/ethereum_jsonrpc/README.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/parity/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex
  apps/explorer/config/dev.exs
  apps/explorer/config/dev/parity.exs
  apps/explorer/config/prod/parity.exs
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_download_block_1_downloads_the_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_duplicate_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_pending.json
  apps/explorer/test/support/fixture/vcr_cassettes/block_importer_import_1_saves_the_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/ethereumex_extensions_trace_transaction_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_duplicate.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_earliest.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_integer.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_latest.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_block_perform_1_string.json
  apps/explorer/test/support/fixture/vcr_cassettes/import_receipt_perform_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1.json
  apps/explorer/test/support/fixture/vcr_cassettes/internal_transaction_importer_import_1_with_contract_creation.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_binds_internal_transactions.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_from_address.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_creates_a_to_address_from_creates.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_download_transaction_with_a_bad_hash.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_failed.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_out_of_gas.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_pending.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_1_receipt.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_import_saves_the_transaction.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_saves_the_association.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_txn_without_block.json
  apps/explorer/test/support/fixture/vcr_cassettes/transaction_importer_updates_the_association.json
  apps/indexer/README.md
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  docker/README.md
Labels: in progress

#1133 make internal transactions load async
  apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: in progress, ready for review

#1124 Fix performance issue at token transfers tab on Token's page
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
  apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/priv/repo/migrations/20181121170616_add_block_number_to_token_transfers.exs
  apps/explorer/priv/repo/migrations/scripts/20181121170616_token_transfers_update_block_number_in_batches.sql
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#1140 Add nonce field to addresses table
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/import/addresses.ex
  apps/explorer/priv/repo/migrations/20181106152300_add_nonce_to_addresses.exs
  apps/explorer/priv/repo/migrations/20181126203826_add_index_to_addresses.exs
  apps/explorer/priv/repo/migrations/scripts/20181126182700_migrate_address_nonce.sql
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/test/indexer/address_extraction_test.exs
Labels: in progress, ready for review

#1116 Async load in token transfers at adress page
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: in progress, ready for review

#1135 Partial retry for batched JSONRPC requests
  .credo.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_hash.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_number.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_tag.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_balance.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_balances.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_beneficiaries.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_beneficiary.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  apps/indexer/test/indexer/block/uncle/fetcher_test.exs
  apps/indexer/test/indexer/coin_balance/fetcher_test.exs
Labels: enhancement, in progress, ready for review, team: architecture

#1148 Update npm dependencies
  apps/block_scout_web/assets/package-lock.json
Labels: in progress, ready for review

#1144 Async loading on the token holders page
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
Labels: in progress, ready for review

#1159 Remove references from pending transactions feature
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
Labels: in progress, ready for review

#1111 Allow gradual data migration after schema and code is deployed
  apps/explorer/lib/explorer/chain/internal_transaction/type.ex
  apps/explorer/priv/repo/migrations/20181107164103_eip6.exs
  apps/explorer/priv/repo/migrations/20181108205650_additional_internal_transaction_constraints.exs
  apps/explorer/priv/repo/migrations/scripts/20181107164103_eip6.sql
  apps/explorer/priv/repo/migrations/scripts/20181108205650_additional_internal_transaction_constraints.sql
Labels: bug :bug:, in progress, ready for review, team: architecture

#1157 Gsf fix contract code display
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_highlight.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/smart_contract/code_highlighting.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_contract_view_test.exs
Labels: in progress, ready for review

#1131 Add release build
  .circleci/config.yml
  apps/explorer/lib/release_tasks.ex
  mix.exs
  mix.lock
  rel/commands/migrate.sh
  rel/commands/seed.sh
  rel/config.exs
  rel/plugins/.gitignore
  rel/vm.args
Labels: in progress
