Repository blockscout/blockscout, pull requests merged in 2018-09, with the labels that each got.

#645 Live reload all USD conversions as exchange rates change
  .gitignore
  apps/block_scout_web/assets/__tests__/lib/currency.js
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/currency.js
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/exchange_rates/usd.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_token_holdings.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
  apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/exchange_rates/usd_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/chain_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/currency_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  coveralls.json
Labels: ready for review

#661 Treat "status" => nil the same as no "status"
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
Labels: bug, enhancement, team: architecture

#660 Use `txs` for list, `tx` or `address` for individual pages, respectively
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_contract_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: ready for review

#659 Add coverage for files that report fluctuating coverage
  apps/block_scout_web/test/block_scout_web/controllers/address_token_balance_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/explorer/test/support/factory.ex
Labels: bug, ready for review, team: architecture, team: contributor, team: developer

#615 312 live update internal transactions on address page
  apps/block_scout_web/assets/__tests__/pages/block.js
  apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/event_handler.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/chain_test.exs
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/test/explorer/chain/import_test.exs
Labels: ready for review, real-time, team: contributor

#678 Fix circle test reporting
  .circleci/config.yml
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_balance_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_contract_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/test/indexer/block_fetcher/realtime_test.exs
Labels: priority: high, severity: 3

#674 Refactor button class names
  apps/block_scout_web/assets/css/components/_button.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
Labels: ready for review

#682 Updated sokol logo
  apps/block_scout_web/assets/static/images/sokol_logo.svg
Labels: ready for review

#680 Token Details Design Clean Up
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: design, enhancement, ready for review, team: contributor

#649 API account#txlist filterby=from support
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, ready for review

#685 Ignore tokens that have the name and/or symbols with special characters
  apps/indexer/lib/indexer/token_fetcher.ex
  apps/indexer/test/indexer/token_fetcher_test.exs
Labels: ready for review

#694 Temporary work-around for #673 value-only transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Labels: bug

#691 Update search button
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: bug, design, ready for review, team: contributor

#689 672 txn copy button
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: enhancement, ready for review, team: contributor

#606 "Tokens" tab in address page
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_token_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#696 Add contract#getabi API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
Labels: api, ready for review

#701 inculde an example of the config
  apps/explorer/config/dev.secret.exs.example
Labels: ready for review

#700 684 the case of the missing gettext
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review, team: contributor

#705 Deal with :bad_gateway errors while querying contracts functions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: bug, chain: ETH, ready for review, team: developer

#699 easy navigation between token and contract
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#718 Orders account#getminedblocks by block number
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, in progress, ready for review

#716 Update the README to help users configure other chains
  README.md
Labels: in progress, ready for review

#719 readme update deploy
  README.md
Labels: in progress

#704 Support Blockscout deployments which are not at root URLs
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/js/lib/currency.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/js/router.js
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#726 Handle multiple values when reading Smart Contract functions
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/tokens/smart_contract_view_test.exs
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: in progress, ready for review, team: developer

#711 Add contract#getsourcecode API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
Labels: api, in progress, ready for review

#727 Add support for ERC-721 token transfer logs with addresses in `data` field
  apps/indexer/lib/indexer/token_transfers.ex
  apps/indexer/test/indexer/token_transfers_test.exs
Labels: in progress, ready for review

#722 Add transaction#gettxreceiptstatus API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Labels: api, in progress, ready for review

#729 Improve Smart Contract's function response CSS style
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
Labels: in progress, ready for review

#730 Fix Token Holders' link from Read Smart Contract page
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
Labels: in progress, ready for review, team: developer

#717 Increase Indexer.TokenBalance.Fetcher timeout and add treatment error
  apps/explorer/lib/explorer/chain/import.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
Labels: bug, chain: ETH, in progress, team: developer, wip

#733 Handle large strings when fetching tokens
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress, ready for review

#657 Allow blocks.gas_used and gas_limit to be numeric to support higher limits on private chains
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/priv/repo/migrations/20180831231919_modify_block_gas.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#731 Add transaction#getstatus API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, in progress, ready for review

#710 More detail on internal transaction tile and fix address transactions live reload in/out
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/_internal_transaction.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/internal_transaction_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#732 Get transaction status and error from last internal transaction
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/support/factory.ex
Labels: bug, chain: ETC, chain: ETH, in progress, team: architecture, team: contributor

#725 Address/Contract Address Details Mobile Optimization
  apps/block_scout_web/assets/css/_code.scss
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_button.scss
  apps/block_scout_web/assets/css/components/_dropdown.scss
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
Labels: enhancement, in progress, ready for review, team: contributor

#734 Add stats#ethsupply API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Labels: api, in progress, ready for review

#746 Preload contract addresses names for transaction push
  apps/block_scout_web/lib/block_scout_web/notifier.ex
Labels: in progress, ready for review

#750 Add stats#ethprice API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Labels: api, in progress, ready for review

#753 Optimize address page loading
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20180117221922_create_blocks.exs
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/priv/repo/migrations/20180606135150_create_token_transfers.exs
  apps/explorer/priv/repo/migrations/20180831231919_modify_block_gas.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: bug, in progress, priority: critical, ready for review, severity: 1, team: contributor

#761 Alter Token decimals column to bigint
  apps/explorer/priv/repo/migrations/20180919175123_alter_token_decimals_to_bigint.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: bug, chain: ROP, in progress, ready for review

#744 686 account list pg
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/block_scout_web/test/support/fake_adapter.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#754 New log file for TokenBalances interaction errors
  apps/indexer/config/dev.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/test/indexer/token_balances_test.exs
  config/config.exs
Labels: in progress, ready for review

#762 Derive status from internal transaction at index 0
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
Labels: in progress

#747 token balances on token listing for address
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/_tokens.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_token_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/token.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/test/explorer/chain/address/token_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#781 Realtime.Fetcher async fetching and no skips
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/supervisor.ex
Labels: in progress, ready for review

#594 added button to convert wei to ether and vice versa
  .gitignore
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/smart_contract/wei_ether_converter.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/explorer/package-lock.json
Labels: enhancement, in progress, ready for review

#760 Wire-up page reload of pending transaction detail when collated chann…
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_loading-spinner.scss
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
Labels: in progress, ready for review, real-time, team: contributor

#791 Fix token holders' tab at the Token's page when the total supply is nil
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/views/tokens/holder_view.ex
  apps/block_scout_web/test/block_scout_web/views/tokens/holder_view_test.exs
Labels: in progress, ready for review, team: developer

#783 Remove duplicated code from Transaction page
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/tab_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/tab_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
Labels: in progress, ready for review

#804 Upgrade node.js and bootstrap.js
  .tool-versions
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
Labels: in progress, ready for review

#795 Add Favicon Assets
  apps/block_scout_web/assets/static/android-chrome-192x192.png
  apps/block_scout_web/assets/static/android-chrome-512x512.png
  apps/block_scout_web/assets/static/apple-touch-icon.png
  apps/block_scout_web/assets/static/browserconfig.xml
  apps/block_scout_web/assets/static/favicon-16x16.png
  apps/block_scout_web/assets/static/favicon-32x32.png
  apps/block_scout_web/assets/static/favicon.ico
  apps/block_scout_web/assets/static/mstile-150x150.png
  apps/block_scout_web/assets/static/safari-pinned-tab.svg
  apps/block_scout_web/assets/static/site.webmanifest
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: enhancement, in progress, ready for review

#806 Handle more errors types at Smart Contract Reader
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: in progress

#805 Move the contract created by (address) at (transaction) info to its own line
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: enhancement, in progress, ready for review

#809 Realtime indexer waits half a second before fetch
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: chain: SOK, client: parity, in progress, ready for review, real-time

#812 Preload created contract address for transaction logs
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
  apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
Labels: in progress, ready for review

#801 Live reload pending transactions page
  apps/block_scout_web/assets/__tests__/pages/transaction.js
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/js/utils.js
  apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/block_scout_web/test/block_scout_web/views/error_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/explorer/lib/explorer/chain/import.ex
  apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Labels: in progress, ready for review

#782 dynamic token search on balance box
  apps/block_scout_web/assets/css/components/_dropdown.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/token_balance_dropdown_search.js
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: in progress, ready for review

#802 Uncle support
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/phoenix/param.ex
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/phoenix/param/explorer/chain/block_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncle.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncles.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/uncle_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/uncles_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block/second_degree_relation.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/chain/transaction/fork.ex
  apps/explorer/priv/repo/migrations/20180117221922_create_blocks.exs
  apps/explorer/priv/repo/migrations/20180917182319_create_block_second_degree_relations.exs
  apps/explorer/priv/repo/migrations/20180918200001_create_transaction_fork.exs
  apps/explorer/test/explorer/chain/block/second_degree_relation_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/transaction/fork_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/address/coin_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/supervisor.ex
  apps/indexer/test/indexer/address/coin_balances_test.exs
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  apps/indexer/test/indexer/block/uncle/fetcher_test.exs
  apps/indexer/test/support/indexer/block/uncle/supervisor/case.ex
Labels: enhancement, in progress, incompatible changes, team: architecture, team: contributor

#815 Fix token balance fetcher log error
  apps/indexer/lib/indexer/token_balances.ex
Labels: in progress

#819 Realtime fetcher retries for unknown block number
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: enhancement, in progress, ready for review

#817 Add Wobserver
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/mix.exs
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/mix.exs
  apps/indexer/mix.exs
  mix.lock
Labels: enhancement, in progress, ready for review

#825 account#tokenlist API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, in progress, ready for review

#738 Add mined blocks count to miner (validator) address page overview.
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_internal_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_validation_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#826 Indexer.Block.Catchup.BoundIntervalSupervisor is proper supervisor
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
Labels: bug, in progress, ready for review

#830 Ignore burn address token balance for Tokens ERC-721
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/token_balance.ex
  apps/explorer/test/explorer/chain/address/token_balance_test.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/token_transfers.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/token_transfers_test.exs
Labels: in progress, ready for review, team: developer
