Repository blockscout/blockscout, pull requests merged in 2018-07, with the labels that each got.

#347 (enhancement) About us and feature details
  README.md
Labels: in progress

#350 Fix ERC20 token support
  README.md
Labels: in progress

#351 Update Readme fix LGPLv3 to GPLv3
  README.md
Labels: in progress

#333 Live update transactions and overview on address page
  .circleci/config.yml
  README.md
  apps/explorer_web/assets/__tests__/pages/address.js
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_animations.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/from_now.js
  apps/explorer_web/assets/js/lib/reload_button.js
  apps/explorer_web/assets/js/pages/address.js
  apps/explorer_web/assets/js/router.js
  apps/explorer_web/assets/js/socket.js
  apps/explorer_web/assets/js/utils.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/lib/explorer_web/chain.ex
  apps/explorer_web/lib/explorer_web/channels/address_channel.ex
  apps/explorer_web/lib/explorer_web/channels/user_socket.ex
  apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/pending_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/_values.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/channels/address_channel_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/support/channel_case.ex
Labels: in progress

#352 Upgrade and clean up project requirements
  .tool-versions
  README.md
  apps/explorer_web/assets/package-lock.json
Labels: in progress

#353 Upgrade explorer Node.js dependencies to 10.5
  apps/explorer/package-lock.json
Labels: in progress

#354 Upgrade node-sass to quiet npm warnings it was generating
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
Labels: in progress

#357 Real-time indexing starting from the last indexed Block
  apps/indexer/lib/indexer/block_fetcher.ex
Labels: bug, in progress

#361 Set realtime interval to 5 seconds
  apps/indexer/lib/indexer/block_fetcher.ex
Labels: in progress

#346 Homepage redesign
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer/test/explorer/chain/statistics_test.exs
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_address_link.scss
  apps/explorer_web/assets/css/components/_all.scss
  apps/explorer_web/assets/css/components/_button.scss
  apps/explorer_web/assets/css/components/_card.scss
  apps/explorer_web/assets/css/components/_chain.scss
  apps/explorer_web/assets/css/components/_dashboard-banner.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/assets/css/theme/_fonts.scss
  apps/explorer_web/assets/css/theme/_poa_variables.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/card_flip.js
  apps/explorer_web/assets/js/lib/market_history_chart.js
  apps/explorer_web/assets/js/lib/sidebar.js
  apps/explorer_web/lib/explorer_web/controllers/chain_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_topnav.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/home_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
Labels: in progress

#365 Fix eslint in CircleCI which was not running on everything it should
  .circleci/config.yml
Labels: in progress

#380 Fix pending transactions page error
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress

#335 Geth non-incompatibility
  .circleci/config.yml
  apps/ethereum_jsonrpc/.formatter.exs
  apps/ethereum_jsonrpc/config/config.exs
  apps/ethereum_jsonrpc/config/geth.exs
  apps/ethereum_jsonrpc/config/parity.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/decode_error.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/data.ex
  apps/explorer/lib/explorer/chain/hash/address.ex
  apps/explorer/lib/explorer/chain/hash/nonce.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20180117221922_create_blocks.exs
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/priv/repo/migrations/20180212222309_create_logs.exs
  apps/explorer/test/explorer/chain/hash/address_test.exs
  apps/explorer/test/explorer/chain/hash/nonce_test.exs
  apps/explorer/test/explorer/chain/hash/truncated_test.exs
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/.formatter.exs
  apps/indexer/lib/indexer/address_balance_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/lib/indexer/pending_transaction_fetcher.ex
  apps/indexer/test/indexer/address_balance_fetcher_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/internal_transaction_fetcher_test.exs
  apps/indexer/test/indexer/pending_transaction_fetcher_test.exs
  coveralls.json
Labels: bug, enhancement, in progress, incompatible changes

#382 Fix multiple results in Repo.One with multiple create type internal transactions
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
Labels: in progress

#389 Convert Indexer.Sequence to GenServer to trap exits to ensure self-cleanup
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/sequence_test.exs
Labels: architecture, bug, enhancement, in progress, incompatible changes

#392 Change reference to Hash.Address
  apps/explorer/lib/explorer/chain.ex
Labels: in progress

#376 Address pg redesign #231
  apps/explorer/package-lock.json
  apps/explorer_web/assets/css/_layout.scss
  apps/explorer_web/assets/css/_tooltip.scss
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_badge.scss
  apps/explorer_web/assets/css/components/_card.scss
  apps/explorer_web/assets/css/components/_dashboard-banner.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_icon-link.scss
  apps/explorer_web/assets/css/components/_nav_tabs.scss
  apps/explorer_web/assets/css/components/_navbar.scss
  apps/explorer_web/assets/css/components/_qr-code.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/assets/css/theme/_poa_variables.scss
  apps/explorer_web/lib/explorer_web/channels/address_channel.ex
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/_responsive_hash.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
Labels: in progress

#384 Pluggable Transport and HTTP transport modules
  .circleci/config.yml
  apps/ethereum_jsonrpc/README.md
  apps/ethereum_jsonrpc/config/config.exs
  apps/ethereum_jsonrpc/config/geth.exs
  apps/ethereum_jsonrpc/config/parity.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http/httpoison.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace/action.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transport.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/http/case.ex
  apps/ethereum_jsonrpc/test/test_helper.exs
  apps/explorer/lib/explorer/chain.ex
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/geth.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/prod/geth.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_balance_fetcher.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/buffered_task.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/lib/indexer/pending_transaction_fetcher.ex
  apps/indexer/mix.exs
  apps/indexer/test/indexer/address_balance_fetcher_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/buffered_task_test.exs
  apps/indexer/test/indexer/internal_transaction_fetcher_test.exs
  apps/indexer/test/indexer/pending_transaction_fetcher_test.exs
  apps/indexer/test/test_helper.exs
Labels: bug, enhancement, in progress, incompatible changes

#395 Transaction list page redesign
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/_responsive_hash.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress

#404 Fix Indexer Supervisor tree
  apps/indexer/lib/indexer/application.ex
Labels: in progress

#362 Add contract creator on Account details page
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_contract_controller_test.exs
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
Labels: contract details

#409 Enhance API account balance endpoint
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: in progress

#413 Add RPC API account balancemulti
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: in progress, ready for review

#411 Fix chunking issues with BlockFetcher and Sequence
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/test/indexer/sequence_test.exs
Labels: bug, in progress, incompatible changes, ready for review

#412 Add transaction status indicator
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/assets/css/theme/_poa_variables.scss
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/pages/block_page.ex
  apps/explorer_web/test/explorer_web/features/pages/home_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress, ready for review

#419 Split batches on 504 Gateway Timeout
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
Labels: bug, in progress, ready for review, team: architecture

#432 Fix dropdown overlaps on homepage.
  apps/explorer_web/assets/css/components/_dashboard-banner.scss
Labels: in progress, ready for review

#428 Dynamically add websocket endpoint to CSP
  apps/explorer_web/.sobelow-conf
  apps/explorer_web/lib/explorer_web/csp_header.ex
  apps/explorer_web/lib/explorer_web/router.ex
Labels: in progress, ready for review

#427 Add account transactions API RPC endpoint
  .credo.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/rpc_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: api, in progress, ready for review

#436 Set up contract verification test with `create` internal transaction
  apps/explorer/test/support/factory.ex
  apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
Labels: bug, contract verification, in progress, ready for review

#441 Restore factory needed by tests
  apps/explorer/test/support/factory.ex
Labels: in progress

#279 (Feature) Smart contract function reading
  README.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/dev/geth.exs
  apps/explorer/config/dev/parity.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/prod/geth.exs
  apps/explorer/config/prod/parity.exs
  apps/explorer/config/test.exs
  apps/explorer/config/test/geth.exs
  apps/explorer/config/test/parity.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer/test/test_helper.exs
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/smart_contract/read_function.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/lib/explorer_web/controllers/address_read_contract_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_read_contract/_function_response.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_read_contract/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_contract_view.ex
  apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_read_contract_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/package-lock.json
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_read_contract_controller_test.exs
  apps/explorer_web/test/explorer_web/views/address_read_contract_view_test.exs
  apps/explorer_web/test/explorer_web/views/address_view_test.exs
  mix.lock
Labels: Feature, in progress, ready for review

#426 Add Token and TokenTransfers schema
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/priv/repo/migrations/20180606135149_create_tokens.exs
  apps/explorer/priv/repo/migrations/20180606135150_create_token_transfers.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#429 Blockchain event registry
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/assets/__tests__/pages/address.js
  apps/explorer_web/assets/__tests__/pages/transaction.js
  apps/explorer_web/assets/js/pages/address.js
  apps/explorer_web/assets/js/pages/transaction.js
  apps/explorer_web/lib/explorer_web/application.ex
  apps/explorer_web/lib/explorer_web/channels/address_channel.ex
  apps/explorer_web/lib/explorer_web/channels/transaction_channel.ex
  apps/explorer_web/lib/explorer_web/event_handler.ex
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/explorer_web/lib/explorer_web/templates/address/_balance_card.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/_values.html.eex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
Labels: in progress, priority: high, ready for review, real-time

#443 Allow test environment configuration to be overridden similar to dev
  README.md
  apps/explorer/config/test.exs
  apps/explorer/config/test.secret.exs.example
Labels: in progress, ready for review

#440 Add optional params to account txlist API endpoint
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/address_controller.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: api, in progress, ready for review

#431 Historical Address Balances
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/balance.ex
  apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs
  apps/explorer/test/explorer/chain/address_test.exs
  apps/explorer/test/explorer/chain/balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/event_handler.ex
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/indexer/lib/indexer/address_balance_fetcher.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/balance_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/buffered_task.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/test/indexer/balance_fetcher_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/sequence_test.exs
  apps/indexer/test/support/indexer/address_balance_fetcher_case.ex
Labels: enhancement, in progress, incompatible changes, ready for review

#449 Fix prod config file to use prod config instead of dev
  apps/indexer/config/prod.exs
Labels: in progress, ready for review

#452 Fixed social media links
  apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: enhancement, in progress, ready for review, team: contributor

#457 Disable EventHandler (live updates) because of memory leak
  apps/explorer_web/lib/explorer_web/application.ex
Labels: in progress

#439 Prevent holes and fill in holes during realtime indexing
  apps/explorer/config/test.exs
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/indexer/config/dev/geth.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/geth.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/bound_interval.ex
  apps/indexer/lib/indexer/pending_transaction_fetcher.ex
  apps/indexer/test/indexer/block_fetcher_test.exs
Labels: bug, in progress, incompatible changes, ready for review

#464 Don't submit test results to coveralls.ios for forks
  .circleci/config.yml
Labels: bug, in progress

#468 Subscribe to only realtime-indexer events for channel broadcasts
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/test/indexer/block_fetcher_test.exs
Labels: in progress, priority: high, ready for review, real-time

#451 Transaction detail #369
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/lib/explorer_web/templates/address/_responsive_hash.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/transaction_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: design, in progress, team: contributor

#467 Unified Explorer.Chain.import
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/import_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/indexer/lib/indexer/balance_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/lib/indexer/pending_transaction_fetcher.ex
  apps/indexer/test/indexer/sequence_test.exs
Labels: bug, enhancement, in progress, incompatible changes, ready for review

#459 geth configureable from environment
  apps/explorer/config/dev.exs
  apps/explorer/config/dev/geth.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/prod/geth.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/geth.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/prod/geth.exs
Labels: enhancement, team: architecture, wip

#475 Fix transaction addresses wrapping onto two lines
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/_internal_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/_internal_transaction.html.eex
Labels: in progress, ready for review

#462 Live reload blocks on homepage
  apps/explorer_web/assets/__tests__/pages/chain.js
  apps/explorer_web/assets/css/components/_animations.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/from_now.js
  apps/explorer_web/assets/js/pages/address.js
  apps/explorer_web/assets/js/pages/chain.js
  apps/explorer_web/assets/js/pages/transaction.js
  apps/explorer_web/assets/js/router.js
  apps/explorer_web/lib/explorer_web/channels/block_channel.ex
  apps/explorer_web/lib/explorer_web/channels/user_socket.ex
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/explorer_web/lib/explorer_web/templates/chain/_block.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/home_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
Labels: in progress, priority: high, ready for review, real-time

#479 Update block list page design
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_block.html.eex
  apps/explorer_web/lib/explorer_web/views/block_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review
