Repository blockscout/blockscout, pull requests merged in 2018-04, with the labels that each got.

#87 Migrate from CircleCI 1.0 to 2.0
  .circleci/config.yml
  .circleci/elixir-node-ruby/Dockerfile
  .circleci/elixir-node-ruby/README.md
  .circleci/setup-heroku.sh
  .credo.exs
  .tool-versions
  apps/explorer/mix.exs
  apps/explorer/test/test_helper.exs
  apps/explorer_web/mix.exs
  apps/explorer_web/test/test_helper.exs
  circle.yml
  elixir_buildpack.config
  mix.exs
Labels: architecture, enhancement, in progress, incompatible changes

#93 Format missed files
  .credo.exs
  .formatter.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer_web/config/config.exs
  apps/explorer_web/lib/explorer_web/application.ex
  apps/explorer_web/test/explorer_web/forms/transaction_form_test.exs
Labels: bug, in progress

#100 Update README for correctness
  .circleci/config.yml
  README.md
  apps/explorer/.sobelow-conf
  apps/explorer_web/.sobelow-conf
  mix.lock
Labels: in progress

#113 Fix zombie phantomjs processes
  apps/explorer_web/mix.exs
  mix.lock
Labels: in progress

#117 Remove license finder build requirement
  .circleci/config.yml
  .circleci/elixir-node-ruby/Dockerfile
  .circleci/elixir-node-ruby/README.md
  Gemfile
  Gemfile.lock
  doc/dependency_decisions.yml
Labels: in progress

#114 Remove transaction hash from detail page
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Labels: in progress

#115 Add exchange rate cache
  .gitignore
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/lib/explorer/exchange_rates/rate.ex
  apps/explorer/lib/explorer/exchange_rates/source.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs
  apps/explorer/test/test_helper.exs
  config/test.exs
  mix.lock
Labels: in progress

#125 Add bootstrap, jQuery, and autoprefixer to project
  apps/explorer_web/README.md
  apps/explorer_web/assets/.eslintrc
  apps/explorer_web/assets/brunch-config.js
  apps/explorer_web/assets/css/_fonts.scss
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/_utilities.scss
  apps/explorer_web/assets/css/_variables.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_container.scss
  apps/explorer_web/assets/css/components/_section.scss
  apps/explorer_web/assets/css/explorer/_button.scss
  apps/explorer_web/assets/css/explorer/_sb-admin-2.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/assets/yarn.lock
Labels: in progress

#128 Replace form modules with proper view module functions
  .circleci/config.yml
  .credo.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/gas.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/test/explorer/chain/wei_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factories/chain/receipt_factory.ex
  apps/explorer_web/README.md
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_from_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_to_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/pending_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/lib/explorer_web/forms/block_form.ex
  apps/explorer_web/lib/explorer_web/forms/pending_transaction_form.ex
  apps/explorer_web/lib/explorer_web/forms/transaction_form.ex
  apps/explorer_web/lib/explorer_web/helpers/wei_converter.ex
  apps/explorer_web/lib/explorer_web/templates/address/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction_from/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction_to/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/show.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_from_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_to_view.ex
  apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/block_view.ex
  apps/explorer_web/lib/explorer_web/views/chain_view.ex
  apps/explorer_web/lib/explorer_web/views/pending_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_transaction_from_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_to_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  apps/explorer_web/test/explorer_web/forms/block_form_test.exs
  apps/explorer_web/test/explorer_web/forms/pending_transaction_form_test.exs
  apps/explorer_web/test/explorer_web/forms/transaction_form_test.exs
  apps/explorer_web/test/explorer_web/helpers/wei_converter_test.exs
  apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
  coveralls.json
  mix.lock
Labels: architecture, bug, enhancement, in progress, incompatible changes

#131 Standardize tools to 120 columns
  .credo.exs
  .formatter.exs
  apps/explorer/config/prod.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/workers/refresh_balance.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain/block_test.exs
  apps/explorer/test/explorer/chain/credit_test.exs
  apps/explorer/test/explorer/chain/debit_test.exs
  apps/explorer/test/explorer/chain/statistics_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/importers/block_importer_test.exs
  apps/explorer/test/explorer/importers/internal_transaction_importer_test.exs
  apps/explorer/test/explorer/importers/receipt_importer_test.exs
  apps/explorer/test/explorer/importers/transaction_importer_test.exs
  apps/explorer/test/explorer/workers/import_balance_test.exs
  apps/explorer/test/explorer/workers/import_internal_transaction_test.exs
  apps/explorer/test/explorer/workers/import_receipt_test.exs
  apps/explorer/test/explorer/workers/import_transaction_test.exs
  apps/explorer_web/lib/explorer_web/chain.ex
  apps/explorer_web/lib/explorer_web/controllers/block_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction_from/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction_to/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_header.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_transaction_from_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_to_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/chain_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
Labels: bug, enhancement, in progress

#126 Add missing fields for rates
  apps/explorer/lib/explorer/exchange_rates/rate.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs
Labels: in progress

#130 Account page revised transactions list #14
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/_utilities.scss
  apps/explorer_web/assets/css/_variables.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_container.scss
  apps/explorer_web/assets/css/explorer/_button.scss
  apps/explorer_web/assets/css/explorer/_filter.scss
  apps/explorer_web/assets/css/explorer/_sb-admin-2.scss
  apps/explorer_web/assets/css/theme/_fonts.scss
  apps/explorer_web/assets/css/theme/_neutral-variables.scss
  apps/explorer_web/assets/css/theme/_variables.scss
  apps/explorer_web/lib/explorer_web/controllers/address_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_from_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_to_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction_from/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_from_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_to_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_to_controller_test.exs
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  apps/explorer_web/test/explorer_web/views/address_transaction_view_test.exs
Labels: in progress

#136 Navigation implementation #127
  apps/explorer_web/assets/brunch-config.js
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_all.scss
  apps/explorer_web/assets/css/components/_container.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_header.scss
  apps/explorer_web/assets/css/components/_menu.scss
  apps/explorer_web/assets/css/explorer/_wrapper.scss
  apps/explorer_web/assets/css/theme/_neutral-variables.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/sidebar.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_header.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/views/layout_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  coveralls.json
Labels: in progress

#133 Remove Heroku
  .circleci/config.yml
  .circleci/setup-heroku.sh
  Procfile
  README.md
  apps/explorer/README.md
  apps/explorer_web/README.md
  apps/explorer_web/config/prod.exs
  bin/deploy
  bin/start-pgbouncer-stunnel
  elixir_buildpack.config
  phoenix_static_buildpack.config
Labels: in progress

#143 Footer implementation #139
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_menu.scss
  apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#146 View all button #144
  apps/explorer_web/assets/css/components/_blocks.scss
  apps/explorer_web/assets/css/components/_transactions.scss
  apps/explorer_web/assets/css/explorer/_button.scss
  apps/explorer_web/assets/css/explorer/_wrapper.scss
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#149 Social links #147
  apps/explorer_web/assets/css/components/_header.scss
  apps/explorer_web/assets/css/components/_menu.scss
  apps/explorer_web/assets/css/explorer/_wrapper.scss
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
Labels: in progress

#140 Block detail overview in header #91
  apps/explorer_web/lib/explorer_web/controllers/block_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/block/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/block_controller_test.exs
Labels: in progress
