Repository blockscout/blockscout, pull requests merged in 2018-05, with the labels that each got.

#154 Sidenav bug #150
  apps/explorer_web/assets/css/_content.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_header.scss
  apps/explorer_web/assets/css/components/_sidebar.scss
  apps/explorer_web/assets/css/explorer/_wrapper.scss
  apps/explorer_web/assets/css/theme/_neutral-variables.scss
  apps/explorer_web/assets/js/lib/sidebar.js
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#155 Exclude internal transactions with no siblings in parent transaction #151
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/templates/transaction/show.html.eex
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
Labels: in progress

#156 Internal transactions on address #15
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factories/chain/transaction_factory.ex
  apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/features/address_page_test.exs
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  coveralls.json
Labels: in progress

#164 Migrate to Webpack
  .circleci/config.yml
  .gitignore
  apps/explorer_web/assets/.eslintrc
  apps/explorer_web/assets/babelrc
  apps/explorer_web/assets/brunch-config.js
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/block_subscription.js
  apps/explorer_web/assets/js/lib/react_phoenix.js
  apps/explorer_web/assets/js/lib/sidebar.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/assets/postcss.config.js
  apps/explorer_web/assets/spec/lib/block_subscription_spec.js
  apps/explorer_web/assets/spec/spec_helper.js
  apps/explorer_web/assets/spec/support/jasmine.scss
  apps/explorer_web/assets/webpack.config.js
  apps/explorer_web/config/dev.exs
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/mix.exs
  apps/explorer_web/test/explorer_web/features/javascript_test.exs
  mix.lock
Labels: in progress

#157 Add Historical Data
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/statistics/server.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/lib/explorer/exchange_rates/source.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
  apps/explorer/lib/explorer/exchange_rates/token.ex
  apps/explorer/lib/explorer/market/history/cataloger.ex
  apps/explorer/lib/explorer/market/history/source.ex
  apps/explorer/lib/explorer/market/history/source/crypto_compare.ex
  apps/explorer/lib/explorer/market/market.ex
  apps/explorer/lib/explorer/market/market_history.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20180424203101_create_market_history.exs
  apps/explorer/test/explorer/chain/statistics/server_test.exs
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs
  apps/explorer/test/explorer/market/history/cataloger_test.exs
  apps/explorer/test/explorer/market/history/source/crypto_compare_test.exs
  apps/explorer/test/explorer/market/market_test.exs
  apps/explorer/test/test_helper.exs
  mix.lock
Labels: in progress

#163 Configurable social media links
  apps/explorer_web/config/config.exs
  apps/explorer_web/lib/explorer_web/social_media.ex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/views/layout_view.ex
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  apps/explorer_web/test/explorer_web/social_media_test.exs
  apps/explorer_web/test/support/feature_case.ex
Labels: in progress

#166 Upgrade fontawesome
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/assets/webpack.config.js
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
Labels: in progress

#145 Add Wei Ecto type
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/credit.ex
  apps/explorer/lib/explorer/chain/debit.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/test/explorer/chain/credit_test.exs
  apps/explorer/test/explorer/chain/debit_test.exs
  apps/explorer/test/explorer/chain/wei_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/importers/balance_importer_test.exs
  apps/explorer/test/explorer/importers/transaction_importer_test.exs
  apps/explorer/test/explorer/workers/import_balance_test.exs
  apps/explorer/test/explorer/workers/refresh_balance_test.exs
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/show.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/block_view.ex
  apps/explorer_web/lib/explorer_web/views/chain_view.ex
  apps/explorer_web/lib/explorer_web/views/pending_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/wei_helpers.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/views/address_transaction_view_test.exs
  apps/explorer_web/test/explorer_web/views/wei_helpers_test.exs
Labels: enhancement, in progress

#175 Update to credo 0.9.2
  apps/explorer/mix.exs
  apps/explorer_web/mix.exs
  mix.lock
Labels: in progress

#173 Market history chart #29
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/lib/explorer/exchange_rates/token.ex
  apps/explorer/lib/explorer/market/market.ex
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/support/factories/market/market_history_factory.ex
  apps/explorer/test/support/factory.ex
  apps/explorer/test/support/fakes/no_op_source.ex
  apps/explorer_web/assets/.babelrc
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_chain.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/market_history_chart.js
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
  apps/explorer_web/lib/explorer_web/controllers/chain_controller.ex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/views/chain_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/chain_controller_test.exs
  config/test.exs
  coveralls.json
Labels: in progress

#170 Add transaction count to address page
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/controllers/address_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/address_page_test.exs
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
Labels: in progress

#180 Store variable-length DATA as Explorer.Chain.Data
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/data.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/priv/repo/migrations/20180212222309_create_logs.exs
  apps/explorer/priv/repo/migrations/20180221001948_create_internal_transactions.exs
  apps/explorer/test/explorer/chain/data_test.exs
  apps/explorer/test/explorer/chain/internal_transaction_test.exs
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/string/chars/explorer/chain/data_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/phoenix/html/safe.ex
  apps/explorer_web/test/explorer_web/features/contributor_browsing_test.exs
  coveralls.json
Labels: enhancement, in progress, incompatible changes

#178 Use configuration to conditionally start processes
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/coveralls.json
  apps/explorer/lib/explorer/application.ex
Labels: architecture, in progress

#188 Fix flaky tests
  apps/explorer/test/explorer/chain/statistics/server_test.exs
Labels: bug, in progress

#181 Initial AWS deployment config and scripts
  .circleci/config.yml
  appspec.yml
  bin/deploy
  bin/deployment/build
  bin/deployment/health_check
  bin/deployment/migrate
  bin/deployment/start
  bin/deployment/stop
Labels: Vienna, in progress

#201 Show USD values for the POA Values in Transaction Details and Account Details
  apps/explorer/lib/explorer.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/market/history/source/crypto_compare.ex
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/chain_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/lib/explorer_web/exchange_rates/usd.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/currency_helpers.ex
  apps/explorer_web/lib/explorer_web/views/transaction_internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/exchange_rates/usd_test.exs
  apps/explorer_web/test/explorer_web/views/address_view_test.exs
  apps/explorer_web/test/explorer_web/views/currency_helpers_test.exs
  apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
  apps/explorer_web/test/support/conn_case.ex
  apps/explorer_web/test/support/factory.ex
Labels: in progress

#172 Require index to be passed as an argument for internal transaction factory
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: Vienna, in progress

#206 Change Gas Price to show Ether/Gwei instead of Wei/Gwei
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Labels: in progress

#203 Remove unnecessary style code
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_address.scss
  apps/explorer_web/assets/css/components/_all.scss
  apps/explorer_web/assets/css/components/_block.scss
  apps/explorer_web/assets/css/components/_button.scss
  apps/explorer_web/assets/css/components/_filter.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_section.scss
  apps/explorer_web/assets/css/components/_table.scss
  apps/explorer_web/assets/css/components/_transaction_log.scss
  apps/explorer_web/assets/css/explorer/_all.scss
  apps/explorer_web/assets/css/explorer/_color.scss
  apps/explorer_web/assets/css/explorer/_header.scss
  apps/explorer_web/assets/css/explorer/_open_sans.scss
  apps/explorer_web/assets/css/explorer/_paper.scss
  apps/explorer_web/assets/css/explorer/_typography.scss
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#202 Remove decimal commas
  apps/explorer_web/lib/explorer_web/exchange_rates/usd.ex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/chain_view.ex
  apps/explorer_web/lib/explorer_web/views/currency_helpers.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/wei_helpers.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/exchange_rates/usd_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/views/chain_view_test.exs
  apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
Labels: in progress

#208 Apply bootstrap grid and components
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_chain.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/theme/_poa_variables.scss
  apps/explorer_web/assets/css/theme/_theme_ribbon.scss
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_ribbon.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_sidebar.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_topnav.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: Vienna, contributor, design, enhancement, in progress

#207 Display Gas Used on transaction page
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#213 Handle large transaction input content
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/code.scss
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Labels: Vienna, contributor, design, enhancement, in progress

#215 Fix USD value labels on homepage
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#211 Create consistency between internal transaction lists
  apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/lib/explorer_web/views/transaction_internal_transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
Labels: in progress

#194 Move Addresses hashes fetching responsibility closer to BlockFetcher
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/lib/explorer/chain/receipt.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/lib/explorer/indexer/block_fetcher/address_extraction.ex
  apps/explorer/lib/explorer/indexer/supervisor.ex
  apps/explorer/test/explorer/indexer/address_balance_fetcher_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher/address_extraction_test.exs
Labels: developer, in progress

#216 Restore lost change to show ether instead of wei for gas price
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
Labels: in progress

#204 Show contract bytecode
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/indexer/block_fetcher/address_extraction.ex
  apps/explorer/priv/repo/migrations/20180117221921_create_address.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher/address_extraction_test.exs
  apps/explorer_web/lib/explorer_web/controllers/address_contract_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_contract_view.ex
  apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_contract_controller_test.exs
Labels: developer, in progress

#223 Add API to calculate a block reward for a block
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block/range.ex
  apps/explorer/lib/explorer/chain/block/reward.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/priv/repo/migrations/20180522154252_create_btree_gist_extension.exs
  apps/explorer/priv/repo/migrations/20180522154253_create_block_rewards.exs
  apps/explorer/test/explorer/chain/block/range_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/block_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/api/rpc/rpc_translator.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/block_view.ex
  apps/explorer_web/lib/explorer_web/views/api/rpc/rpc_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/api/rpc/rpc_translator_test.exs
Labels: in progress

#221 Only hide "call" type internal transactions
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress

#222 Fold receipts into transactions and denormalize block_number into transactions
  .formatter.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/explorer/README.md
  apps/explorer/benchmarks/explorer/chain/recent_collated_transactions.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/lib/explorer/chain/receipt.ex
  apps/explorer/lib/explorer/chain/receipt/status.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/chain/transaction/status.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/priv/repo/migrations/20180212214442_create_receipts.exs
  apps/explorer/priv/repo/migrations/20180212222309_create_logs.exs
  apps/explorer/test/explorer/chain/receipt/status_test.exs
  apps/explorer/test/explorer/chain/receipt_test.exs
  apps/explorer/test/explorer/chain/statistics_test.exs
  apps/explorer/test/explorer/chain/transaction/status_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/api/rpc/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/chain_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
  apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
  apps/explorer_web/test/support/conn_case.ex
  apps/explorer_web/test/support/factory.ex
  apps/explorer_web/test/support/feature_case.ex
  coveralls.json
  mix.lock
Labels: architecture, bug, in progress, incompatible changes

#218 Defer internal transaction fetching with buffered task queue
  apps/explorer/lib/explorer/buffered_task.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/indexer.ex
  apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/lib/explorer/indexer/internal_transaction_fetcher.ex
  apps/explorer/lib/explorer/indexer/supervisor.ex
  apps/explorer/lib/explorer/schema.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20180117221921_create_address.exs
  apps/explorer/priv/repo/migrations/20180117221922_create_blocks.exs
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/priv/repo/migrations/20180212222309_create_logs.exs
  apps/explorer/priv/repo/migrations/20180221001948_create_internal_transactions.exs
  apps/explorer/test/explorer/buffered_task_test.exs
  apps/explorer/test/explorer/indexer/address_balance_fetcher_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/support/indexer/address_balance_fetcher_case.ex
  apps/explorer/test/support/indexer/internal_transaction_fetcher_case.ex
  coveralls.json
  mix.exs
Labels: in progress
