Repository blockscout/blockscout, pull requests merged in 2018-08, with the labels that each got.

#483 Improve token transfers on transactions tab in the Address details page
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#489 Fetch realtime internal transactions and balances synchronously
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/import_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/balance_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/lib/indexer/block_fetcher/receipts.ex
  apps/indexer/lib/indexer/block_fetcher/supervisor.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/lib/indexer/pending_transaction_fetcher.ex
  apps/indexer/test/indexer/address_extraction_test.exs
  apps/indexer/test/indexer/block_fetcher/realtime_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/supervisor_test.exs
Labels: bug, enhancement, in progress, incompatible changes, ready for review

#500 Restore don't broadcast from catchup
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
Labels: bug, in progress, ready for review

#497 Live reload transactions on homepage #35
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/assets/__tests__/pages/address.js
  apps/explorer_web/assets/__tests__/pages/chain.js
  apps/explorer_web/assets/__tests__/pages/transaction.js
  apps/explorer_web/assets/css/components/_animations.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/pages/address.js
  apps/explorer_web/assets/js/pages/block.js
  apps/explorer_web/assets/js/pages/chain.js
  apps/explorer_web/assets/js/pages/transaction.js
  apps/explorer_web/lib/explorer_web/channels/block_channel.ex
  apps/explorer_web/lib/explorer_web/channels/transaction_channel.ex
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/_tile.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_block.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_tile.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/pages/home_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress, priority: high, ready for review, real-time, team: contributor

#501 Denormalize contract creation address on transaction
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/priv/repo/migrations/20180117221923_create_transactions.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer/test/explorer/import_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress, incompatible changes, ready for review

#499 Adds API docs page with 'try it' UI
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_card.scss
  apps/explorer_web/assets/css/components/_nounderline-link.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/pretty_json.js
  apps/explorer_web/assets/js/lib/try_api.js
  apps/explorer_web/lib/explorer_web/controllers/api_docs_controller.ex
  apps/explorer_web/lib/explorer_web/etherscan.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/api_docs/_action_tile.html.eex
  apps/explorer_web/lib/explorer_web/templates/api_docs/_model_table.html.eex
  apps/explorer_web/lib/explorer_web/templates/api_docs/_module_card.html.eex
  apps/explorer_web/lib/explorer_web/templates/api_docs/index.html.eex
  apps/explorer_web/lib/explorer_web/views/api_docs_view.ex
  apps/explorer_web/test/explorer_web/controllers/api_docs_controller_test.exs
Labels: api, in progress, ready for review

#484 Catalog token transfers and tokens during indexing
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20180606135149_create_tokens.exs
  apps/explorer/priv/repo/migrations/20180606135150_create_token_transfers.exs
  apps/explorer/test/explorer/chain/data_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/import_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/endpoint.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/_link.html.eex
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/lib/indexer/token_fetcher.ex
  apps/indexer/lib/indexer/token_transfers.ex
  apps/indexer/mix.exs
  apps/indexer/test/indexer/address_extraction_test.exs
  apps/indexer/test/indexer/block_fetcher/realtime_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/supervisor_test.exs
  apps/indexer/test/indexer/token_fetcher_test.exs
  apps/indexer/test/indexer/token_transfers_test.exs
  apps/indexer/test/support/indexer/token_fetcher_case.ex
  mix.lock
Labels: Vienna, enhancement, in progress, ready for review, tokens

#495 Fix tokens transfers info according to the tokens' type
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/_transaction.html.eex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/currency_helpers.ex
  apps/explorer_web/lib/explorer_web/views/token_helpers.ex
  apps/explorer_web/test/explorer_web/views/address_transaction_view_test.exs
  apps/explorer_web/test/explorer_web/views/currency_helpers_test.exs
  apps/explorer_web/test/explorer_web/views/token_helpers_test.exs
Labels: in progress, ready for review

#508 Improves API test coverage
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: api, in progress, ready for review

#509 Edit API account balance actions to return Wei
  apps/explorer_web/lib/explorer_web/views/api/rpc/address_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/rpc/address_controller_test.exs
Labels: api, in progress, ready for review

#511 Live update chain statistics #33
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer/lib/explorer/chain/statistics/server.ex
  apps/explorer/test/explorer/chain/statistics/server_test.exs
  apps/explorer/test/explorer/chain/statistics_test.exs
  apps/explorer_web/assets/__tests__/pages/chain.js
  apps/explorer_web/assets/css/components/_animations.scss
  apps/explorer_web/assets/js/pages/chain.js
  apps/explorer_web/config/test.exs
  apps/explorer_web/lib/explorer_web/channels/address_channel.ex
  apps/explorer_web/lib/explorer_web/channels/block_channel.ex
  apps/explorer_web/lib/explorer_web/controllers/chain_controller.ex
  apps/explorer_web/lib/explorer_web/notifier.ex
  apps/explorer_web/lib/explorer_web/templates/chain/_block.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/test/explorer_web/controllers/chain_controller_test.exs
  apps/explorer_web/test/explorer_web/features/pages/chain_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
  apps/explorer_web/test/support/fake_adapter.ex
Labels: in progress, ready for review, real-time, team: contributor

#503 (enhancement) minor README changes
  README.md
  explorer_example.gif
Labels: in progress, ready for review

#512 Adds error example values to API docs page
  apps/explorer_web/lib/explorer_web/etherscan.ex
  apps/explorer_web/lib/explorer_web/templates/api_docs/_action_tile.html.eex
Labels: api, in progress, ready for review

#486 Include a Token details page
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer_web/lib/explorer_web/chain.ex
  apps/explorer_web/lib/explorer_web/controllers/token_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/token/_token_transfer.html.eex
  apps/explorer_web/lib/explorer_web/templates/token/show.html.eex
  apps/explorer_web/lib/explorer_web/views/currency_helpers.ex
  apps/explorer_web/lib/explorer_web/views/token_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/views/address_transaction_view_test.exs
  apps/explorer_web/test/explorer_web/views/currency_helpers_test.exs
  apps/explorer_web/test/explorer_web/views/token_view_test.exs
  mix.lock
Labels: in progress, ready for review, team: developer

#526 Upgrade node-sass to clear security vulnerability alerts
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
Labels: in progress, ready for review

#523 Add transaction hash to order_by on address_to_transactions query to …
  apps/explorer/lib/explorer/chain.ex
Labels: in progress, priority: high, ready for review, team: contributor

#505 Use nil Balance value to indicate unfetched
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/balance.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/priv/repo/migrations/20180717204948_create_balances.exs
  apps/explorer/test/explorer/chain/balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/market/history/cataloger_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
  apps/explorer_web/test/support/feature_case.ex
  apps/indexer/lib/indexer/balance_fetcher.ex
  apps/indexer/lib/indexer/balances.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/test/indexer/balance_fetcher_test.exs
  apps/indexer/test/indexer/balances_test.exs
  apps/indexer/test/indexer/supervisor_test.exs
Labels: bug, in progress, incompatible changes, ready for review

#507 Elixir 1.7.2 / Erlang 21.0.4
  .circleci/config.yml
  .credo.exs
  .tool-versions
  README.md
  apps/explorer_web/lib/explorer_web/templates/block/_tile.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/block_view.ex
  apps/explorer_web/lib/explorer_web/views/cldr/number.ex
  apps/explorer_web/lib/explorer_web/views/currency_helpers.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/wei_helpers.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/viewing_chain_test.exs
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/test/indexer/supervisor_test.exs
  mix.lock
Labels: enhancement, in progress

#531 Replicate Variant and Chain testing instructions to other READMEs that can use it
  README.md
  apps/ethereum_jsonrpc/README.md
  apps/explorer/README.md
  apps/indexer/README.md
Labels: enhancement, in progress

#528 Add block-number data-selector to template and fix feature test that …
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress, ready for review, real-time, team: contributor

#527 contract page and read/verify contract layout and style improvements
  apps/explorer_web/assets/css/_code.scss
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_button.scss
  apps/explorer_web/assets/css/components/_tile.scss
  apps/explorer_web/assets/css/forms.scss
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/loading_element.js
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_contract_verification/new.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_read_contract/_function_response.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_read_contract/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
Labels: design, in progress, ready for review

#542 Include a link to the token page on the address page, and show token type on the token page
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/_transaction.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/token/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#545 Add API Docs link to navbar
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/assets/js/lib/loading_element.js
Labels: api, ready for review

#546 Mobile live update fix
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/assets/css/forms.scss
  apps/explorer_web/assets/js/lib/loading_element.js
Labels: ready for review

#548 Use CTE for optimized address transactions query
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
Labels: priority: high, ready for review, team: contributor

#554 Fix dropdown hover bg color
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
Labels: ready for review

#544 Add event logs API support
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_module_card.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/lib/explorer/etherscan/logs.ex
  apps/explorer/test/explorer/etherscan/logs_test.exs
Labels: api, ready for review

#555 Update nodejs dependencies
  apps/block_scout_web/assets/package-lock.json
Labels: ready for review

#563 Fix real-time events on AWS
  apps/block_scout_web/config/prod.exs
Labels: ready for review

#537 Add function for validating address hashes
  apps/explorer/lib/explorer/chain/hash/address.ex
  apps/explorer/test/explorer/chain/hash/address_test.exs
Labels: in progress, ready for review

#557 Contributor sees Read Smart Contract in the Token Details page
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/smart_contract/read_only_functions.js
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/token_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_functions.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/token_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/overview_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/read_contract_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/token_view_test.exs
  apps/block_scout_web/test/test_helper.exs
  apps/explorer/lib/explorer/chain.ex
Labels: ready for review, team: developer

#556 Live reload chart, exchange rate, and market cap on homepage
  apps/block_scout_web/assets/__mocks__/css/app.scss.js
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/locale.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/exchange_rate_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/event_handler.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
  apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/block_scout_web/test/block_scout_web/views/chain_view_test.exs
  apps/block_scout_web/test/test_helper.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
Labels: ready for review

#559 525 design cleanup api doc
  apps/block_scout_web/assets/css/components/_nav_tabs.scss
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/chain_view_test.exs
Labels: enhancement, ready for review

#558 Add API txlistinternal action for account module
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, ready for review

#562 Add support for multiple return types in contracts
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/smart_contract_view.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/lib/explorer/token/balance_reader.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/indexer/lib/indexer/token_fetcher.ex
  mix.lock
Labels: ready for review

#575 Add API endpoint to get token data
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/token_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/token_controller_test.exs
Labels: api, ready for review

#578 Add stats#tokensupply API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
Labels: api, ready for review

#582 Index TokenBalances
  apps/explorer/lib/explorer/chain/address/token_balance.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/priv/repo/migrations/20180817021704_create_address_token_balances.exs
  apps/explorer/test/explorer/import_test.exs
  apps/indexer/lib/indexer/balances.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/test/indexer/supervisor_test.exs
Labels: ready for review, team: developer

#572 Use WebSocket subscription to newHeads for realtime indexer
  .circleci/config.yml
  .credo.exs
  README.md
  apps/ethereum_jsonrpc/README.md
  apps/ethereum_jsonrpc/config/test/mox.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/subscription.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transport.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/registration.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/geth/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/geth/mox.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/parity/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/parity/mox.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/geth.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/mox.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex
  apps/ethereum_jsonrpc/test/test_helper.exs
  apps/explorer/README.md
  apps/explorer/config/dev/geth.exs
  apps/explorer/config/dev/parity.exs
  apps/explorer/config/prod/geth.exs
  apps/explorer/config/prod/parity.exs
  apps/explorer/config/test/geth.exs
  apps/explorer/config/test/parity.exs
  apps/indexer/README.md
  apps/indexer/config/dev/geth.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/geth.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/catchup/supervisor.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/lib/indexer/block_fetcher/realtime/supervisor.ex
  apps/indexer/lib/indexer/block_fetcher/supervisor.ex
  apps/indexer/test/indexer/block_fetcher/catchup/supervisor_test.exs
  apps/indexer/test/indexer/block_fetcher/realtime_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/buffered_task_test.exs
  mix.lock
Labels: bug, enhancement, incompatible changes, ready for review

#590 Add support for named addresses
  .credo.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/name.ex
  apps/explorer/priv/repo/migrations/20180821142139_create_address_names.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/token_fetcher.ex
Labels: ready for review

#587 Updated address page so things do not wrap
  apps/block_scout_web/assets/css/_typography.scss
  apps/block_scout_web/assets/css/components/_icon-link.scss
  apps/block_scout_web/assets/css/components/_token-balance-dropdown.scss
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_tokens.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: bug, design, priority: high, ready for review

#595 Fix Coveralls
  .circleci/config.yml
  apps/block_scout_web/mix.exs
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/mix.exs
  apps/indexer/mix.exs
  mix.exs
  mix.lock
Labels: ready for review

#596 Add account#tokentx API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, ready for review

#619 Fix uniqueness/on_conflict for address_token_balances
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/priv/repo/migrations/20180817021704_create_address_token_balances.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/balances.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/balances_test.exs
Labels: bug, enhancement, team: architecture

#613 Set error log path
  config/dev.exs
  config/prod.exs
  config/test.exs
Labels: bug, team: architecture

#583 Fetch TokenBalances values in Realtime and Catchup Indexers
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/config/dev/parity.exs
  apps/explorer/config/prod/parity.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/lib/explorer/token/balance_reader.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/token/balance_reader_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/lib/indexer/token_balance_fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/test/indexer/block_fetcher/catchup/supervisor_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/token_balance_fetcher_test.exs
  apps/indexer/test/indexer/token_balances_test.exs
  apps/indexer/test/support/indexer/token_balance_fetcher_case.ex
Labels: ready for review, team: developer

#630 Use Path.absname in config so that log paths are stable during reload of Application env
  apps/block_scout_web/config/dev.exs
  apps/block_scout_web/config/prod.exs
  apps/block_scout_web/config/test.exs
  apps/ethereum_jsonrpc/config/dev.exs
  apps/ethereum_jsonrpc/config/prod.exs
  apps/ethereum_jsonrpc/config/test.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/test.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  config/dev.exs
  config/prod.exs
  config/test.exs
Labels: bug, team: architecture

#617 Adds links to token standards in API docs
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
Labels: api, ready for review

#616 Add account#getminedblocks API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, ready for review

#629 Add filterby flag to account#txlist
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: api, ready for review

#636 Better error message when receipt cannot be converted to elixir
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipt_test.exs
Labels: bug, ready for review, team: architecture

#637 529 resize token transfer cards
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/assets/css/components/_token_tile_view_more.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/token_transfers_toggle.js
  apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/_transaction.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/token/balance_reader_test.exs
Labels: design, enhancement, ready for review

#656 Fix spacing on account page pagination
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
Labels: ready for review

#633 Updated with a classic ethereum variable stylesheet
  apps/block_scout_web/assets/css/theme/_ethereum_classic_variables.scss
  apps/block_scout_web/assets/css/theme/_ethereum_variables.scss
  apps/block_scout_web/assets/static/images/classic_ethereum_logo.svg
  apps/block_scout_web/assets/static/images/classic_logo.svg
Labels: design, ready for review, team: contributor

#655 Fix height container for transactions on the homepage
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
Labels: ready for review

#644 Change Balance to CoinBalance and make its references consistent to TokenBalances
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/coin_balance.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/priv/repo/migrations/20180117221921_create_address.exs
  apps/explorer/priv/repo/migrations/20180717204948_create_address_coin_balances.exs
  apps/explorer/test/explorer/chain/address/coin_balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/import_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/address/coin_balances.ex
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block_fetcher.ex
  apps/indexer/lib/indexer/block_fetcher/catchup.ex
  apps/indexer/lib/indexer/block_fetcher/realtime.ex
  apps/indexer/lib/indexer/coin_balance_fetcher.ex
  apps/indexer/lib/indexer/internal_transaction_fetcher.ex
  apps/indexer/test/indexer/address/coin_balances_test.exs
  apps/indexer/test/indexer/address_extraction_test.exs
  apps/indexer/test/indexer/block_fetcher/catchup/supervisor_test.exs
  apps/indexer/test/indexer/block_fetcher/realtime_test.exs
  apps/indexer/test/indexer/block_fetcher_test.exs
  apps/indexer/test/indexer/coin_balance_fetcher_test.exs
  apps/indexer/test/indexer/internal_transaction_fetcher_test.exs
  apps/indexer/test/support/indexer/coin_balance_fetcher_case.ex
Labels: ready for review

#652 Add docs for block#getblockreward
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_model_table.html.eex
Labels: api, ready for review
