Repository blockscout/blockscout, pull requests merged in 2018-06, with the labels that each got.

#235 Remove pubsub from explorer_web application
  apps/explorer_web/config/prod.exs
Labels: in progress

#232 Contributer sees a QR code for address and transaction hashes
  apps/explorer/mix.exs
  apps/explorer_web/assets/css/_code.scss
  apps/explorer_web/assets/css/_content.scss
  apps/explorer_web/assets/css/_tooltip.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_qr-code.scss
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/views/address_view_test.exs
  apps/explorer_web/test/explorer_web/views/transaction_view_test.exs
  mix.lock
Labels: Vienna, contributor, design, in progress

#246 Mark to_address_hash as optional association on block->transactions page
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
Labels: in progress

#248 Index from latest to genesis
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/lib/explorer/indexer/sequence.ex
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/explorer/indexer/sequence_test.exs
  coveralls.json
Labels: bug, enhancement, in progress

#249 Improve paging query #200
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/paging_options.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/error_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/views/error_view_test.exs
Labels: in progress

#255 Index pending transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/lib/explorer/indexer.ex
  apps/explorer/lib/explorer/indexer/address_extraction.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/lib/explorer/indexer/internal_transaction_fetcher.ex
  apps/explorer/lib/explorer/indexer/pending_transaction_fetcher.ex
  apps/explorer/lib/explorer/indexer/supervisor.ex
  apps/explorer/test/explorer/indexer/address_extraction_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/explorer/indexer/internal_transaction_fetcher_test.exs
  apps/explorer/test/explorer/indexer/pending_transaction_fetcher_test.exs
  apps/explorer/test/support/data_case.ex
  apps/explorer/test/support/factory.ex
Labels: architecture, bug, enhancement, in progress

#256 Use table statistics estimate for total transaction
  apps/explorer/lib/explorer/chain.ex
  apps/explorer_web/lib/explorer_web/controllers/pending_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
Labels: in progress

#253 Ui bug fixes
  apps/explorer_web/assets/css/_code.scss
  apps/explorer_web/assets/css/_typography.scss
  apps/explorer_web/assets/css/components/_header.scss
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_topnav.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/views/address_view_test.exs
Labels: in progress

#182 Developer verifies a Smart Contract
  .circleci/config.yml
  apps/explorer/.sobelow-conf
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/smart_contract/publisher.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/solidity/compiler_version.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/repo/migrations/20180518221256_create_smart_contract_verified.exs
  apps/explorer/priv/solc.bash
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/publisher_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/compiler_version_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/explorer/test/support/fixture/smart_contract/solc_bin.json
  apps/explorer_web/assets/css/_content.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_all.scss
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/controllers/address_contract_verification_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_contract/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_contract_verification/new.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/address_contract_verification_view.ex
  apps/explorer_web/lib/explorer_web/views/address_contract_view.ex
  apps/explorer_web/lib/explorer_web/views/address_internal_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/lib/explorer_web/views/error_helpers.ex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_contract_controller_test.exs
  apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
  apps/explorer_web/test/explorer_web/views/error_helpers_test.exs
  apps/explorer_web/test/support/fixture/smart_contract/solc_bin.json
  mix.lock
Labels: in progress

#269 Increase characters in address and remove address icon
  apps/explorer_web/assets/css/components/_address_link.scss
  apps/explorer_web/lib/explorer_web/templates/address/_link.html.eex
Labels: in progress

#271 Add note at readme noticing the Solidity dependency
  README.md
Labels: developer, in progress

#277 Upgrade gettext dependency
  apps/explorer_web/mix.exs
  mix.lock
Labels: in progress

#275 Display contract create address #241
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/features/pages/address_page.ex
  apps/explorer_web/test/explorer_web/features/pages/block_page.ex
  apps/explorer_web/test/explorer_web/features/pages/home_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_list_page.ex
  apps/explorer_web/test/explorer_web/features/pages/transaction_page.ex
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: in progress

#281 Add Google Fonts to Content Security Policy
  apps/explorer_web/lib/explorer_web/router.ex
Labels: in progress

#285 on_conflict for insert_internal_transactions
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/test/explorer/buffered_task_test.exs
  apps/explorer/test/explorer/repo_test.exs
  coveralls.json
Labels: architecture, bug, enhancement, in progress

#282 Fix Contract address not showing code tab
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: bug, in progress

#298 Update CircleCI to Elixir 1.6.5
  .circleci/config.yml
  .tool-versions
Labels: bug, in progress

#176 Add user accounts
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/accounts/accounts.ex
  apps/explorer/lib/explorer/accounts/user.ex
  apps/explorer/lib/explorer/accounts/user/registration.ex
  apps/explorer/lib/explorer/accounts/user_contact.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20180508183700_create_users.exs
  apps/explorer/priv/repo/migrations/20180508191045_create_user_contacts.exs
  apps/explorer/test/explorer/accounts/accounts_test.exs
  apps/explorer/test/explorer/accounts/user_contact_test.exs
  apps/explorer/test/explorer/accounts/user_test.exs
  apps/explorer/test/support/data_case.ex
  mix.lock
Labels: Vienna, architecture, in progress

#252 Add API for getting total/circulating supply values
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/supply.ex
  apps/explorer/lib/explorer/chain/supply/proof_of_authority.ex
  apps/explorer/test/explorer/chain/supply/proof_of_authority_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web/controllers/api/v1/supply_controller.ex
  apps/explorer_web/lib/explorer_web/router.ex
  apps/explorer_web/lib/explorer_web/views/api/v1/supply_view.ex
  apps/explorer_web/test/explorer_web/controllers/api/v1/supply_controller_test.exs
Labels: architecture, in progress

#293 Create ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: in progress

#291 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: in progress

#299 CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: enhancement, in progress, incompatible changes

#283 fetched_balance_block_number instead of fetched_balance_at
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex
  apps/explorer/lib/explorer/indexer/address_extraction.ex
  apps/explorer/lib/explorer/indexer/block_fetcher.ex
  apps/explorer/lib/explorer/indexer/internal_transaction_fetcher.ex
  apps/explorer/lib/explorer/indexer/pending_transaction_fetcher.ex
  apps/explorer/priv/repo/migrations/20180117221921_create_address.exs
  apps/explorer/test/explorer/chain/address_test.exs
  apps/explorer/test/explorer/chain/block_test.exs
  apps/explorer/test/explorer/chain/log_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/indexer/address_balance_fetcher_test.exs
  apps/explorer/test/explorer/indexer/address_extraction_test.exs
  apps/explorer/test/explorer/indexer/block_fetcher_test.exs
  apps/explorer/test/explorer/indexer/internal_transaction_fetcher_test.exs
  apps/explorer/test/explorer/repo_test.exs
  apps/explorer/test/explorer/smart_contract/publisher_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/address_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_addresses_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_transactions_test.exs
Labels: bug, enhancement, in progress, incompatible changes

#301 Rotate cache keys to cache bcrypt
  .circleci/config.yml
Labels: bug, in progress

#302 Cache deps with _build
  .circleci/config.yml
Labels: bug, in progress

#306 Last seen paging on address page #230
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer_web/lib/explorer_web.ex
  apps/explorer_web/lib/explorer_web/chain.ex
  apps/explorer_web/lib/explorer_web/controllers/address_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/address_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/block_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/pending_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_internal_transaction_controller.ex
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/mix.exs
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/block_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/pending_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
  apps/explorer_web/test/explorer_web/features/viewing_blocks_test.exs
  mix.lock
Labels: in progress

#307 Show correct internal transaction type and contract link
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/views/internal_transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/views/internal_transaction_view_test.exs
Labels: in progress

#308 Dedupe and log duplicate transaction hashes before fetching internal transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/explorer/lib/explorer/buffered_task.ex
  apps/explorer/lib/explorer/indexer/internal_transaction_fetcher.ex
  apps/explorer/test/explorer/indexer/internal_transaction_fetcher_test.exs
  coveralls.json
Labels: bug, enhancement, in progress

#315 Pass through removed flag for logs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
Labels: bug, in progress

#310 `AddressBalanceFetcher` uses max `block_quantity` for `hash_data` in batches
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs
  apps/explorer/lib/explorer/indexer/address_balance_fetcher.ex
  apps/explorer/test/explorer/indexer/address_balance_fetcher_test.exs
  coveralls.json
Labels: architecture, bug, enhancement, in progress

#316 Rechunk batch JSONRPC request when 413 is returned
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/etheream_jsonrpc_test.exs
  apps/explorer/test/explorer/chain/statistics/server_test.exs
  coveralls.json
Labels: architecture, bug, in progress

#318 Add same markup as the labels above
  apps/explorer_web/lib/explorer_web/templates/address/overview.html.eex
Labels: in progress

#322 Rename Gas Limit to Gas Used on Internal Transactions
  apps/explorer_web/lib/explorer_web/templates/transaction_internal_transaction/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#320 Bug fix transactions not populating #297
  apps/explorer/lib/explorer/chain.ex
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction_log/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer_web/test/explorer_web/controllers/address_internal_transaction_controller_test.exs
  apps/explorer_web/test/explorer_web/controllers/address_transaction_controller_test.exs
Labels: in progress

#325 Ensure transaction logs are displayed if to_address is nil on transac…
  apps/explorer_web/lib/explorer_web/controllers/transaction_log_controller.ex
  apps/explorer_web/test/explorer_web/controllers/transaction_log_controller_test.exs
Labels: in progress

#326 Redesign Implementation Header & Footer
  apps/explorer_web/assets/css/_content.scss
  apps/explorer_web/assets/css/_layout.scss
  apps/explorer_web/assets/css/_tooltip.scss
  apps/explorer_web/assets/css/_utilities.scss
  apps/explorer_web/assets/css/app.scss
  apps/explorer_web/assets/css/components/_chain.scss
  apps/explorer_web/assets/css/components/_footer.scss
  apps/explorer_web/assets/css/components/_header.scss
  apps/explorer_web/assets/css/components/_navbar.scss
  apps/explorer_web/assets/css/components/_panels.scss
  apps/explorer_web/assets/css/components/_sidebar.scss
  apps/explorer_web/assets/css/explorer/_all.scss
  apps/explorer_web/assets/css/explorer/_breakpoints.scss
  apps/explorer_web/assets/css/explorer/_paper.scss
  apps/explorer_web/assets/css/explorer/_size.scss
  apps/explorer_web/assets/css/theme/_fonts.scss
  apps/explorer_web/assets/css/theme/_poa_variables.scss
  apps/explorer_web/assets/css/theme/_theme_ribbon.scss
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_footer.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_ribbon.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_sidebar.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/_topnav.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#327 Update ages in real-time
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer_web/assets/js/app.js
  apps/explorer_web/assets/js/lib/from_now.js
  apps/explorer_web/lib/explorer_web/templates/address_internal_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/address_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/block_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_blocks.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/_transactions.html.eex
  apps/explorer_web/lib/explorer_web/templates/chain/show.html.eex
  apps/explorer_web/lib/explorer_web/templates/layout/app.html.eex
  apps/explorer_web/lib/explorer_web/templates/pending_transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/index.html.eex
  apps/explorer_web/lib/explorer_web/templates/transaction/overview.html.eex
  apps/explorer_web/lib/explorer_web/views/block_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/block_view.ex
  apps/explorer_web/lib/explorer_web/views/pending_transaction_view.ex
  apps/explorer_web/lib/explorer_web/views/transaction_view.ex
  apps/explorer_web/priv/gettext/default.pot
  apps/explorer_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#288 Give support for all solidity's versions in the contract verification
  .circleci/config.yml
  .gitignore
  README.md
  apps/explorer/lib/explorer/smart_contract/publisher.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/solidity/compiler_version.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/package.json
  apps/explorer/priv/compile_solc.js
  apps/explorer/priv/solc.bash
  apps/explorer/test/explorer/smart_contract/publisher_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/compiler_version_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/explorer/test/support/factory.ex
  apps/explorer/test/support/fixture/smart_contract/solc_bin.json
  apps/explorer_web/lib/explorer_web/templates/address_contract_verification/new.html.eex
  apps/explorer_web/test/explorer_web/features/address_contract_verification_test.exs
  apps/explorer_web/test/support/fixture/smart_contract/solc_bin.json
Labels: in progress

#336 Fix homepage timeout #330
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer/priv/repo/migrations/20180626143840_add_inserted_at_index_to_blocks.exs
  apps/explorer/test/explorer/chain/statistics_test.exs
Labels: in progress

#339 More home page query optimizations
  apps/explorer/lib/explorer/chain/statistics.ex
  apps/explorer/test/explorer/chain/statistics_test.exs
Labels: in progress

#342 Include and update explorer/ and explorer_web/assets/ package-lock.json
  apps/explorer/package-lock.json
  apps/explorer_web/assets/package-lock.json
Labels: in progress

#344 Run audit on node dependencies
  apps/explorer_web/assets/package-lock.json
  apps/explorer_web/assets/package.json
Labels: in progress
