Repository blockscout/blockscout, pull requests merged in 2018-10, with the labels that each got.

#803 Remove duplicated template code from Address page
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_internal_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_token_transfer_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_token_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_contract_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Labels: in progress, ready for review

#835 token_balance_test.ex -> token_balance_test.exs
  apps/explorer/test/explorer/chain/address/token_balance_test.exs
Labels: bug, in progress, ready for review

#840 Display miner address names in block views
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/transfer_view_test.exs
Labels: in progress, ready for review

#839 Display shortened addresses in named address links
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Labels: in progress, ready for review

#841 Add prometheus metric exporting
  .credo.exs
  README.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/application.ex
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/prometheus/exporter.ex
  apps/block_scout_web/lib/block_scout_web/prometheus/instrumenter.ex
  apps/block_scout_web/mix.exs
  apps/explorer/config/config.exs
  apps/explorer/config/dev.secret.exs.example
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/repo/prometheus_logger.ex
  apps/explorer/mix.exs
  mix.lock
  prometheus.yml
Labels: enhancement, in progress

#844 Ensure order is preserved for account multibalance
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: bug, in progress

#807 Missed token transfer cataloger
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/lib/indexer/token_transfer/parser.ex
  apps/indexer/lib/indexer/token_transfer/uncataloged/supervisor.ex
  apps/indexer/lib/indexer/token_transfer/uncataloged/worker.ex
  apps/indexer/lib/indexer/token_transfers.ex
  apps/indexer/test/indexer/sequence_test.exs
  apps/indexer/test/indexer/token_transfer/parser_test.exs
  apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
Labels: in progress, ready for review

#848 Fix Typos
  .circleci/config.yml
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/css/theme/_neutral_variables.scss
  apps/block_scout_web/assets/js/lib/try_api.js
  apps/block_scout_web/lib/block_scout_web/application.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_transaction_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/tab_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs
  apps/block_scout_web/test/support/channel_case.ex
  apps/block_scout_web/test/support/conn_case.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/decode_error.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace/action.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace/result.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/subscription.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transport.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/registration.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/data.ex
  apps/explorer/lib/explorer/chain/hash/address.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/lib/explorer/market/history/cataloger.ex
  apps/explorer/test/explorer/chain/block/range_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/buffered_task.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
Labels: bug, in progress

#833 Support reorganizations
  apps/explorer/.sobelow-conf
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/test/explorer/chain/import_test.exs
Labels: bug, enhancement, in progress, ready for review, team: architecture

#849 Trim address and token names of whitespace
  apps/explorer/lib/explorer/chain/address/name.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#816 789 pending transactions on address page live update
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_loading-spinner.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/transaction_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_link.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/render_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/render_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review, real-time, team: contributor

#832 Deployment fixes for the network path
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/config/prod.exs
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/prod/parity.exs
  apps/indexer/config/prod/parity.exs
  bin/deployment/health_check
Labels: in progress, wip

#845 Only count consensus blocks as not missing
  apps/explorer/lib/explorer/chain.ex
Labels: bug, enhancement, in progress, team: architecture

#828 account#txlistinternal by address API endpoint
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/etherscan_test.exs
Labels: in progress

#855 Fix where_forked selecting all transactions when there are no blocks being imported
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/test/explorer/chain/import_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Labels: bug, enhancement, in progress, team: architecture

#847 775 in order blocks realtime
  apps/block_scout_web/assets/__tests__/pages/block.js
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/__tests__/pages/transaction.js
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/assets/css/components/_loading-spinner.scss
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
Labels: in progress, ready for review, real-time, team: contributor

#852 Highlight transaction status
  apps/block_scout_web/assets/css/_typography.scss
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Labels: enhancement, in progress, ready for review

#857 Fix channel event name for chain transactions.
  apps/block_scout_web/assets/js/pages/chain.js
Labels: bug, in progress, ready for review, real-time, team: contributor

#864 Allow insecure WebSocket connections
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/indexer/config/dev/geth.exs
Labels: in progress, wip

#859 Break up Explorer.Chain.Import
  .credo.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/import/address/coin_balances.ex
  apps/explorer/lib/explorer/chain/import/address/token_balances.ex
  apps/explorer/lib/explorer/chain/import/addresses.ex
  apps/explorer/lib/explorer/chain/import/block/second_degree_relations.ex
  apps/explorer/lib/explorer/chain/import/blocks.ex
  apps/explorer/lib/explorer/chain/import/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/logs.ex
  apps/explorer/lib/explorer/chain/import/runner.ex
  apps/explorer/lib/explorer/chain/import/token_transfers.ex
  apps/explorer/lib/explorer/chain/import/tokens.ex
  apps/explorer/lib/explorer/chain/import/transaction/forks.ex
  apps/explorer/lib/explorer/chain/import/transactions.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/import_test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  mix.exs
  mix.lock
Labels: enhancement, in progress, incompatible changes, ready for review, team: architecture

#858 Add metatags for individual pages on BlockScout
  apps/block_scout_web/lib/block_scout_web/templates/address/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_read_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_default_title.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
  apps/block_scout_web/lib/block_scout_web/views/chain_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/overview_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: in progress

#874 nil error when forking transactions
  apps/explorer/lib/explorer/chain/import/blocks.ex
  apps/explorer/test/explorer/chain/import_test.exs
Labels: bug, enhancement, in progress, ready for review, team: architecture

#867 Consolidate token transfer count
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/counters/token_transfer_counter.ex
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/token_transfer_counter_test.exs
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/pending_transaction/fetcher.ex
Labels: in progress, ready for review

#882 Set endpoint to load favicon-related assets
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
Labels: in progress, ready for review

#885 Remove token holders count from Token's page
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
Labels: in progress, ready for review, team: developer

#886 DAI Chain Theme
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/assets/css/theme/_dai_variables.scss
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/static/images/cube.svg
  apps/block_scout_web/assets/static/images/dai_logo.svg
  apps/block_scout_web/assets/static/images/icons/transactions.svg
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/icons/_transaction_icon.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#870 Uncle Support in the UI
  apps/block_scout_web/assets/css/components/_animations.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/block_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/views/block_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
Labels: in progress, ready for review

#891 Fix z-index issue with the network selection menu
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
Labels: bug, in progress, ready for review

#887 Log InternalTransaction.Fetcher errors as error
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
Labels: in progress

#889 Don't count every sibling unnecessarily.
  apps/explorer/lib/explorer/chain.ex
Labels: in progress

#912 Add a Gitter chat badge to README.md
  README.md
Labels: in progress

#914 Blocks validated tab for miner crashing
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
Labels: in progress, ready for review

#871 Fill-in skipped blocks on page render for blocks list
  apps/block_scout_web/assets/__tests__/pages/block.js
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/utils.js
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/block_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
Labels: in progress, ready for review, team: contributor

#877 Consolidate validation count
  apps/block_scout_web/assets/js/pages/address.js
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/counters/block_validation_counter.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/block_validation_counter_test.exs
Labels: in progress, ready for review

#916 899 loading bar when indexing
  apps/block_scout_web/assets/css/components/_loading-spinner.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/currency.js
  apps/block_scout_web/assets/js/lib/indexing.js
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/block_channel_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/app_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review, real-time, team: contributor

#915 UI Improvements
  apps/block_scout_web/assets/css/_typography.scss
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/css/components/_footer.scss
  apps/block_scout_web/assets/css/components/_icon-link.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/css/theme/_dai_variables.scss
  apps/block_scout_web/assets/css/theme/_kovan_variables.scss
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
  apps/block_scout_web/assets/css/theme/_variables.scss
  apps/block_scout_web/assets/static/images/dai_logo.svg
  apps/block_scout_web/assets/static/images/rinkeby_logo.svg
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_action_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: design, in progress, ready for review

#917 Optimize entry memory usage for work queues
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/lib/explorer/exchange_rates/token.ex
  apps/explorer/test/explorer/chain/hash/full_test.exs
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/test/indexer/coin_balance/fetcher_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
Labels: enhancement, in progress, ready for review, team: architecture

#923 Log and retry import errors in uncle fetcher
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
Labels: bug, in progress

#931 Fixes for ganache integration
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/explorer/config/dev/ganache.exs
  apps/indexer/config/dev/ganache.exs
Labels: ready for review

#929 Refactor the transactions count by address to use the accounts nonce
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review, team: developer

#904 Consolidate token holders count
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/token_balance.ex
  apps/explorer/lib/explorer/counters/token_holders_counter.ex
  apps/explorer/test/explorer/chain/address/token_balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/token_holders_counter_test.exs
Labels: in progress, ready for review

#927 Add bare admin panel
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/admin_router.ex
  apps/block_scout_web/lib/block_scout_web/controllers/admin/dashboard_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/admin/session_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/admin/setup_controller.ex
  apps/block_scout_web/lib/block_scout_web/plug/admin/check_owner_registered.ex
  apps/block_scout_web/lib/block_scout_web/plug/admin/require_admin_role.ex
  apps/block_scout_web/lib/block_scout_web/plug/fetch_user_from_session.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/admin/dashboard/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/admin/session/login_form.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/admin/setup/admin_registration.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/admin/setup/verify.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/form/text_field.html.eex
  apps/block_scout_web/lib/block_scout_web/views/admin/dashboard_view.ex
  apps/block_scout_web/lib/block_scout_web/views/admin/session_view.ex
  apps/block_scout_web/lib/block_scout_web/views/admin/setup_view.ex
  apps/block_scout_web/lib/block_scout_web/views/error_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/form_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/admin/dashboard_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/admin/session_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/admin/setup_controller_test.exs
  apps/block_scout_web/test/block_scout_web/plug/admin/check_owner_registered_test.exs
  apps/block_scout_web/test/block_scout_web/plug/admin/require_admin_role_test.exs
  apps/block_scout_web/test/block_scout_web/plug/fetch_user_from_session_test.exs
  apps/block_scout_web/test/support/conn_case.ex
  apps/explorer/.gitignore
  apps/explorer/lib/explorer/accounts/accounts.ex
  apps/explorer/lib/explorer/accounts/user/authenticate.ex
  apps/explorer/lib/explorer/accounts/user/registration.ex
  apps/explorer/lib/explorer/accounts/user_contact.ex
  apps/explorer/lib/explorer/admin.ex
  apps/explorer/lib/explorer/admin/administrator.ex
  apps/explorer/lib/explorer/admin/recovery.ex
  apps/explorer/lib/explorer/admin/role.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/priv/repo/migrations/20181008195723_create_administrators.exs
  apps/explorer/priv/repo/migrations/20181015173318_add_case_insensitive_extension.exs
  apps/explorer/priv/repo/migrations/20181015173319_modify_users_username.exs
  apps/explorer/priv/repo/migrations/20181016163236_modify_user_contacts_email.exs
  apps/explorer/test/explorer/accounts/accounts_test.exs
  apps/explorer/test/explorer/accounts/user_contact_test.exs
  apps/explorer/test/explorer/admin/administrator/role_test.exs
  apps/explorer/test/explorer/admin/recovery_test.exs
  apps/explorer/test/explorer/admin_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#940 Considers mint transfers using logs to index the address
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/mint_transfer.ex
  apps/indexer/test/indexer/mint_transfer_test.exs
Labels: in progress, ready for review

#936 Update block reward contract beneficiary balances
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/test/indexer/address_extraction_test.exs
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Labels: chain: POA :chains:, client: parity, in progress, ready for review

#893 Address tile should display validations
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/errors.po
Labels: in progress

#949 Make address pending transactions collapsable
  apps/block_scout_web/assets/__tests__/pages/address.js
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/pending_transactions_toggle.js
  apps/block_scout_web/assets/js/lib/token_balance_dropdown.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/block.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/js/utils.js
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: in progress, ready for review

#953 Address 404 page
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#951 dai chain supply and market cap
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/supply.ex
  apps/explorer/lib/explorer/chain/supply/proof_of_authority.ex
  apps/explorer/lib/explorer/chain/supply/transaction_and_log.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/lib/explorer/exchange_rates/source/transaction_and_log.ex
  apps/explorer/test/explorer/chain/supply/transaction_and_log_test.exs
  apps/explorer/test/explorer/chain/wei_test.exs
  apps/explorer/test/explorer/exchange_rates/source/transaction_and_log_test.exs
  apps/explorer/test/support/fakes/one_coin_source.ex
Labels: in progress, ready for review

#946 Add transaction dropdown menu to navbar
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_list_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
Labels: in progress, wip

#955 Add Internal Transaction type to the tile
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/views/internal_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/internal_transaction_view_test.exs
Labels: in progress, ready for review

#958 Adds log rotation
  apps/block_scout_web/config/prod.exs
  apps/ethereum_jsonrpc/config/prod.exs
  apps/explorer/config/prod.exs
  apps/indexer/config/prod.exs
  config/prod.exs
Labels: enhancement, in progress, ready for review

#965 Remove null bytes from token name and symbol
  apps/indexer/lib/indexer/token/fetcher.ex
Labels: in progress

#928 Improve Internal Transactions listing performance
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/blocks.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/mix/tasks/migrate.transaction.info.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20181011193212_add_fields_to_internal_transactions.exs
  apps/explorer/priv/repo/migrations/20181017141409_add_index_to_internal_transaction_table.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/internal_transaction_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer/test/explorer/repo_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress, ready for review

#945 Fix ping/pong from ganache ws implementation
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
Labels: client: ganache, in progress, ready for review

#970 Provide default 2nd arg for executing contract functions on Geth
  apps/block_scout_web/test/block_scout_web/controllers/smart_contract_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: in progress, ready for review

#975 Lookup internal_txs by {hash, index} in BlockScoutWeb.Notifier handle_event()
  apps/block_scout_web/lib/block_scout_web/notifier.ex
Labels: in progress

#971 Monitor and shrink memory usage of Sequence and BufferedTasks when soft-limit exceeded
  .credo.exs
  README.md
  apps/indexer/README.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/bound_queue.ex
  apps/indexer/lib/indexer/buffered_task.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/logger.ex
  apps/indexer/lib/indexer/memory/monitor.ex
  apps/indexer/lib/indexer/memory/shrinkable.ex
  apps/indexer/lib/indexer/sequence.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/test/indexer/buffered_task_test.exs
  apps/indexer/test/indexer/coin_balance/fetcher_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
  apps/indexer/test/indexer/sequence_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
  apps/indexer/test/support/indexer/block/uncle/supervisor/case.ex
  apps/indexer/test/support/indexer/coin_balance/supervisor/case.ex
  apps/indexer/test/support/indexer/internal_transaction/supervisor/case.ex
  apps/indexer/test/support/indexer/pending_transaction/supervisor/case.ex
  apps/indexer/test/support/indexer/token/supervisor/case.ex
  apps/indexer/test/support/indexer/token_balance/supervisor/case.ex
  apps/indexer/test/test_helper.exs
Labels: bug :bug:, enhancement, in progress, incompatible changes, ready for review

#961 Add backoff for Ethereum JSON RPC requests
  apps/ethereum_jsonrpc/config/config.exs
  apps/ethereum_jsonrpc/config/test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/application.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/rolling_window.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/request_coordinator_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/rolling_window_test.exs
Labels: in progress, ready for review

#977 Fix InternalTransaction listing page by removing transaction fields.
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: bug :bug:, in progress, ready for review

#960 Improve token balances fetcher
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
  apps/indexer/test/indexer/token_balances_test.exs
Labels: in progress, ready for review, team: developer

#985 Composite primary keys and eliminating use of on_conflict: replace_all
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/address/coin_balances.ex
  apps/explorer/lib/explorer/chain/import/address/token_balances.ex
  apps/explorer/lib/explorer/chain/import/addresses.ex
  apps/explorer/lib/explorer/chain/import/block/second_degree_relations.ex
  apps/explorer/lib/explorer/chain/import/blocks.ex
  apps/explorer/lib/explorer/chain/import/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/logs.ex
  apps/explorer/lib/explorer/chain/import/token_transfers.ex
  apps/explorer/lib/explorer/chain/import/tokens.ex
  apps/explorer/lib/explorer/chain/import/transaction/forks.ex
  apps/explorer/lib/explorer/chain/import/transactions.ex
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/priv/repo/migrations/20181024141113_internal_transactions_composite_primary_key.exs
  apps/explorer/priv/repo/migrations/20181024164623_logs_composite_primary_key.exs
  apps/explorer/priv/repo/migrations/20181024172010_token_transfers_composite_primary_key.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/token_transfer_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
Labels: bug :bug:, in progress

#973 hide token holder count when not consolidating
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/token/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/priv/gettext/errors.pot
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/counters/token_holders_counter.ex
Labels: in progress, ready for review

#987 Do not store token_hash as address_hash in token balances
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
Labels: in progress, ready for review

#990 Add Absinthe for GraphQL API
  apps/block_scout_web/lib/block_scout_web/resolvers/block.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/test/block_scout_web/schema/query/block_test.exs
  mix.lock
Labels: in progress

#983 Prevent stampedes via sleeping for throttle_timeout even when request is not made
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
Labels: in progress, ready for review

#997 Fix error when indexing Wanchain
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
Labels: in progress, ready for review

#1005 Color Scheme and Logo for New Networks
  apps/block_scout_web/assets/css/theme/_callisto_variables.scss
  apps/block_scout_web/assets/css/theme/_ellaism_variables.scss
  apps/block_scout_web/assets/css/theme/_expanse_variables.scss
  apps/block_scout_web/assets/css/theme/_gochain_variables.scss
  apps/block_scout_web/assets/css/theme/_musicoin_variables.scss
  apps/block_scout_web/assets/css/theme/_pirl_variables.scss
  apps/block_scout_web/assets/css/theme/_social_variables.scss
  apps/block_scout_web/assets/css/theme/_tobalaba_variables.scss
  apps/block_scout_web/assets/css/theme/_tomochain_variables.scss
  apps/block_scout_web/assets/css/theme/_wanchain_variables.scss
  apps/block_scout_web/assets/static/images/callisto_logo.svg
  apps/block_scout_web/assets/static/images/ellaism_logo.svg
  apps/block_scout_web/assets/static/images/expanse_logo.png
  apps/block_scout_web/assets/static/images/gochain_logo.png
  apps/block_scout_web/assets/static/images/musicoin_logo.svg
  apps/block_scout_web/assets/static/images/pirl_logo.svg
  apps/block_scout_web/assets/static/images/social_logo.svg
  apps/block_scout_web/assets/static/images/tobalaba_logo.svg
  apps/block_scout_web/assets/static/images/tomochain_logo.svg
  apps/block_scout_web/assets/static/images/wanchain_logo.png
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: design, in progress, team: contributor

#998 add contract address to transaction fetching
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/indexer/lib/indexer/address_extraction.ex
Labels: in progress, ready for review

#1012 Fixed mobile search bar and network ui bug
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: in progress

#999 Add custom GraphQL scalar types
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/scalars.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
Labels: in progress, ready for review

#1001 Fix for undefined function error in TokenTransfer Uncatalogued Worker Module
  apps/indexer/lib/indexer/token_transfer/uncataloged/worker.ex
  apps/indexer/test/indexer/token_transfer/uncataloged/worker_test.exs
Labels: bug :bug:, in progress, ready for review

#1015 Highlight code tab when a contract is verified
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
Labels: enhancement, in progress, ready for review

#993 Dockerize blockscout (for local usage)
  .dockerignore
  docker/Dockerfile
  docker/Makefile
  docker/README.md
Labels: in progress

#1014 Gsf increase limit of token decimals field
  apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/holder_view.ex
  apps/block_scout_web/test/block_scout_web/views/currency_helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/helpers_test.exs
  apps/block_scout_web/test/block_scout_web/views/tokens/holder_view_test.exs
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/priv/repo/migrations/20181029174420_update_tokens_table_decimals_from_bigint_to_numeric.exs
  apps/explorer/test/explorer/chain/address/token_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress, ready for review

#1021 Color code internal transaction type labels
  apps/block_scout_web/assets/css/_typography.scss
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
Labels: design, in progress, ready for review

#1020 Read contract query styling
  apps/block_scout_web/lib/block_scout_web/templates/smart_contract/_function_response.html.eex
Labels: bug :bug:, design, in progress, ready for review

#1019 GraphQL token transfers subscription
  apps/block_scout_web/lib/block_scout_web/application.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/event_handler.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/schema.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/test/block_scout_web/schema/subscription/token_transfers_test.exs
  apps/block_scout_web/test/support/subscription_case.ex
Labels: in progress, ready for review
