Repository blockscout/blockscout, pull requests merged in 2019-03, with the labels that each got.

#1505 use https instead of ssh for absinthe libs
  apps/block_scout_web/mix.exs
  apps/explorer/test/explorer/chain_test.exs
  mix.lock
Labels: in progress

#1510 fix test that fails every 1st day of the month
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1496 feat: remove dropped/replaced transactions in pending transactions list
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/explorer/lib/explorer/chain.ex
Labels: in progress

#1518 select only distinct failed transactions
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
Labels: in progress

#1517 fix bootstrap vulnerability
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/explorer/package-lock.json
Labels: in progress

#1511 set correct log level for production
  apps/indexer/config/prod.exs
Labels: in progress

#1509 add index to blocks' consensus
  apps/explorer/priv/repo/migrations/20190301120328_add_index_to_consensus.exs
Labels: in progress

#1508 remove duplicated indexes
  apps/explorer/priv/repo/migrations/20190301095620_remove_duplicated_indexes.exs
Labels: in progress

#1516 fix coin balance params reducer for pending transaction
  apps/indexer/lib/indexer/address/coin_balances.ex
  apps/indexer/test/indexer/address/coin_balances_test.exs
Labels: in progress

#1466 feat: decoding candidates for unverified contracts
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain/contract_method.ex
  apps/explorer/lib/explorer/chain/method_identifier.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20181221145054_add_contract_methods.exs
  apps/explorer/test/explorer/chain/transaction_test.exs
  apps/explorer/test/explorer/smart_contract/publisher_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress

#1521 Revert "fix bootstrap vulnerability"
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/explorer/package-lock.json
Labels: in progress

#1520 Fix flaky tests
  .circleci/config.yml
Labels: in progress

#1492 disable usd value for an empty exchange rate
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/exchange_rates/token.ex
Labels: in progress

#1527 add index to value_fetched_at
  apps/explorer/priv/repo/migrations/20190305095926_add_index_to_value_fetched_at.exs
Labels: in progress

#1537 fix test that depended on date
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1519 Create contract methods
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/pages/admin/tasks.js
  apps/block_scout_web/lib/block_scout_web/admin_router.ex
  apps/block_scout_web/lib/block_scout_web/controllers/admin/tasks_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/admin/dashboard/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain/contract_method.ex
Labels: in progress

#1532 upgrade elixir to 1.8.1
  .circleci/config.yml
  .dialyzer-ignore
  .tool-versions
  README.md
  apps/block_scout_web/mix.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/mix.exs
  apps/explorer/test/explorer/smart_contract/publisher_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/mix.exs
  mix.exs
  mix.lock
  rel/config.exs
Labels: in progress

#1545 Fix scheduling of latest block polling in Realtime Fetcher
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: ready for review

#1547 verify smart contracts with evm versions
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/solc_bin.json
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Labels: in progress

#1539 (Feature) Add the link to release in the footer
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: ready for review

#1551 (Feature) Exact date and time for Transaction details page
  apps/block_scout_web/assets/js/lib/from_now.js
Labels: ready for review

#1554 encode integer parameters when calling smart contract functions
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: in progress

#1534 fix: render a nicer error when creator cannot be determined
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1540 fetch ERC721 token balances if sender is '0x0..0'
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
Labels: in progress

#1560 Allow executing smart contract functions in arbitrarily sized batches
  .dialyzer-ignore
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/contract_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/encoder_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/lib/explorer/token/balance_reader.ex
  apps/explorer/test/explorer/chain/supply/token_bridge_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
  apps/explorer/test/explorer/token/balance_reader_test.exs
  apps/explorer/test/explorer/token/metadata_retriever_test.exs
  apps/explorer/test/explorer/validator/metadata_retriever_test.exs
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
  apps/indexer/test/indexer/token/fetcher_test.exs
  apps/indexer/test/indexer/token/metadata_updater_test.exs
  apps/indexer/test/indexer/token_balance/fetcher_test.exs
  apps/indexer/test/indexer/token_balances_test.exs
Labels: ready for review

#1562 add incoming transactions count to contract view
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/priv/repo/migrations/20190314084907_add_index_to_to_address_hash.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1558 allow searching by token symbol
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/chain_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/priv/repo/migrations/20190313085740_add_index_symobl_in_tokens.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1543 Use trace_replayBlockTransactions API for faster tracing
  .dialyzer-ignore
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/ganache.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/geth_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/priv/repo/migrations/20190228220746_add_internal_transactions_indexed_at_to_blocks.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
  apps/indexer/test/indexer/temporary/failed_created_addresses_test.exs
Labels: in progress, ready for review

#1579 Add SpringChain to the list of Additional Chains Utilizing BlockScout
  README.md
Labels: in progress

#1572 add option to disable block rewards in indexer config
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
Labels: in progress

#1586 (Fix) Exact timestamp display
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
Labels: ready for review

#1578 Refine contributing procedure
  CHANGELOG.md
  CONTRIBUTING.md
Labels: in progress

#1567 feat: allow setting different configuration just for realtime fetcher
  apps/indexer/config/dev/parity.exs
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
Labels: in progress

#1588 fix usd value on address page
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
Labels: in progress

#1559 change v column type
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190313103912_change_transactions_v_column_type.exs
Labels: in progress

#1589 feat: rpc endpoint to list addresses
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
Labels: in progress

#1581 consider `creates` param when fetching transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
Labels: in progress

#1595 Reduce block_rewards in the catchup fetcher
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
Labels: in progress

#1597 1.3.6 changelog update
  CHANGELOG.md
Labels: in progress

#1610 Add PIRL to Readme
  README.md
Labels: in progress

#1583 Chunk JSON-RPC batches in case connection times out
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
Labels: in progress, ready for review

#1577 add process to fix contract with code
  apps/indexer/config/dev.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  config/config.exs
Labels: in progress

#1613 fix usd fee
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1615 add more logging to code fixer process
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
Labels: in progress

#1616 Update 1.3.7 changelog
  CHANGELOG.md
Labels: in progress

#1618 Ethereum Mainnet 1.3.7
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190313103912_change_transactions_v_column_type.exs
  apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  config/config.exs
Labels: in progress

#1614 do not fetch burn address balance
  CHANGELOG.md
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
Labels: in progress

#1611 allow setting first indexing block
  CHANGELOG.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
Labels: in progress

#1621 modify query to fetch failed contract creations
  CHANGELOG.md
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
Labels: in progress

#1629 Kovan 1.3.7
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190313103912_change_transactions_v_column_type.exs
  apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  config/config.exs
Labels: in progress

#1632 Ropsten 1.3.7
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190313103912_change_transactions_v_column_type.exs
  apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  config/config.exs
Labels: in progress

#1633 Sokol 1.3.7
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  apps/block_scout_web/assets/js/lib/from_now.js
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/internal_transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/address_test.exs
  apps/block_scout_web/test/block_scout_web/schema/query/transaction_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transactions.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190313103912_change_transactions_v_column_type.exs
  apps/explorer/priv/repo/migrations/20190318151809_add_inserted_at_index_to_accounts.exs
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code/supervisor.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  config/config.exs
Labels: in progress

#1627 Revert "Fix flaky tests"
  .circleci/config.yml
Labels: in progress

#1637 Fix other explorers
  apps/block_scout_web/config/config.exs
Labels: in progress

#1596 create decompiled smart contracts
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress

#1647 fix typo
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1630 (Fix) colour for release link in the footer
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: ready for review

#1643 Set internal_transactions_indexed_at for empty blocks
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress, ready for review

#1639 Optimize token holder count updates when importing address current balances
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
Labels: in progress, ready for review

#1660 Staging mainnet branch
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/css/theme/_variables.scss
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/config/prod.exs
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/ethereum_jsonrpc/config/config.exs
  apps/explorer/config/config.exs
  apps/explorer/config/dev.exs
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/indexer/config/config.exs
  apps/indexer/config/dev.exs
  apps/indexer/config/prod.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/lib/indexer/code/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
Labels: in progress

#1650 add petersburg evm version to smart contract verifier
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
Labels: in progress, ready for review

#1634 add transaction count cache
  CHANGELOG.md
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
Labels: in progress, ready for review

#1608 feat: add listcontracts endpoint
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
Labels: in progress

#1657 Force consensus loss for parent block if its hash mismatches parent_hash
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Labels: in progress, ready for review

#1663 1.3.8 release - update changelog
  CHANGELOG.md
Labels: in progress

#1668 Ethereum Mainnet production 1.3.8
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1675 Rinkeby v1.3.8
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1677 Sokol 1.3.8
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1678 xDai 1.3.8
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1679 Goerli v1.3.8
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1681 Kovan 1.3.8
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/decompiled_smart_contract.ex
  apps/explorer/lib/explorer/chain/hash.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/priv/repo/migrations/20190319081821_create_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190321185644_add_old_value_for_current_token_balances.exs
  apps/explorer/priv/repo/migrations/20190325081658_remove_unique_address_hash_decompiled_contracts.exs
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/decompiled_smart_contract_test.exs
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address/token_balances.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/internal_transaction/fetcher.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/address/token_balances_test.exs
  apps/indexer/test/indexer/internal_transaction/fetcher_test.exs
Labels: in progress

#1669 do not fail if multiple matching tokens are found
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review

#1661 try to compile with the latest evm version if bytecode doesn't match
  CHANGELOG.md
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
Labels: in progress, ready for review

#1654 tab for decompiled code
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress, ready for review
