Repository blockscout/blockscout, pull requests merged in 2019-05, with the labels that each got.

#1865 Revert "`ex_abi` version bump to 0.2"
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/test/explorer/validator/metadata_retriever_test.exs
Labels: in progress

#1868 fix: logs list endpoint performance
  CHANGELOG.md
  apps/explorer/lib/explorer/etherscan/logs.ex
Labels: in progress

#1871 Transaction importer return created_contract_address_hash
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
Labels: in progress

#1855 Don't lookup in table when table isn't initiated
  apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/exchange_rates/exchange_rates.ex
  apps/explorer/lib/explorer/known_tokens/known_tokens.ex
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/known_tokens/known_tokens_test.exs
Labels: in progress

#1877 Ropsten v1.3.11
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
  rel/commands/clear_build.sh
Labels: in progress

#1859 feat: show raw transaction traces
  CHANGELOG.md
  apps/block_scout_web/assets/js/view_specific/raw_trace/code_highlighting.js
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_raw_trace_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain/internal_transaction.ex
  apps/explorer/lib/explorer/chain/internal_transaction/action.ex
  apps/explorer/lib/explorer/chain/internal_transaction/result.ex
  apps/explorer/test/explorer/chain/internal_transaction_test.exs
Labels: in progress

#1801 Staking pools fetching
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/staking/pools_reader.ex
  apps/explorer/lib/explorer/validator/metadata_retriever.ex
  apps/explorer/priv/contracts_abi/poa/metadata.json
  apps/explorer/priv/contracts_abi/poa/validators.json
  apps/explorer/priv/contracts_abi/pos/staking.json
  apps/explorer/priv/contracts_abi/pos/validators.json
  apps/explorer/test/explorer/chain/import/runner/staking_pools_test.exs
  apps/explorer/test/explorer/staking/pools_reader_test.exs
  apps/indexer/README.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/fetcher/staking_pools.ex
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/test/indexer/fetcher/staking_pools_test.exs
Labels: in progress, ready for review

#1869 Fix output and gas extraction in JS tracer for Geth
  CHANGELOG.md
  apps/ethereum_jsonrpc/priv/js/ethereum_jsonrpc/geth/debug_traceTransaction/tracer.js
Labels: in progress, ready for review

#1857 Re-implement Geth JS internal transaction tracer in Elixir
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/call.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth/tracer.ex
Labels: in progress

#1822 add style to every line of decompiled contract
  CHANGELOG.md
  apps/block_scout_web/assets/css/_code.scss
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_decompiled_contract_view_test.exs
Labels: in progress

#1887 Rinkeby v1.3.11
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
  rel/commands/clear_build.sh
Labels: in progress

#1888 Kovan v1.3.11
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
  rel/commands/clear_build.sh
Labels: in progress

#1812 add pagination to addresses page
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1895 poa theme and poa logo
  CHANGELOG.md
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
  apps/block_scout_web/assets/static/images/poa_logo.svg
Labels: in progress

#1896 requery tokens in top nav automplete
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1885 highlight reserved words
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_decompiled_contract_view_test.exs
Labels: in progress

#1898 check if constructor has arguments
  CHANGELOG.md
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
Labels: in progress

#1892 remove temporary worker modules
  CHANGELOG.md
  apps/indexer/README.md
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/lib/indexer/temporary/addresses_without_code.ex
  apps/indexer/lib/indexer/temporary/failed_created_addresses.ex
  apps/indexer/test/indexer/temporary/addresses_without_code_test.exs
  apps/indexer/test/indexer/temporary/failed_created_addresses_test.exs
Labels: in progress

#1904 fix `BLOCK_COUNT_CACHE_TTL` env var type
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain/block_count_cache.ex
Labels: in progress

#1915 fallback to 2 evm versions
  CHANGELOG.md
  apps/explorer/lib/explorer/smart_contract/verifier.ex
Labels: in progress

#1876 Async calculate a count of blocks
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
Labels: in progress, ready for review

#1905 fix reorgs, uncles pagination
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
Labels: in progress

#1926 (fix) status label alignment
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_tile.scss
Labels: in progress

#1920 fix: remove source code fields from list endpoint
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
Labels: in progress

#1900 SUPPORTED_CHAINS ENV var
  .dialyzer-ignore
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: in progress, ready for review

#1937 Check the presence of overlap[i] object
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/list_morph.js
Labels: in progress

#1928 (Feature) New pagination view
  CHANGELOG.md
  apps/block_scout_web/assets/css/_helpers.scss
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/assets/css/components/_pagination.scss
  apps/block_scout_web/assets/css/components/_pagination_container.scss
  apps/block_scout_web/assets/js/lib/async_listing_load.js
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination_container.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_raw_trace/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1959 Goerli theme and logo
  CHANGELOG.md
  apps/block_scout_web/assets/css/theme/_goerli_variables.scss
  apps/block_scout_web/assets/static/images/goerli_logo.svg
Labels: in progress

#1917 Force block refetch if transaction is re-collated in a different block
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190508152922_add_old_block_hash_for_transactions.exs
  apps/explorer/priv/repo/migrations/20190513134025_add_refetch_needed_to_block.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/indexer/README.md
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Labels: in progress, ready for review

#1944 (fix) Wrong styles for tokens dropdown
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_card.scss
  apps/block_scout_web/assets/css/components/_dropdown.scss
  apps/block_scout_web/lib/block_scout_web/templates/address_token_balance/_token_balances.html.eex
Labels: in progress

#1960 do not remove bold text in decompiled contacts
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_decompiled_contract_view_test.exs
Labels: in progress

#1958 Default value for release link env var
  .dialyzer-ignore
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/test/block_scout_web/views/layout_view_test.exs
Labels: in progress, ready for review

#1933 add eth_BlockNumber
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/block_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/eth_rpc_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/test/explorer/chain/block_number_cache_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: in progress

#1956 event logs tab
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_logs/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_logs_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1916 Fetch additional data from POSDAO
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/paging_options.ex
  apps/explorer/lib/explorer/staking/epoch_counter.ex
  apps/explorer/lib/explorer/staking/pools_reader.ex
  apps/explorer/priv/contracts_abi/pos/staking.json
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/staking/epoch_counter_test.exs
  apps/explorer/test/explorer/staking/pools_reader_test.exs
  apps/indexer/lib/indexer/fetcher/staking_pools.ex
  apps/indexer/test/indexer/fetcher/staking_pools_test.exs
Labels: in progress, ready for review

#1975 add log index to transaction view
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Labels: in progress

#1967 organize README, add links to external resources
  README.md
Labels: in progress

#1957 Calculate staked ratio before insert pools
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/test/explorer/chain/import/runner/staking_pools_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress, ready for review

#1988 Fix wrong parity tasks names in Circle CI
  .circleci/config.yml
  CHANGELOG.md
Labels: ready for review

#2002 Get estimated count of blocks when cache is empty
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
Labels: ready for review

#1966 fix: add fields for contract filter performance
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/explorer/lib/explorer/smart_contract/solc_downloader.ex
  apps/explorer/priv/repo/migrations/20190516140202_add_address_hash_index_to_decompiled_smart_contracts.exs
  apps/explorer/priv/repo/migrations/20190516160535_add_decompiled_and_verified_flag_to_addresses.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: in progress

#1974 pagination and navigation
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/async_listing_load.js
  apps/block_scout_web/lib/block_scout_web/controllers/pagination_helpers.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_pagination_container.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/common_components_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1964 ALLOWED_EVM_VERSIONS env var
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Labels: ready for review

#2010 Block/tx not found errors pages
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_errors.scss
  apps/block_scout_web/assets/static/images/errors-img/etc-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/etc-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/etc-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/etc-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/eth-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/eth-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/eth-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/eth-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/goerli-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/goerli-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/goerli-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/goerli-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/koan-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/kovan-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/kovan-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/kovan-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/kovan-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/poa-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/poa-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/poa-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/poa-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/rinkeby-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/rinkeby-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/rinkeby-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/rinkeby-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/rinnkeby-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/rinnkeby-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/ropsten-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/ropsten-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/ropsten-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/ropsten-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/rsk-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/rsk-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/rsk-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/rsk-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/sokol-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/sokol-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/sokol-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/sokol-tx-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/xdai-block-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/xdai-block-not-found@2x.png
  apps/block_scout_web/assets/static/images/errors-img/xdai-tx-not-found.png
  apps/block_scout_web/assets/static/images/errors-img/xdai-tx-not-found@2x.png
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/404.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/not_found.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
Labels: ready for review

#2018 Use PORT env variable in dev config
  CHANGELOG.md
  apps/block_scout_web/config/dev.exs
Labels: ready for review

#1890 Verification links to other explorers
  CHANGELOG.md
  apps/block_scout_web/assets/css/_mixins.scss
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_verify_other_explorers.scss
  apps/block_scout_web/assets/static/images/icons/blockchair.png
  apps/block_scout_web/assets/static/images/icons/blockchair@2x.png
  apps/block_scout_web/assets/static/images/icons/etherchain.png
  apps/block_scout_web/assets/static/images/icons/etherchain@2x.png
  apps/block_scout_web/assets/static/images/icons/etherscan.png
  apps/block_scout_web/assets/static/images/icons/etherscan@2x.png
  apps/block_scout_web/assets/static/images/icons/link.svg
  apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorers.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#2040 Verification links to other explorers
  CHANGELOG.md
  apps/block_scout_web/assets/css/_mixins.scss
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_verify_other_explorers.scss
  apps/block_scout_web/assets/static/images/icons/blockchair.png
  apps/block_scout_web/assets/static/images/icons/blockchair@2x.png
  apps/block_scout_web/assets/static/images/icons/etherchain.png
  apps/block_scout_web/assets/static/images/icons/etherchain@2x.png
  apps/block_scout_web/assets/static/images/icons/etherscan.png
  apps/block_scout_web/assets/static/images/icons/etherscan@2x.png
  apps/block_scout_web/assets/static/images/icons/link.svg
  apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorer_modal.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_verify_other_explorers.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2027 Fix BlocksTransactionsMismatch temporary fetcher
  CHANGELOG.md
  apps/explorer/priv/repo/migrations/20190513134025_add_refetch_needed_to_block.exs
  apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Labels: ready for review

#2055 Increase timeout for geth indexers
  CHANGELOG.md
  apps/indexer/config/prod/geth.exs
Labels: ready for review

#2069 Docsify integration: static docs page generation
  CHANGELOG.md
  docs/.gitkeep
  docs/.nojekyll
  docs/README.md
  docs/index.html
Labels: ready for review

#2036 New tables for staking pools and delegators
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools_delegators.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/staking_pool.ex
  apps/explorer/lib/explorer/chain/staking_pools_delegator.ex
  apps/explorer/lib/explorer/staking/pools_reader.ex
  apps/explorer/priv/repo/migrations/20190521104412_create_staking_pools.exs
  apps/explorer/priv/repo/migrations/20190523112839_create_staking_pools_delegators.exs
  apps/explorer/test/explorer/chain/import/runner/staking_pools_delegators_test.exs
  apps/explorer/test/explorer/chain/import/runner/staking_pools_test.exs
  apps/explorer/test/explorer/chain/staking_pool_test.exs
  apps/explorer/test/explorer/chain/staking_pools_delegator_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/staking/pools_reader_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/fetcher/staking_pools.ex
  apps/indexer/test/indexer/fetcher/staking_pools_test.exs
Labels: ready for review

#2070 Reduce max_concurrency of BlocksTransactionsMismatch
  CHANGELOG.md
  apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Labels: ready for review
