Repository blockscout/blockscout, pull requests merged in 2019-04, with the labels that each got.

#1671 use postgres stats as fallback for transaction count
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
Labels: in progress, ready for review

#1688 do not fail if failure reason is atom
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
Labels: in progress, ready for review

#1692 exclude decompiled smart contract from encoding
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/address.ex
Labels: in progress

#1691 decrease token metadata update interval
  CHANGELOG.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1662 allow specifying number of optimization runs
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
Labels: in progress

#1658 Add with version filter
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
Labels: in progress

#1684 Discard child block with parent_hash not matching hash of imported block
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
Labels: in progress, ready for review

#1665 Verify contracts rpc
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
Labels: in progress

#1697 fix failing in rpc if balance is empty
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
Labels: in progress

#1699 use seconds as transaction cache period measure
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
Labels: in progress

#1712 do not set contract code from transaction input
  apps/indexer/lib/indexer/address_extraction.ex
Labels: in progress

#1693 Add a checklist to the PR template
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
Labels: in progress, ready for review

#1706 allow setting update interval for addresses with balances counter
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
Labels: in progress

#1711 rescue failing repo in block number cache update
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/block_number_cache.ex
Labels: in progress

#1708 Update config.yml
  .circleci/config.yml
Labels: in progress

#1715 1.3.9 release (Mainnet-Staging)
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/helpers.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/contract_verify_page.ex
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/priv/repo/migrations/scripts/20190326202921_lose_consensus_for_invalid_blocks.sql
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/prod/parity.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1714 fix average block time calculation
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/explorer/test/explorer/counters/average_block_time_test.exs
  apps/indexer/test/indexer/coin_balance/on_demand_fetcher_test.exs
Labels: in progress

#1716 finalize 1.3.9 release
  CHANGELOG.md
Labels: in progress

#1727 add logs pagination in rpc api
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Labels: in progress

#1724 Remove internal tx and token balance fetching from realtime fetcher
  CHANGELOG.md
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Labels: in progress

#1705 Adopt BS for Lukso: customize coin
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
Labels: in progress

#1740 fix empty block time
  CHANGELOG.md
  apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
Labels: in progress

#1739 highlight decompiled source code
  CHANGELOG.md
  apps/block_scout_web/assets/css/_code.scss
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_decompiled_code_test.exs
Labels: in progress

#1720 Goerli v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1743 sort decompiled smart contracts in lexicographical order
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_decompiled_contract_view_test.exs
Labels: in progress

#1723 Sokol v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1734 Ropsten v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1733 Rinkeby v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1736 Mainnet v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1729 xDAI v1.3.9
  .circleci/config.yml
  CHANGELOG.md
  PULL_REQUEST_TEMPLATE.md
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_decompiled_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
  apps/block_scout_web/test/support/fixture/smart_contract/compiler_tests.json
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/contract.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/transaction_count_cache.ex
  apps/explorer/lib/explorer/counters/addresses_with_balance_counter.ex
  apps/explorer/lib/explorer/smart_contract/solidity/code_compiler.ex
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/priv/compile_solc.js
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/verifier_test.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/invalid_consensus/supervisor.ex
  apps/indexer/lib/indexer/block/invalid_consensus/worker.ex
  apps/indexer/lib/indexer/block/realtime/consensus_ensurer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/token/fetcher.ex
  apps/indexer/test/indexer/block/invalid_consensus/worker_test.exs
  apps/indexer/test/indexer/token/fetcher_test.exs
Labels: in progress

#1753 add check mark to decompiled contract tab
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_decompiled_contract/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1749 (Fix) Update telegram link
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
Labels: in progress, ready for review

#1742 Feat: Add RSK Support
  CHANGELOG.md
  README.md
  apps/ethereum_jsonrpc/config/config.exs
  apps/ethereum_jsonrpc/config/test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/application.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/request_coordinator.ex
  apps/ethereum_jsonrpc/lib/rsk.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/request_coordinator_test.exs
  apps/explorer/config/dev/rsk.exs
  apps/explorer/config/prod/rsk.exs
  apps/explorer/config/test/rsk.exs
  apps/indexer/config/dev/rsk.exs
  apps/indexer/config/prod/rsk.exs
  apps/indexer/lib/indexer/supervisor.ex
Labels: in progress

#1701 feat: slightly more informative json rpc error messages + logging
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/rpc_translator_test.exs
Labels: in progress

#1744 remove `0x0..0` from tests
  CHANGELOG.md
  apps/explorer/test/support/factory.ex
Labels: in progress

#1696 add postgres full text search by tokens
  .circleci/config.yml
  CHANGELOG.md
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/csp_header.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/address_contract_verification_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/priv/repo/migrations/20190403080447_add_full_text_search_tokens.exs
  apps/explorer/test/explorer/chain_test.exs
  bin/install_chrome_headless.sh
  mix.lock
Labels: in progress

#1756 add today's token balance from the previous value
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: in progress

#1763 Describe indexer structure and list existing fetchers
  CHANGELOG.md
  apps/indexer/README.md
Labels: in progress

#1773 Aerum v1.3.9
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
Labels: in progress

#1774 Callisto v1.3.9
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
Labels: in progress

#1757 (Chore) Change twitter acc link to official Blockscout acc twitter
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
Labels: in progress, ready for review

#1778 Make websocket optional for realtime fetcher
  CHANGELOG.md
  apps/indexer/config/prod/parity.exs
  apps/indexer/config/prod/rsk.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/supervisor.ex
Labels: in progress

#1768 fix first block parameter
  CHANGELOG.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
Labels: in progress

#1769 add timestamp to block overview
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/from_now.js
Labels: in progress

#1777 optionally show ERC-20 token transfer info
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1780 Update link to the github repo in the footer
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
Labels: ready for review

#1770 feat: set a websocket keepalive from config
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/web_socket/web_socket_client_test.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/geth.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/mox.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/case/parity.ex
  apps/indexer/README.md
  apps/indexer/lib/indexer/block/realtime/supervisor.ex
Labels: in progress

#1785 Aerum v1.3.9
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
Labels: in progress

#1784 RSK v1.3.9: Change coin
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
Labels: in progress

#1783 Update README with the chains that use Blockscout
  CHANGELOG.md
  README.md
Labels: ready for review

#1748 Update links in footer
  apps/block_scout_web/config/config.exs
Labels: in progress

#1795 fix line numbers for decompiled contracts
  CHANGELOG.md
  apps/block_scout_web/assets/css/_code.scss
Labels: in progress

#1789 add ERC-721 info to transaction overview page
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
Labels: in progress

#1793 fix top nav autocomplete
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1790 fix constructor arguments verification
  CHANGELOG.md
  apps/explorer/lib/explorer/smart_contract/verifier.ex
  apps/explorer/lib/explorer/smart_contract/verifier/constructor_arguments.ex
  apps/explorer/test/explorer/smart_contract/verifier/constructor_arguments_test.exs
Labels: in progress

#1531 docker: fix dockerFile for secp256k1 building
  docker/Dockerfile
Labels: Docker, in progress

#1802 make coinmarketcap's number of pages configurable
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
Labels: in progress

#1800 Disable lazy logging check in Credo
  .credo.exs
  CHANGELOG.md
Labels: in progress, ready for review

#1799 Use eth_getUncleByBlockHashAndIndex for uncle block fetching
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_nephew.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncle.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/uncles.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block/second_degree_relation.ex
  apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex
  apps/explorer/priv/repo/migrations/20190421143300_add_index_to_bsdr.exs
  apps/explorer/test/explorer/chain/block/second_degree_relation_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/README.md
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/uncle_block.ex
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/lib/indexer/temporary/uncles_without_index.ex
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/fetcher/uncle_block_test.exs
Labels: ready for review

#1803 use coinmarketcap for total_supply by default
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/channels/exchange_rate_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/supply/coin_market_cap.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_gecko.ex
  apps/explorer/lib/explorer/exchange_rates/source/coin_market_cap.ex
  apps/explorer/lib/explorer/exchange_rates/source/transaction_and_log.ex
  apps/explorer/lib/explorer/exchange_rates/token.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/exchange_rates/exchange_rates_test.exs
  apps/explorer/test/explorer/exchange_rates/source/coin_gecko_test.exs
  apps/explorer/test/explorer/exchange_rates/source/coin_market_cap_test.exs
  apps/explorer/test/support/fakes/one_coin_source.ex
Labels: in progress

#1804 (Chore) Divide chains by Mainnet/Testnet in menu
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Labels: in progress, ready for review

#1806 feat: verify contracts with a post request
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
Labels: in progress

#1814 (Chore) Clear build artefacts script
  CHANGELOG.md
  rel/commands/clear_build.sh
Labels: ready for review

#1815 Able to search without prefix "0x"
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
Labels: in progress, ready for review

#1813 Add total blocks counter
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#1829 Handle nil size in block decoding routine
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
Labels: ready for review

#1830 Make block size field nullable
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
Labels: ready for review

#1835 fix: ignore `pong` messages without error
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
Labels: in progress

#1838 Block counter calculates only consensus blocks
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/explorer/lib/explorer/chain.ex
Labels: in progress, ready for review

#1837 (Chore) Add -f flag to clear_build.sh script delete static folder
  CHANGELOG.md
  rel/commands/clear_build.sh
Labels: in progress, ready for review

#1840 Handle case when total supply is nil
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain.ex
Labels: in progress, ready for review

#1848 Add cache for block counter
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
Labels: in progress, ready for review

#1852 LUKSO 1.3.11
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/web_socket/web_socket_client.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/block_count_cache.ex
  apps/explorer/priv/repo/migrations/20190424170833_change_block_size_to_nullable.exs
  apps/explorer/test/explorer/chain/block_count_cache_test.exs
  rel/commands/clear_build.sh
Labels: in progress

#1846 Disable usd value in transaction if there no exchange_rate
  apps/block_scout_web/lib/block_scout_web/templates/address/_balance_card.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#1853 (Feature) New pages for POSDAO network
  apps/block_scout_web/assets/css/theme/_posdao_variables.scss
  apps/block_scout_web/assets/css/theme/_variables.scss
  apps/block_scout_web/lib/block_scout_web/controllers/active_pools_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/inactive_pools_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/validators_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/active_pools/_table.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/active_pools/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/inactive_pools/_table.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/inactive_pools/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_address.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_btn_remove_pool.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_btn_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_btn_withdraw.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_withdraw.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_empty_content.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_progress.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item_account.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_table.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_th.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_title.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_validator_info_item.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/validators/_table.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/validators/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/active_pools_view.ex
  apps/block_scout_web/lib/block_scout_web/views/inactive_pools_view.ex
  apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
  apps/block_scout_web/lib/block_scout_web/views/validators_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/encoder.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/test/explorer/validator/metadata_retriever_test.exs
  mix.lock
Labels: in progress

#1849 Improve chains menu
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_dropdown.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress, ready for review

#1863 Stringify solc error message instead of Error instance
  apps/explorer/priv/compile_solc.js
Labels: ready for review
