Repository blockscout/blockscout, pull requests merged in 2019-12, with the labels that each got.

#2895 do no remove non-consensus logs
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/log.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/receipts_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/logs.ex
  apps/explorer/lib/explorer/chain/log.ex
  apps/explorer/priv/repo/migrations/20191121064805_add_block_hash_and_block_index_to_logs.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain/log_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/factory.ex
Labels: indexing

#2902 Offset in blocks retrieval for average block time
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/explorer/test/explorer/counters/average_block_time_test.exs
  apps/indexer/test/indexer/fetcher/coin_balance_on_demand_test.exs
Labels: ready for review

#2857 Extend getsourcecode API view with new output fields
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/contract_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/contract_controller_test.exs
Labels: ready for review

#2913 clean reorgs in pending block ops by schedule
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/indexer/lib/indexer/pending_ops_cleaner.ex
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/test/indexer/pending_ops_cleaner_test.exs
Labels: indexing

#2925 Mitigate issues in the migration to "block_hash" indexing approach
  CHANGELOG.md
  apps/explorer/priv/repo/migrations/20191018140054_add_pending_internal_txs_operation.exs
  apps/explorer/priv/repo/migrations/20191121064805_add_block_hash_and_block_index_to_logs.exs
  apps/explorer/priv/repo/migrations/20191122062035_add_block_hash_to_token_transfers.exs
Labels: indexing, ready for review

#2929 Speedup pending block ops int txs to fetch query
  CHANGELOG.md
  apps/explorer/priv/repo/migrations/20191220113006_pending_block_operations_block_hash_partial_index.exs
Labels: ready for review

#2918 Add tokenID for tokentx API action explicitly
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
Labels: api, ready for review

#2914 Reduce execution time of stream_unfetched_token_instances query
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
Labels: performance, ready for review

#2924 Speedup address to logs query
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/priv/repo/migrations/20191218120138_logs_block_number_index_index.exs
Labels: indexing, ready for review

#2915 Speedup of blocks_without_reward_query
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/priv/repo/migrations/20191208135613_block_rewards_block_hash_partial_index.exs
Labels: performance, ready for review

#2887 Increase chart loading speed
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/chart-loader.js
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/lib/modals.js
  apps/block_scout_web/assets/js/pages/address/coin_balances.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/webpack.config.js
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: UI

#2926 API endpoint: sum of balances except burning address
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/rpc_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/address_sum_minus_burnt.ex
  apps/explorer/test/explorer/chain/cache/address_sum_minus_burnt.exs
  apps/explorer/test/explorer/chain/cache/address_sum_test.exs
Labels: ready for review

#2933 Get rid of deadlock in the query to address_current_token_balance table
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Labels: ready for review
