Repository blockscout/blockscout, pull requests merged in 2019-07, with the labels that each got.

#2270 Remove duplicate params in `Indexer.Fetcher.TokenBalance`
  CHANGELOG.md
  apps/indexer/lib/indexer/fetcher/token_balance.ex
  apps/indexer/test/indexer/fetcher/token_balance_test.exs
Labels: ready for review

#2198 Reduce transaction status and error constraint
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190619154943_reduce_transaction_status_constraint.exs
  apps/explorer/test/explorer/chain/import_test.exs
Labels: ready for review

#2216 Improve token's controllers by avoiding unnecessary preloads
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/fetcher/token.ex
  apps/indexer/lib/indexer/fetcher/token_updater.ex
Labels: ready for review

#2244 Fix internal transactions failing to be indexed because of constraint
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
Labels: ready for review

#2267 Modify implementation of `where_transaction_has_multiple_internal_transactions`
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
Labels: ready for review

#2249 More transaction controllers improvements
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#2258 Reduce BlocksTransactionsMismatch memory footprint
  CHANGELOG.md
  apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
Labels: ready for review

#2283 Add transactions cache
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/recent_transactions_controller.ex
  apps/block_scout_web/test/support/conn_case.ex
  apps/block_scout_web/test/support/feature_case.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/transactions_cache.ex
  apps/explorer/test/explorer/chain/transactions_cache_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: ready for review

#2237 fix rsk total_supply
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/supply/rsk.ex
  apps/explorer/test/explorer/chain/supply/rsk_test.exs
Labels: chain: RSK :chains:

#2205 Fetching inactive delegators
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools_delegators.ex
  apps/explorer/lib/explorer/chain/staking_pools_delegator.ex
  apps/explorer/lib/explorer/staking/pools_reader.ex
  apps/explorer/priv/contracts_abi/pos/staking.json
  apps/explorer/priv/repo/migrations/20190605125829_delegators_deleted_colum.exs
  apps/explorer/test/explorer/staking/pools_reader_test.exs
  apps/indexer/test/indexer/fetcher/staking_pools_test.exs
Labels: chain: POSDAO :chains:, ready for review

#2289 Optional websockets for dev environment
  CHANGELOG.md
  apps/indexer/config/dev/parity.exs
  apps/indexer/config/dev/rsk.exs
Labels: ready for review

#2290 Add eth_get_balance.json to AddressView's render
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/address_view.ex
Labels: ready for review

#2305 Improve Address controllers
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/fetcher/token.ex
  apps/indexer/lib/indexer/fetcher/token_updater.ex
Labels: ready for review

#2323 Group Explorer caches
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
  apps/block_scout_web/test/support/conn_case.ex
  apps/block_scout_web/test/support/feature_case.ex
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/cache/block_count.ex
  apps/explorer/lib/explorer/chain/cache/block_number.ex
  apps/explorer/lib/explorer/chain/cache/blocks.ex
  apps/explorer/lib/explorer/chain/cache/net_version.ex
  apps/explorer/lib/explorer/chain/cache/transaction_count.ex
  apps/explorer/lib/explorer/chain/cache/transactions.ex
  apps/explorer/lib/explorer/chain/supply/rsk.ex
  apps/explorer/test/explorer/chain/block_number_cache_test.exs
  apps/explorer/test/explorer/chain/cache/block_count_test.exs
  apps/explorer/test/explorer/chain/cache/block_number_test.exs
  apps/explorer/test/explorer/chain/cache/blocks_test.exs
  apps/explorer/test/explorer/chain/cache/transaction_count_test.exs
  apps/explorer/test/explorer/chain/cache/transactions_test.exs
  apps/explorer/test/explorer/chain/transaction_count_cache_test.exs
  apps/explorer/test/explorer/market/market_history_cache_test.exs
  apps/explorer/test/explorer/market/market_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
Labels: ready for review

#2325 Reduce function input to address' hash only where possible
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_decompiled_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_validation_controller.ex
  apps/block_scout_web/lib/block_scout_web/resolvers/transaction.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address_token_transfer_csv_exporter.ex
  apps/explorer/lib/explorer/chain/address_transaction_csv_exporter.ex
  apps/explorer/lib/explorer/graphql.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/graphql_test.exs
Labels: ready for review

#2346 Avoid fetching internal transactions of blocks that still need refetching
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/support/factory.ex
Labels: ready for review

#2352 Fetch rewards in parallel with transactions
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/explorer/lib/explorer/chain.ex
Labels: ready for review

#2375 Update created_contract_code_indexed_at on transaction import conflict
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/test/explorer/chain/import/runner/transactions_test.exs
Labels: ready for review

#2379 Disable network selector when is empty
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: ready for review

#2378 Page performance: exclude moment.js localization files except EN, remove unused css
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_footer.scss
  apps/block_scout_web/assets/css/components/_network-selector.scss
  apps/block_scout_web/assets/webpack.config.js
Labels: ready for review

#2389 Reduce Lodash lib size (86% of lib methods are not used)
  CHANGELOG.md
  apps/block_scout_web/assets/__tests__/pages/pending_transactions.js
  apps/block_scout_web/assets/js/lib/async_listing_load.js
  apps/block_scout_web/assets/js/lib/infinite_scroll_helpers.js
  apps/block_scout_web/assets/js/lib/list_morph.js
  apps/block_scout_web/assets/js/lib/redux_helpers.js
  apps/block_scout_web/assets/js/lib/utils.js
  apps/block_scout_web/assets/js/pages/address.js
  apps/block_scout_web/assets/js/pages/address/coin_balances.js
  apps/block_scout_web/assets/js/pages/address/internal_transactions.js
  apps/block_scout_web/assets/js/pages/address/logs.js
  apps/block_scout_web/assets/js/pages/address/transactions.js
  apps/block_scout_web/assets/js/pages/address/validations.js
  apps/block_scout_web/assets/js/pages/blocks.js
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/assets/js/pages/pending_transactions.js
  apps/block_scout_web/assets/js/pages/transaction.js
  apps/block_scout_web/assets/js/pages/transactions.js
  apps/block_scout_web/assets/js/pages/verification_form.js
  apps/block_scout_web/assets/webpack.config.js
Labels: ready for review

#2401 Add ENV vars to manage updating period
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/explorer/lib/explorer/market/market_history_cache.ex
Labels: ready for review

#2391 Controllers Improvements
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/verified_smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/smart_contract/reader.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/smart_contract/reader_test.exs
Labels: ready for review

#2407 Refresh staking page top panel when new blocks arrive
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/channels/stakes_channel_test.exs
  apps/explorer/lib/explorer/chain/events/subscriber.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
Labels: chain: POSDAO :chains:

#2418 Remove parentheses in market cap percentage
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address/_tile.html.eex
Labels: ready for review

#2405 Tiles and table loaders for all views
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_stakes_table.scss
  apps/block_scout_web/assets/css/components/_tile.scss
  apps/block_scout_web/lib/block_scout_web/templates/address/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_logs/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_token_transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_validation/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_table-loader.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_tile-loader.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/pending_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_internal_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_log/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2416 Fix "page not found" handling in the router
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/smart_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
Labels: ready for review

#2412 Dark theme
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/css/theme/_dai_variables.scss
  apps/block_scout_web/assets/css/theme/_dark-theme.scss
  apps/block_scout_web/assets/css/theme/_ethereum_classic_variables.scss
  apps/block_scout_web/assets/css/theme/_ethereum_variables.scss
  apps/block_scout_web/assets/css/theme/_goerli_variables.scss
  apps/block_scout_web/assets/css/theme/_kovan_variables.scss
  apps/block_scout_web/assets/css/theme/_lukso_variables.scss
  apps/block_scout_web/assets/css/theme/_neutral_variables.scss
  apps/block_scout_web/assets/css/theme/_poa_variables.scss
  apps/block_scout_web/assets/css/theme/_rinkeby_variables.scss
  apps/block_scout_web/assets/css/theme/_ropsten_variables.scss
  apps/block_scout_web/assets/css/theme/_rsk_variables.scss
  apps/block_scout_web/assets/css/theme/_sokol_variables.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/market_history_chart.js
  apps/block_scout_web/assets/js/pages/dark-mode-switcher.js
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/priv/gettext/errors.pot
Labels: ready for review

#2419 Fetch and use staking token for all staking amounts
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/views/stakes_helpers.ex
  apps/explorer/lib/explorer/chain/staking_pool.ex
  apps/explorer/lib/explorer/chain/staking_pools_delegator.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
Labels: chain: POSDAO :chains:

#2421 Fix hiding of loader for txs on the main page
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
Labels: ready for review

#2424 Use new validatorRewardPercent getter for block reward ratios
  apps/explorer/lib/explorer/staking/contract_reader.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
  apps/explorer/priv/contracts_abi/posdao/BlockRewardAuRa.json
  apps/explorer/priv/contracts_abi/posdao/StakingAuRa.json
  apps/explorer/test/explorer/staking/contract_state_test.exs
Labels: chain: POSDAO :chains:

#2450 Fix clearance of logs and node_modules folders in clearing script
  CHANGELOG.md
  rel/commands/clear_build.sh
Labels: ready for review

#2425 Force to show address view for checksummed address even if it is not in DB
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_coin_balance_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
Labels: ready for review

#2435 Replace deprecated extract-text-webpack-plugin with mini-css-extract-plugin
  CHANGELOG.md
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/assets/webpack.config.js
Labels: ready for review

#2439 Show modal window with validator/pool info
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/validator_info.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_address.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex
Labels: chain: POSDAO :chains:

#2460 Show "Become a Candidate" modal window
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/become_candidate.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_empty_content.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: chain: POSDAO :chains:

#2461 Show "Remove my Poll" modal window
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/remove_pool.js
Labels: chain: POSDAO :chains:

#2462 Show "Make Stake" modal window
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/make_stake.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: chain: POSDAO :chains:

#2464 Show "Move Stake" modal window
  apps/block_scout_web/assets/css/components/_modal_bottom_disclaimer.scss
  apps/block_scout_web/assets/css/components/_modal_stake.scss
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/move_stake.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
Labels: chain: POSDAO :chains:
