Repository blockscout/blockscout, pull requests merged in 2019-08, with the labels that each got.

#2402 bump otp version to 22.0
  .circleci/config.yml
  .tool-versions
  CHANGELOG.md
  docker/Dockerfile
  mix.exs
Labels: ready for review

#2503 Mitigate autocompletion library influence to page loading performance
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/awesomplete-util.js
  apps/block_scout_web/assets/js/lib/awesomplete.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/assets/webpack.config.js
  apps/block_scout_web/lib/block_scout_web/csp_header.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/package-lock.json
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2373 Add script to validate internal_transactions constraint for large DBs
  CHANGELOG.md
  apps/explorer/priv/repo/migrations/20181108205650_additional_internal_transaction_constraints.exs
  apps/explorer/priv/repo/migrations/scripts/20181108205650_large_additional_internal_transaction_constraints.sql
Labels: ready for review

#2473 get rid of cldr warnings
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web/channels/address_channel.ex
  apps/block_scout_web/lib/block_scout_web/cldr.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/schema/types.ex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/lib/block_scout_web/views/block_view.ex
  apps/block_scout_web/lib/block_scout_web/views/cldr_helper/number.ex
  apps/block_scout_web/lib/block_scout_web/views/currency_helpers.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/wei_helpers.ex
  apps/block_scout_web/mix.exs
  apps/explorer/mix.exs
  mix.lock
Labels: ready for review

#2506 Fix a bug with active tab
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: ready for review

#2523 Avoid importing internal_transactions of pending transactions
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
Labels: ready for review

#2403 Return gasPrice at gettxinfo API's method
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
Labels: api, ready for review

#2376 Split API and WebApp routes
  CHANGELOG.md
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/api_router.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/router.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/lib/block_scout_web/web_router.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/rpc_translator_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/decompiled_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/health_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/supply_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/verified_smart_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/pending_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/recent_transactions_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_log_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/transaction_token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_logs_page.ex
  apps/block_scout_web/test/support/conn_case.ex
  apps/explorer/config/config.exs
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/application.ex
  docs/env-variables.md
Labels: ready for review

#2433 Add functionality to try Eth RPC methods in documentation
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_api.scss
  apps/block_scout_web/assets/css/components/_button.scss
  apps/block_scout_web/assets/css/components/_form.scss
  apps/block_scout_web/assets/css/theme/_base_variables.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/try_eth_api.js
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/_eth_rpc_item.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/api_docs/eth_rpc.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/eth_rpc.ex
Labels: ready for review

#2514 Isolating of staking dapp css && extracting of non-critical css
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_modal.scss
  apps/block_scout_web/assets/css/components/_modal_variables.scss
  apps/block_scout_web/assets/css/components/_stakes_variables.scss
  apps/block_scout_web/assets/css/components/stakes/_copy_icon.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_become_candidate.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_bottom_disclaimer.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_stake.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_validator_info.scss
  apps/block_scout_web/assets/css/components/stakes/_progress_from_to.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes_btn_remove_pool.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes_empty_content.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes_progress.scss
  apps/block_scout_web/assets/css/non-critical.scss
  apps/block_scout_web/assets/css/stakes.scss
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/webpack.config.js
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2549 Fix wrong colour of tooltip
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/non-critical.scss
Labels: ready for review

#2548 CSS preload support in Firefox
  CHANGELOG.md
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Labels: ready for review

#2553 Dark theme import to the end of sass
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
Labels: ready for review

#2551 Correctly handle dynamically created Bootstrap tooltips
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/tooltip.js
Labels: ready for review

#2471 Add update of total supply and balances on each block
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/staking/contract_reader.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
  apps/explorer/test/explorer/staking/contract_state_test.exs
Labels: chain: POSDAO :chains:

#2497 Add generic Ordered Cache behaviour and implementation
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/controllers/api/v1/health_controller_test.exs
  apps/block_scout_web/test/support/conn_case.ex
  apps/block_scout_web/test/support/feature_case.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/blocks.ex
  apps/explorer/lib/explorer/chain/cache/transactions.ex
  apps/explorer/lib/explorer/chain/ordered_cache.ex
  apps/explorer/test/explorer/chain/cache/blocks_test.exs
  apps/explorer/test/explorer/market/market_history_cache_test.exs
  apps/explorer/test/explorer/market/market_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
Labels: ready for review

#2570 Network icons preload
  CHANGELOG.md
  apps/block_scout_web/assets/css/_images-preload.scss
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_network-selector.scss
  apps/block_scout_web/lib/block_scout_web/templates/layout/_network_selector_item.html.eex
Labels: ready for review

#2572 Ease non-critical css
  CHANGELOG.md
  apps/block_scout_web/assets/css/non-critical.scss
  apps/block_scout_web/assets/css/theme/_dai_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_ether1_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_ethereum_classic_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_ethereum_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_goerli_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_kovan_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_lukso_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_neutral_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_poa_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_rinkeby_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_ropsten_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_rsk_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_sokol_variables-non-critical.scss
  apps/block_scout_web/assets/css/theme/_variables-non-critical.scss
Labels: ready for review

#2558 Implement filters for staking pool tables
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_title.html.eex
  apps/explorer/lib/explorer/chain.ex
Labels: chain: POSDAO :chains:

#2614 Consider a pool to be a delegator for itself and fetch its delegator data
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
  apps/explorer/test/explorer/staking/contract_state_test.exs
Labels: chain: POSDAO :chains:

#2640 SVG network icons
  CHANGELOG.md
  apps/block_scout_web/assets/css/_images-preload.scss
  apps/block_scout_web/assets/css/components/_network-selector.scss
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/static/images/network-selector-icons/aerum-mainnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/callisto-mainnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/callisto-mainnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/callisto.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/core.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/dai.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/ethereum-classic.png
  apps/block_scout_web/assets/static/images/network-selector-icons/ethereum-classic.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/ethereum-mainnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/ethereum-mainnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/goerli-testnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/goerli-testnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/kovan-testnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/kovan-testnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/lukso-l14-testnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/lukso-l14-testnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/poa-core.png
  apps/block_scout_web/assets/static/images/network-selector-icons/poa-core.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/poa-sokol.png
  apps/block_scout_web/assets/static/images/network-selector-icons/poa-sokol.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/rinkeby-testnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/rinkeby-testnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/rinkeby.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/ropsten-testnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/ropsten-testnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/ropsten.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/rsk-mainnet.png
  apps/block_scout_web/assets/static/images/network-selector-icons/rsk-mainnet.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/sokol.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/xdai-chain.png
  apps/block_scout_web/assets/static/images/network-selector-icons/xdai-chain.svg
Labels: ready for review

#2581 Add generic Map-like Cache behaviour and implementation
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/cache/block_count.ex
  apps/explorer/lib/explorer/chain/cache/block_number.ex
  apps/explorer/lib/explorer/chain/cache/net_version.ex
  apps/explorer/lib/explorer/chain/cache/transaction_count.ex
  apps/explorer/lib/explorer/chain/map_cache.ex
  apps/explorer/lib/explorer/chain/supply/rsk.ex
  apps/explorer/test/explorer/chain/cache/block_count_test.exs
  apps/explorer/test/explorer/chain/cache/block_number_test.exs
  apps/explorer/test/explorer/chain/cache/blocks_test.exs
  apps/explorer/test/explorer/chain/cache/transaction_count_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
Labels: ready for review
