Repository blockscout/blockscout, pull requests merged in 2019-01, with the labels that each got.

#1291 Use COUNT(*) and index of current_token_balances to eliminate TokenHoldersCounter
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/index.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/holder_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/inventory_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/tokens/read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_tokens_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/address/token_balance.ex
  apps/explorer/lib/explorer/counters/token_holders_counter.ex
  apps/explorer/priv/repo/migrations/20190102141900_index_current_token_holders.exs
  apps/explorer/test/explorer/chain/address/token_balance_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/token_holders_counter_test.exs
Labels: bug :bug:, in progress, ready for review

#1296 Order current token balance inserts to prevent deadlock
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/token_balance/fetcher.ex
  apps/indexer/lib/indexer/token_balances.ex
Labels: bug :bug:, in progress, ready for review, team: architecture

#1292 feat: store averge block time in a genserver
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/explorer/mix.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/average_block_time_test.exs
Labels: in progress

#1289 Fix test warning db connection error
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_transactions_test.exs
  apps/block_scout_web/test/support/feature_case.ex
Labels: in progress

#1293 Don't fetch or import internal transactions for successful value transfers
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/channels/transaction_channel_test.exs
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/uncle/fetcher.ex
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Labels: enhancement, in progress, ready for review, team: architecture

#1305 Don't fetch internal transactions for simple token transfers
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: enhancement, in progress, ready for review, team: architecture

#1300 feat: render block time with up to one decimal point of accuracy
  apps/block_scout_web/lib/block_scout_web/channels/block_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/explorer/lib/explorer/counters/average_block_time_duration_format.ex
  apps/explorer/test/explorer/counters/average_block_time_test.exs
Labels: in progress

#1313 Restrict `Explorer.Chain.Block.get_blocks_without_reward` to consensus
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: bug :bug:, enhancement, in progress

#1309 Delete block_rewards for non-consensus or old consensus blocks
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Labels: bug :bug:, in progress, team: architecture

#1315 Order topics by array order, not name order in RPC API
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/logs_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs
Labels: api, bug :bug:, in progress

#1316 Guard against nil in Parity.Trace.Action input
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace/action.ex
Labels: enhancement, in progress

#1318 Order derive_tranactions_forks SELECT to match transaction inserts
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
Labels: bug :bug:, in progress, ready for review, team: architecture

#1323 Update `address_current_token_balances` and `address_token_balances` to remove those referencing replaced block numbers during reorgs
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
Labels: bug :bug:, enhancement, in progress, ready for review, team: architecture

#1327 Script to fix address_current_token_balances
  apps/explorer/priv/repo/migrations/scripts/insert_address_current_token_balances_in_batches.sql
  apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
Labels: bug :bug:, in progress

#1321 Fixes for ganache JSON RPC mistakes
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipt.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  docker/README.md
Labels: bug :bug:, in progress

#1330 [WIP] return polling to realtime fetcher
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: in progress

#1329 feat: allow deferring js to specific pages
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/view_specific/address_contract/code_highlighting.js
  apps/block_scout_web/assets/webpack.config.js
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/script_helpers.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1332 Fix and optimize queries that need min or max block number
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/logs_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/block_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_internal_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_log_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/counters/blocks_indexed_counter.ex
  apps/block_scout_web/lib/block_scout_web/templates/block_transaction/404.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/block_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/logs_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/block_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_blocks_test.exs
  apps/block_scout_web/test/block_scout_web/views/transaction_view_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/supply/proof_of_authority.ex
  apps/explorer/lib/explorer/etherscan.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/etherscan_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer.ex
Labels: bug :bug:, enhancement, in progress, ready for review

#1340 Optimize update_address_current_token_balances_in_batches
  apps/explorer/priv/repo/migrations/scripts/update_address_current_token_balances_in_batches.sql
Labels: bug :bug:, in progress, team: architecture

#1338 fix: poll on import completion and only new blocks
  apps/explorer/lib/explorer/counters/average_block_time.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: in progress

#1341 do not index internal transactions with simple token transfers
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: in progress

#1348 feat: add alt tags to logos
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: in progress

#1356 feat: better footer, configurable network list
  apps/block_scout_web/assets/css/components/_footer.scss
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/lib/block_scout_web.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_footer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: in progress

#1347 fetch codes
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_code.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/fetched_codes.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
Labels: in progress

#1357 Store and maintain Explorer.Chain.count_token_holders_from_token_hash in tokens.holder_count
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/tokens.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/priv/repo/migrations/20190114204640_add_tokens_holder_count.exs
  apps/explorer/priv/repo/migrations/scripts/update_new_tokens_holder_count_in_batches.sql
  apps/explorer/test/explorer/chain/import/runner/address/current_token_balances_test.exs
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/support/chain/import/runner_case.ex
Labels: bug :bug:, in progress

#1361 fix: add height for footer logo
  apps/block_scout_web/assets/css/components/_footer.scss
Labels: in progress

#1360 Set Token holder_count to 0 for new tokens
  apps/explorer/lib/explorer/chain/import/runner/tokens.ex
  apps/explorer/test/explorer/chain/import/runner/tokens_test.exs
Labels: bug :bug:, in progress, team: architecture

#1350 Improved docker makefile for checking existance of postgres DB.
  docker/Makefile
Labels: in progress

#1364 Make insert_address_current_token_balances_in_batches only insert new
  apps/explorer/priv/repo/migrations/scripts/insert_address_current_token_balances_in_batches.sql
Labels: bug :bug:, enhancement, in progress

#1363 feat: render addresses according to eip-55
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/phoenix/html/safe.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/pages/address_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/block_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/chain_page.ex
  apps/block_scout_web/test/block_scout_web/features/pages/transaction_logs_page.ex
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/test/explorer/chain/address_test.exs
  apps/indexer/test/indexer_test.exs
Labels: in progress

#1366 feat: add a minimum polling interval to protect from overrun
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
Labels: in progress

#1353 add catchup code fetcher
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190116082843_add_created_contract_indexed_at_to_transactions.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/address_extraction.ex
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/code/fetcher.ex
  apps/indexer/lib/indexer/code/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/test/indexer/address_extraction_test.exs
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/code/fetcher_test.exs
  apps/indexer/test/support/indexer/code/supervisor/case.ex
Labels: in progress

#1365 Update to Phoenix 1.4 and cowboy 2.0 to enable HTTP/2
  .gitignore
  apps/block_scout_web/config/config.exs
  apps/block_scout_web/config/dev.exs
  apps/block_scout_web/config/test.exs
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/rpc_translator.ex
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract_verification/new.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/admin/session/login_form.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/admin/setup/admin_registration.html.eex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/web_socket/cowboy/websocket_handler.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/block/second_degree_relation.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20190118040301_create_tokens_primary_key.exs
  apps/explorer/priv/repo/migrations/20190118152240_block_second_degree_relations_composite_primary_key.exs
  mix.exs
  mix.lock
Labels: enhancement, in progress, ready for review

#1371 fix: don't reload every page
  apps/block_scout_web/assets/js/lib/smart_contract/read_only_functions.js
Labels: in progress

#1374 Add HTTPS Upgrade to Readme
  README.md
Labels: in progress

#1376 Prevent block rewards for different hash being recorded for same block number during reorg
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity/fetched_beneficiaries_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/block/rewards.ex
  apps/explorer/lib/explorer/chain/wei.ex
  apps/explorer/test/explorer/chain/block_test.exs
  apps/explorer/test/explorer/chain/wei_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/block/reward/fetcher.ex
  apps/indexer/lib/indexer/block/reward/supervisor.ex
  apps/indexer/lib/indexer/block/supervisor.ex
  apps/indexer/lib/indexer/block/uncataloged_rewards/importer.ex
  apps/indexer/lib/indexer/block/uncataloged_rewards/processor.ex
  apps/indexer/lib/indexer/coin_balance/fetcher.ex
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/reward/fetcher_test.exs
  apps/indexer/test/indexer/block/uncataloged_rewards/importer_test.exs
  apps/indexer/test/support/indexer/block/reward/supervisor/case.ex
Labels: bug :bug:, enhancement, in progress

#1370 add replaced transaction fetcher
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/repo/migrations/20190122125815_change_transaction_error_constraint.exs
  apps/explorer/priv/repo/migrations/20190124082812_add_index_on_transaction_nonce_and_from_address_hash.exs
  apps/explorer/priv/repo/migrations/scripts/update_replaced_transaction.sql
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/replaced_transaction/fetcher.ex
  apps/indexer/lib/indexer/replaced_transaction/supervisor.ex
  apps/indexer/lib/indexer/shrinkable/supervisor.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  apps/indexer/test/indexer/replaced_transaction/fetcher_test.exs
  apps/indexer/test/support/indexer/replaced_transaction/supervisor/case.ex
Labels: in progress

#1384 update transactions even if internal transactions are inserted
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/test/explorer/chain/import_test.exs
Labels: in progress

#1385 Update migration script for dropped/replaced transactions
  apps/explorer/priv/repo/migrations/scripts/update_replaced_transaction.sql
Labels: in progress

#1388 cache max and min block number
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/block_number_cache.ex
  apps/explorer/test/explorer/chain/block_number_cache_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/support/data_case.ex
Labels: in progress
