Repository blockscout/blockscout, pull requests merged in 2019-11, with the labels that each got.

#2829 Fix for stuck gas limit label and value
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2830 Fix wrong color of contract icon on xDai chain
  CHANGELOG.md
  apps/block_scout_web/assets/css/theme/_dai_variables.scss
  apps/block_scout_web/assets/static/images/dai_logo.svg
  apps/block_scout_web/assets/static/images/network-selector-icons/xdai-chain.svg
Labels: ready for review

#2822 Estimated address count on the main page
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/token_counters.js
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#2828 Fix for script that clears compilation/launching assets
  CHANGELOG.md
  apps/explorer/package-lock.json
  apps/explorer/package.json
  rel/commands/clear_build.sh
Labels: ready for review

#2841 LUKSO dashboard height fix
  CHANGELOG.md
  apps/block_scout_web/assets/css/theme/_lukso_variables.scss
Labels: ready for review

#2844 Extend external reward types up to 20
  CHANGELOG.md
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/fetched_beneficiaries.ex
Labels: ready for review

#2845 Set outline none for nav dropdown item in mobile view
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_navbar.scss
Labels: ready for review

#2846 Remove networks images preload
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: ready for review

#2851 Extend paths for css/js assets
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Labels: ready for review

#2855 Fix favicons load
  CHANGELOG.md
  apps/block_scout_web/assets/static/android-chrome-192x192.png
  apps/block_scout_web/assets/static/android-chrome-512x512.png
  apps/block_scout_web/assets/static/favicon-16x16.png
  apps/block_scout_web/assets/static/favicon-32x32.png
  apps/block_scout_web/assets/static/images/favicon-16x16.png
  apps/block_scout_web/assets/static/images/favicon-32x32.png
  apps/block_scout_web/assets/static/images/favicon.ico
  apps/block_scout_web/assets/static/mstile-150x150.png
  apps/block_scout_web/lib/block_scout_web/endpoint.ex
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
Labels: ready for review

#2862 Coin total supply from DB API endpoint
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/views/api/rpc/stats_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/stats_controller_test.exs
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/address_sum.ex
  apps/explorer/test/explorer/chain/cache/address_sum_test.exs
  apps/explorer/test/explorer/chain/cache/block_count_test.exs
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#2777 Remove duplicate blocks from changes_list before import
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Labels: ready for review

#2768 Remove nonconsensus blocks from cache after internal transactions importing
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/cache/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Labels: paused, ready for review

#2878 Decrease loaders showing delay on the main page
  CHANGELOG.md
  apps/block_scout_web/assets/js/lib/utils.js
Labels: UI, ready for review

#2835 Update int txs constraints repairing script
  CHANGELOG.md
  apps/explorer/priv/repo/migrations/scripts/20181108205650_large_additional_internal_transaction_constraints.sql
Labels: internal txs indexing, ready for review

#2896 Disable Parity websockets tests
  .circleci/config.yml
  CHANGELOG.md
Labels: ready for review

#2888 remove pending ops on invalidation
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Labels: indexing
