Repository blockscout/blockscout, pull requests merged in 2019-09, with the labels that each got.

#2636 Execute all address' transactions page queries in parallel
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address_transaction_csv_exporter.ex
  apps/explorer/lib/explorer/chain/transaction.ex
Labels: ready for review

#2659 Multipurpose front-end part update
  CHANGELOG.md
  apps/block_scout_web/assets/css/app.scss
  apps/block_scout_web/assets/css/components/_custom_tooltips_block_details.scss
  apps/block_scout_web/assets/css/components/_dashboard-banner.scss
  apps/block_scout_web/assets/css/components/_transaction.scss
  apps/block_scout_web/lib/block_scout_web/templates/address_coin_balance/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2573 Validate staking contract calls in JS and allow adding <1 POA to existing stake
  apps/block_scout_web/assets/css/components/_form.scss
  apps/block_scout_web/assets/js/lib/validation.js
  apps/block_scout_web/assets/js/pages/stakes/become_candidate.js
  apps/block_scout_web/assets/js/pages/stakes/make_stake.js
  apps/block_scout_web/assets/js/pages/stakes/move_stake.js
  apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_input_group.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: chain: POSDAO :chains:

#2649 Separate Claim Withdrawal button from Withdraw
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/claim_withdrawal.js
  apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_claim.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_control_withdraw.html.eex
Labels: chain: POSDAO :chains:

#2650 Show Stake modal instead of Become a Candidate for existing pools
  apps/block_scout_web/assets/js/pages/stakes/become_candidate.js
  apps/block_scout_web/assets/js/pages/stakes/make_stake.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
Labels: chain: POSDAO :chains:

#2651 Hide all controls when staking is forbidden by contract
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_top.html.eex
  apps/explorer/lib/explorer/staking/contract_reader.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
  apps/explorer/test/explorer/staking/contract_state_test.exs
Labels: chain: POSDAO :chains:

#2612 Add cache updating independently from Indexer
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/cache/block_number.ex
  apps/explorer/lib/explorer/chain/cache/blocks.ex
  apps/explorer/lib/explorer/chain/cache/transactions.ex
  apps/explorer/lib/explorer/chain/ordered_cache.ex
  apps/explorer/test/explorer/chain/cache/block_number_test.exs
Labels: ready for review

#2682 Use Task.start instead of Task.async in caches
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/cache/block_count.ex
  apps/explorer/lib/explorer/chain/cache/transaction_count.ex
Labels: ready for review

#2670 Improve UI and delegators logic for banned pools
  apps/block_scout_web/assets/css/components/_stakes_table.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_validator_info.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/lib/block_scout_web/channels/stakes_channel.ex
  apps/block_scout_web/lib/block_scout_web/controllers/stakes_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/chain/staking_pool.ex
  apps/explorer/lib/explorer/staking/contract_reader.ex
  apps/explorer/lib/explorer/staking/contract_state.ex
  apps/explorer/priv/contracts_abi/posdao/ValidatorSetAuRa.json
  apps/explorer/priv/repo/migrations/20190904170014_add_additional_ban_fields_to_staking_pools.exs
  apps/explorer/test/explorer/staking/contract_state_test.exs
Labels: chain: POSDAO :chains:

#2692 Fix staking UI issues (from #2292)
  apps/block_scout_web/assets/css/components/_check_tooltip.scss
  apps/block_scout_web/assets/css/components/_stakes_table.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_become_candidate.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_delegators_info.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_stake.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_validator_info.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/assets/css/stakes.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/list_morph.js
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/lib/block_scout_web/templates/layout/app.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_address.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_stats_item_account.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex
  apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
Labels: chain: POSDAO :chains:, wip

#2619 Enforce DB transaction's order to prevent deadlocks
  CHANGELOG.md
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/contract_method.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/import/runner/address/coin_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/current_token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/address/token_balances.ex
  apps/explorer/lib/explorer/chain/import/runner/addresses.ex
  apps/explorer/lib/explorer/chain/import/runner/block/rewards.ex
  apps/explorer/lib/explorer/chain/import/runner/block/second_degree_relations.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/logs.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools.ex
  apps/explorer/lib/explorer/chain/import/runner/staking_pools_delegators.ex
  apps/explorer/lib/explorer/chain/import/runner/token_transfers.ex
  apps/explorer/lib/explorer/chain/import/runner/tokens.ex
  apps/explorer/lib/explorer/chain/import/runner/transaction/forks.ex
  apps/explorer/lib/explorer/chain/import/runner/transactions.ex
  apps/explorer/lib/explorer/chain/import/stage.ex
  apps/explorer/lib/explorer/chain/import/stage/address_referencing.ex
  apps/explorer/lib/explorer/chain/import/stage/block_following.ex
  apps/explorer/lib/explorer/chain/import/stage/block_referencing.ex
  apps/explorer/lib/explorer/chain_spec/parity/importer.ex
  apps/explorer/lib/explorer/chain_spec/poa/importer.ex
  apps/explorer/lib/explorer/market/market.ex
  apps/explorer/lib/explorer/validator/metadata_importer.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/indexer/lib/indexer/temporary/blocks_transactions_mismatch.ex
  docs/sharelocks.md
Labels: ready for review

#2667 Add ETS-based cache for accounts page
  CHANGELOG.md
  apps/block_scout_web/test/support/conn_case.ex
  apps/block_scout_web/test/support/feature_case.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/accounts.ex
  apps/explorer/test/explorer/chain/cache/accounts_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/fetcher/block_reward.ex
  apps/indexer/lib/indexer/fetcher/coin_balance.ex
  apps/indexer/lib/indexer/fetcher/coin_balance_on_demand.ex
  apps/indexer/lib/indexer/fetcher/contract_code.ex
  apps/indexer/lib/indexer/fetcher/internal_transaction.ex
  apps/indexer/lib/indexer/fetcher/pending_transaction.ex
  apps/indexer/lib/indexer/fetcher/uncle_block.ex
Labels: ready for review

#2700 Fix staking Theme colors UI issues (from #2292)
  apps/block_scout_web/assets/css/_mixins.scss
  apps/block_scout_web/assets/css/components/_check.scss
  apps/block_scout_web/assets/css/components/_form.scss
  apps/block_scout_web/assets/css/components/_i_tooltip.scss
  apps/block_scout_web/assets/css/components/_modal_status.scss
  apps/block_scout_web/assets/css/components/_stakes_table.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_bottom_disclaimer.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_delegators_info.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes_progress.scss
  apps/block_scout_web/assets/css/theme/_dai_variables.scss
  apps/block_scout_web/assets/css/theme/_dark-theme.scss
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/utils.js
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_i_tooltip.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_bottom_disclaimer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/index.html.eex
Labels: chain: POSDAO :chains:, wip

#2709 Fix stuck label and value for uncle block height
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2717 Improve speed of nonconsensus data removal
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
Labels: ready for review

#2718 Include all addresses taking part in transactions in wallets' addresses counter
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/chain_controller.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/test/block_scout_web/channels/address_channel_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/rpc/eth_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_addresses_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/block_scout_web/test/block_scout_web/features/viewing_chain_test.exs
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/lib/explorer/counters/addresses_counter.ex
  apps/explorer/test/explorer/chain_test.exs
  apps/explorer/test/explorer/counters/addresses_counter_test.exs
Labels: ready for review
