Repository blockscout/blockscout, pull requests merged in 2019-10, with the labels that each got.

#2726 Remove internal_transaction block_number setting from blocks runner
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions_indexed_at_blocks.ex
  apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
Labels: ready for review

#2735 Add pending transactions cache
  CHANGELOG.md
  apps/block_scout_web/test/support/conn_case.ex
  apps/block_scout_web/test/support/feature_case.ex
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/pending_transactions.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/cache/pending_transactions_test.exs
  apps/explorer/test/support/data_case.ex
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/pending_transaction.ex
  apps/indexer/lib/indexer/fetcher/uncle_block.ex
Labels: ready for review

#2733 Add cache for first page of uncles
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/controllers/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/chain_controller_test.exs
  apps/explorer/config/config.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/cache/uncles.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/test/explorer/chain/cache/uncles_test.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/uncle_block.ex
  apps/indexer/lib/indexer/temporary/uncles_without_index.ex
Labels: ready for review

#2734 Allow connection only to authorized chain networks
  apps/block_scout_web/assets/js/lib/modals.js
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/assets/js/pages/stakes/become_candidate.js
  apps/block_scout_web/assets/js/pages/stakes/claim_withdrawal.js
  apps/block_scout_web/assets/js/pages/stakes/make_stake.js
  apps/block_scout_web/assets/js/pages/stakes/move_stake.js
  apps/block_scout_web/assets/js/pages/stakes/remove_pool.js
  apps/block_scout_web/assets/js/pages/stakes/utils.js
  apps/block_scout_web/assets/js/pages/stakes/withdraw_stake.js
Labels: chain: POSDAO :chains:

#2470 Allow Realtime Fetcher to wait for small skips
  CHANGELOG.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
  docs/env-variables.md
Labels: ready for review

#2757 Fix UI issues in Staking Dapp related to Mobile View
  apps/block_scout_web/assets/css/components/_modal.scss
  apps/block_scout_web/assets/css/components/_stakes_table.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_delegators_info.scss
  apps/block_scout_web/assets/css/components/stakes/_modal_stake.scss
  apps/block_scout_web/assets/css/components/stakes/_stakes.scss
  apps/block_scout_web/assets/css/theme/_dark-theme.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/lib/modals.js
  apps/block_scout_web/assets/js/pages/stakes.js
  apps/block_scout_web/lib/block_scout_web/templates/common_components/_modal_close_button.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_rows.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_become_candidate.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_claim.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_delegators_list.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_move.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_stake.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_validator_info.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_modal_withdraw.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_progress.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_stakes_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/stakes/_table.html.eex
  apps/block_scout_web/lib/block_scout_web/views/stakes_view.ex
Labels: chain: POSDAO :chains:, wip

#2783 Fix stuck value and ticker on the token page
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2744 Disable Geth tests in CI
  .circleci/config.yml
  CHANGELOG.md
Labels: ready for review

#2793 Hide "We are indexing this chain right now. Some of the counts may be inaccurate" banner if no txs in blockchain
  CHANGELOG.md
  apps/block_scout_web/test/block_scout_web/features/viewing_app_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/test/explorer/chain_test.exs
Labels: ready for review

#2449 Send events through postgres notify
  CHANGELOG.md
  apps/explorer/config/config.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/events/db_sender.ex
  apps/explorer/lib/explorer/chain/events/listener.ex
  apps/explorer/lib/explorer/chain/events/publisher.ex
  apps/explorer/lib/explorer/chain/events/simple_sender.ex
  apps/explorer/test/explorer/chain/events/publisher_test.exs
  apps/explorer/test/explorer/chain/events/subscriber_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
Labels: ready for review

#2803 Fix block validator custom tooltip
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_custom_tooltips_block_details.scss
  apps/block_scout_web/lib/block_scout_web/templates/address/_link.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/block/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/chain/_block.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/holder/_token_balances.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/inventory/_token.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_pending_tile.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction_token_transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/views/address_view_test.exs
Labels: ready for review

#2805 Update supported chains
  .dialyzer-ignore
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/layout_view.ex
Labels: ready for review

#2806 Fix blocks fetching on the main page
  CHANGELOG.md
  apps/block_scout_web/assets/js/pages/chain.js
  apps/block_scout_web/lib/block_scout_web/templates/chain/show.html.eex
Labels: ready for review

#2807 422 page
  CHANGELOG.md
  apps/block_scout_web/assets/static/images/errors-img/pic-404.svg
  apps/block_scout_web/lib/block_scout_web/controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/error422/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/error_422.ex
Labels: ready for review

#2808 Add tooltip for tx input
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#2797 Return old style menu
  CHANGELOG.md
  apps/block_scout_web/assets/css/components/_navbar.scss
  apps/block_scout_web/assets/css/theme/_dark-theme.scss
  apps/block_scout_web/assets/js/app.js
  apps/block_scout_web/assets/js/pages/dark-mode-switcher.js
  apps/block_scout_web/assets/js/pages/layout.js
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review
