Repository blockscout/blockscout, pull requests merged in 2020-02, with the labels that each got.

#2990 Fix import of Parity spec file
  CHANGELOG.md
  apps/explorer/lib/explorer/chain_spec/parity/importer.ex
  apps/explorer/test/explorer/chain_spec/parity/importer_test.exs
  apps/explorer/test/support/fixture/chain_spec/classic.json
Labels: ready for review

#2995 Support API_PATH env var in Docker file
  CHANGELOG.md
  docker/Makefile
Labels: ready for review

#2996 Fix awesomplete lib loading in Firefox
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/layout/_topnav.html.eex
Labels: UI, ready for review

#2883 Fix long contracts names
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address/_responsive_hash.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/address/overview.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: UI

#2993 Fix path definition for contract verification endpoint
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/router.ex
Labels: ready for review

#2999 Contract verification fix
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/router.ex
Labels: ready for review

#3006 npm audit fix
  .circleci/config.yml
  apps/block_scout_web/assets/package-lock.json
  apps/block_scout_web/assets/package.json
Labels: ready for review

#3007 Fix copy UTF8 tx input action
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/transaction/overview.html.eex
Labels: ready for review

#3009 Fix broken export to CSV
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/templates/address_transaction/index.html.eex
  apps/block_scout_web/lib/block_scout_web/views/address_transaction_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#3012 Speedup token transfers list query
  CHANGELOG.md
  apps/explorer/lib/explorer/etherscan.ex
Labels: ready for review

#3011 Revert realtime fetcher small skips feature
  CHANGELOG.md
  apps/indexer/config/config.exs
  apps/indexer/lib/indexer/block/catchup/fetcher.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/test/indexer/block/catchup/bound_interval_supervisor_test.exs
  apps/indexer/test/indexer/block/catchup/fetcher_test.exs
  apps/indexer/test/indexer/block/realtime/fetcher_test.exs
Labels: ready for review

#3016 Fix token instance QR code data
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
Labels: ready for review

#3017 Fix token instance QR code data when api_path is different from path
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api_docs_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
  apps/block_scout_web/priv/gettext/default.pot
  apps/block_scout_web/priv/gettext/en/LC_MESSAGES/default.po
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/schema/subscription/token_transfers_test.exs
  apps/block_scout_web/test/block_scout_web/views/api_docs_view_test.exs
Labels: ready for review

#3014 Fix checksum address feature for tokens pages
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/holder_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/instance/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/inventory_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/read_contract_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/tokens/transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/instance/overview/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_details.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_metatags.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/overview/_tabs.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/read_contract/index.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/tokens/transfer/_token_transfer.html.eex
  apps/block_scout_web/lib/block_scout_web/views/tokens/read_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/transfer_view.ex
Labels: ready for review

#3018 Fix filters functionality
  apps/block_scout_web/lib/block_scout_web/checksum_address.ex
Labels: ready for review

#3021 Refine dev config
  CHANGELOG.md
  apps/block_scout_web/README.md
  apps/block_scout_web/config/dev.exs
  apps/block_scout_web/config/dev.secret.exs.example
  apps/explorer/README.md
  apps/explorer/config/dev.exs
  apps/explorer/config/dev.secret.exs.example
Labels: ready for review

#3013 Raw trace of transaction on-demand
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/controllers/transaction_raw_trace_controller.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/ganache.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/parity/trace.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/variant.ex
  apps/ethereum_jsonrpc/lib/rsk.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/parity_test.exs
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/import.ex
  apps/explorer/lib/explorer/chain/import/runner.ex
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/test/explorer/chain/import/runner/blocks_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/fetcher/internal_transaction.ex
Labels: ready for review

#3000 Get rid of storing of first trace for all types of transactions for Parity variant
  CHANGELOG.md
  apps/explorer/lib/explorer/chain/import/runner/internal_transactions.ex
  apps/explorer/test/explorer/chain/import/runner/internal_transactions_test.exs
  apps/explorer/test/explorer/chain/import_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/config/test.exs
  apps/indexer/config/test/ganache.exs
  apps/indexer/config/test/geth.exs
  apps/indexer/config/test/parity.exs
  apps/indexer/config/test/rsk.exs
  apps/indexer/test/indexer/fetcher/internal_transaction_test.exs
Labels: ready for review

#3029 Fix transactions and blocks appearance on the main page
  CHANGELOG.md
  apps/block_scout_web/assets/__tests__/pages/chain.js
  apps/block_scout_web/assets/js/pages/chain.js
Labels: ready for review
