Repository blockscout/blockscout, pull requests merged in 2024-11, with the labels that each got.

#10699 feat: zilliqa consensus data related to block
  .github/workflows/config.yml
  .github/workflows/pre-release-zilliqa.yml
  .github/workflows/publish-docker-image-for-zilliqa.yml
  .github/workflows/release-zilliqa.yml
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/zilliqa_view.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/zilliqa.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/zilliqa/aggregate_quorum_certificate.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/zilliqa/helper.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/zilliqa/nested_quorum_certificates.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/zilliqa/quorum_certificate.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/block_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/zilliqa_test.exs
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/zilliqa/aggregate_quorum_certificates.ex
  apps/explorer/lib/explorer/chain/import/runner/zilliqa/nested_quorum_certificates.ex
  apps/explorer/lib/explorer/chain/import/runner/zilliqa/quorum_certificates.ex
  apps/explorer/lib/explorer/chain/import/stage/chain_type_specific.ex
  apps/explorer/lib/explorer/chain/zilliqa/aggregate_quorum_certificate.ex
  apps/explorer/lib/explorer/chain/zilliqa/hash/signature.ex
  apps/explorer/lib/explorer/chain/zilliqa/nested_quorum_certificate.ex
  apps/explorer/lib/explorer/chain/zilliqa/quorum_certificate.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/priv/zilliqa/migrations/20240927123039_create_quorum_certificate.exs
  apps/explorer/priv/zilliqa/migrations/20240927123101_create_aggregate_quorum_certificate.exs
  apps/explorer/priv/zilliqa/migrations/20240927123113_create_nested_quorum_certificate.exs
  apps/explorer/priv/zilliqa/migrations/20241015095021_add_view_to_block.exs
  apps/explorer/test/explorer/migrator/sanitize_duplicated_log_index_logs_test.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  config/config_helper.exs
  config/runtime/dev.exs
  config/runtime/prod.exs
  cspell.json
Labels: ci:all, ci:zilliqa

#11187 fix: Fix failed filecoin tests
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
Labels: ci:all

#11073 chore: OP modules improvements
  apps/block_scout_web/lib/block_scout_web/channels/optimism_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/optimism_deposit_channel.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket.ex
  apps/block_scout_web/lib/block_scout_web/channels/user_socket_v2.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/notifiers/optimism.ex
  apps/block_scout_web/lib/block_scout_web/realtime_event_handler.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/transaction.ex
  apps/explorer/lib/explorer/chain/events/publisher.ex
  apps/explorer/lib/explorer/chain/events/subscriber.ex
  apps/explorer/lib/explorer/chain/optimism/deposit.ex
  apps/explorer/lib/explorer/chain/optimism/dispute_game.ex
  apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
  apps/explorer/lib/explorer/chain/optimism/frame_sequence_blob.ex
  apps/explorer/lib/explorer/chain/optimism/output_root.ex
  apps/explorer/lib/explorer/chain/optimism/transaction_batch.ex
  apps/explorer/lib/explorer/chain/optimism/withdrawal.ex
  apps/explorer/lib/explorer/chain/optimism/withdrawal_event.ex
  apps/indexer/lib/indexer/fetcher/optimism.ex
  apps/indexer/lib/indexer/fetcher/optimism/deposit.ex
  apps/indexer/lib/indexer/fetcher/optimism/output_root.ex
  apps/indexer/lib/indexer/fetcher/optimism/transaction_batch.ex
  apps/indexer/lib/indexer/fetcher/optimism/withdrawal.ex
  apps/indexer/lib/indexer/fetcher/optimism/withdrawal_event.ex
  apps/indexer/lib/indexer/fetcher/rollup_l1_reorg_monitor.ex
  apps/indexer/lib/indexer/helper.ex
  config/runtime.exs
  cspell.json
  docker-compose/envs/common-blockscout.env
Labels: ci:optimism, ci:all

#11183 feat: Add Stylus verificaiton support
  .dialyzer-ignore
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/verification_controller.ex
  apps/block_scout_web/lib/block_scout_web/routers/smart_contracts_api_v2_router.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/filecoin_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/smart_contract/compiler_version.ex
  apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
  apps/explorer/lib/explorer/smart_contract/solidity/publisher_worker.ex
  apps/explorer/lib/explorer/smart_contract/stylus/publisher.ex
  apps/explorer/lib/explorer/smart_contract/stylus/publisher_worker.ex
  apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
  apps/explorer/lib/explorer/smart_contract/stylus_verifier_interface.ex
  apps/explorer/lib/explorer/smart_contract/vyper/publisher.ex
  apps/explorer/lib/explorer/smart_contract/vyper/publisher_worker.ex
  apps/explorer/priv/arbitrum/migrations/20241111195112_add_stylus_fields.exs
  apps/explorer/priv/repo/migrations/20241111200520_add_language_field.exs
  config/config_helper.exs
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all

#11264 fix: Multiple json rpc urls fixes
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/http.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/common_helper.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_checker.ex
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/http/mox_test.exs
  apps/ethereum_jsonrpc/test/ethereum_jsonrpc/utility/common_helper_test.exs
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/geth/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/case/nethermind/http_websocket.ex
  apps/ethereum_jsonrpc/test/support/ethereum_jsonrpc/http/case.ex
  apps/explorer/lib/explorer/chain/bridged_token.ex
  apps/explorer/lib/explorer/smart_contract/stylus/verifier.ex
  apps/indexer/lib/indexer/block/catchup/bound_interval_supervisor.ex
Labels: ci:all
