Repository blockscout/blockscout, pull requests merged in 2024-12, with the labels that each got.

#11195 feat: add CSV export of epoch transactions for address
  apps/block_scout_web/lib/block_scout_web/controllers/address_transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
  apps/explorer/lib/explorer/chain/celo/election_reward.ex
  apps/explorer/lib/explorer/chain/celo/reader.ex
  apps/explorer/lib/explorer/chain/csv_export/celo/address_election_rewards_csv_exporter.ex
  apps/indexer/test/indexer/block/fetcher_test.exs
Labels: ci:celo

#11206 fix: `entry/1` in token balance fetcher
  apps/indexer/lib/indexer/fetcher/token_balance.ex
Labels: ci:celo

#10675 feat: CDN
  .gitignore
  apps/block_scout_web/lib/block_scout_web/application.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v1/health_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
  apps/block_scout_web/lib/block_scout_web/health_endpoint.ex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_actions.html.eex
  apps/block_scout_web/lib/block_scout_web/templates/transaction/_decoded_input_body.html.eex
  apps/block_scout_web/lib/block_scout_web/views/abi_encoded_value_view.ex
  apps/block_scout_web/lib/block_scout_web/views/address_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/token_view.ex
  apps/block_scout_web/lib/block_scout_web/views/script_helper.ex
  apps/block_scout_web/lib/block_scout_web/views/tokens/instance/overview_view.ex
  apps/block_scout_web/lib/block_scout_web/views/transaction_view.ex
  apps/block_scout_web/mix.exs
  apps/block_scout_web/test/block_scout_web/views/abi_encoded_value_view_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/application.ex
  apps/ethereum_jsonrpc/mix.exs
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/chain/token/instance.ex
  apps/explorer/lib/explorer/chain/token/instance/media_urls.ex
  apps/explorer/lib/explorer/prometheus/instrumenter.ex
  apps/explorer/lib/explorer/token/metadata_retriever.ex
  apps/explorer/mix.exs
  apps/explorer/priv/repo/migrations/20240708152519_add_nft_media_urls.exs
  apps/indexer/lib/indexer/application.ex
  apps/indexer/lib/indexer/fetcher/on_demand/token_instance_metadata_refetch.ex
  apps/indexer/lib/indexer/fetcher/token_instance/helper.ex
  apps/indexer/lib/indexer/nft_media_handler/backfiller.ex
  apps/indexer/lib/indexer/nft_media_handler/queue.ex
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/mix.exs
  apps/nft_media_handler/.gitignore
  apps/nft_media_handler/README.md
  apps/nft_media_handler/lib/nft_media_handler.ex
  apps/nft_media_handler/lib/nft_media_handler/application.ex
  apps/nft_media_handler/lib/nft_media_handler/dispatcher.ex
  apps/nft_media_handler/lib/nft_media_handler/dispatcher_interface.ex
  apps/nft_media_handler/lib/nft_media_handler/image/resizer.ex
  apps/nft_media_handler/lib/nft_media_handler/media/fetcher.ex
  apps/nft_media_handler/lib/nft_media_handler/r2/uploader.ex
  apps/nft_media_handler/mix.exs
  apps/utils/lib/utils/token_instance_helper.ex
  apps/utils/mix.exs
  bin/version_bump.sh
  config/config_helper.exs
  config/runtime.exs
  config/runtime/dev.exs
  config/runtime/prod.exs
  cspell.json
  docker-compose/docker-compose.yml
  docker-compose/envs/common-blockscout.env
  docker-compose/envs/common-nft-media-handler.env
  docker-compose/no-services.yml
  docker-compose/services/backend.yml
  docker-compose/services/nft_media_handler.yml
  docker/Dockerfile
  mix.exs
  mix.lock
Labels: ci:all

#11319 chore: Remove shorthands-duplicates from API responses
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/stats_controller.ex
  apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
  apps/block_scout_web/lib/block_scout_web/views/account/api/v2/tags_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/block_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/internal_transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/mud_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/polygon_zkevm_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/search_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/token_transfer_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/zksync_view.ex
  apps/explorer/lib/explorer/account/notifier/email.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
  apps/explorer/test/explorer/account/notifier/email_test.exs
Labels: ci:all

#11069 feat: zilliqa scilla transactions and smart contracts
  apps/block_scout_web/lib/block_scout_web/paging_helper.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/smart_contract_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/transaction_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/zilliqa_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/zilliqa/helper.ex
  apps/explorer/lib/explorer/chain/zilliqa/reader.ex
  apps/explorer/priv/zilliqa/migrations/20241027171945_modify_smart_contracts.exs
  apps/indexer/lib/indexer/block/fetcher.ex
  apps/indexer/lib/indexer/fetcher/contract_code.ex
  apps/indexer/lib/indexer/fetcher/zilliqa/scilla_smart_contracts.ex
  apps/indexer/lib/indexer/supervisor.ex
  config/runtime.exs
  cspell.json
Labels: ci:all

#11481 Fix: issue in db request during Arbitrum message claiming
  apps/explorer/lib/explorer/chain/arbitrum/reader.ex
Labels: ci:arbitrum

#11397 chore: documentation for Explorer.Chain.Transaction.History.Historian
  apps/explorer/lib/explorer/chain/denormalization_helper.ex
  apps/explorer/lib/explorer/chain/transaction/history/historian.ex
  apps/explorer/lib/explorer/chain/transaction/history/transaction_stats.ex
  apps/explorer/lib/explorer/history/historian.ex
  apps/explorer/lib/explorer/history/process.ex
Labels: ci:all

#11541 feat: get all Arbitrum batches that corresponds to an AnyTrust data blob
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/arbitrum_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
  apps/explorer/lib/explorer/arbitrum/claim_rollup_message.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/README.md
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/general.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/messages.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/settlement.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/common.ex
Labels: ci:arbitrum

#11547 fix: Fix MarketHistory flickering test
  apps/explorer/test/explorer/market/history/cataloger_test.exs
Labels: ci:all

#11531 chore: split Arbitrum Reader and DB modules for improved maintainability
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/arbitrum_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum/constants/contracts.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum/constants/events.ex
  apps/explorer/lib/explorer/arbitrum/claim_rollup_message.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/README.md
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/general.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/messages.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/settlement.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/common.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/general.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/messages.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/parent_chain_transactions.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/settlement.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/da/anytrust.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/messages_to_l2_matcher.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/messaging.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/rollup_messages_catchup.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/tracking_batches_statuses.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/tracking_messages_on_l1.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/README.md
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/common.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/messages.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/parent_chain_transactions.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/settlement.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/tools.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/rpc.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/historical_messages_on_l2.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/l1_finalization.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_confirmations.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_l1_executions.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_messages_to_l2.ex
Labels: ci:arbitrum

#11485 fix: the same DA blobs for different Arbitrum batches
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/arbitrum_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/arbitrum_view.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum/constants/contracts.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum/constants/events.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/lib/explorer/arbitrum/claim_rollup_message.ex
  apps/explorer/lib/explorer/chain/arbitrum/batch_to_da_blob.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/README.md
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/general.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/messages.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/api/settlement.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/common.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/general.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/messages.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/parent_chain_transactions.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/settlement.ex
  apps/explorer/lib/explorer/chain/cache/background_migrations.ex
  apps/explorer/lib/explorer/chain/import/runner/arbitrum/batch_to_da_blobs.ex
  apps/explorer/lib/explorer/chain/import/stage/chain_type_specific.ex
  apps/explorer/lib/explorer/migrator/arbitrum_da_records_normalization.ex
  apps/explorer/lib/explorer/migrator/filling_migration.ex
  apps/explorer/lib/explorer/migrator/migration_status.ex
  apps/explorer/priv/arbitrum/migrations/20241217155103_add_data_blobs_to_batches_table.exs
  apps/indexer/lib/indexer/fetcher/arbitrum/da/anytrust.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/da/celestia.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/da/common.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/messages_to_l2_matcher.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/messaging.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/rollup_messages_catchup.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/tracking_batches_statuses.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/tracking_messages_on_l1.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/README.md
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/common.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/messages.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/parent_chain_transactions.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/settlement.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/tools.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/rpc.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/historical_messages_on_l2.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/l1_finalization.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_confirmations.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_l1_executions.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_messages_to_l2.ex
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all
