Repository blockscout/blockscout, pull requests merged in 2025-01, with the labels that each got.

#11355 feat: Support OP Holocene upgrade
  .devcontainer/README.md
  .devcontainer/bin/bs
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/optimism_controller.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/import/runner/optimism/eip1559_config_updates.ex
  apps/explorer/lib/explorer/chain/import/stage/chain_type_specific.ex
  apps/explorer/lib/explorer/chain/optimism/eip1559_config_update.ex
  apps/explorer/lib/explorer/smart_contract/solidity/publisher.ex
  apps/explorer/priv/optimism/migrations/20241203113159_holocene_support.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/fetcher/optimism.ex
  apps/indexer/lib/indexer/fetcher/optimism/deposit.ex
  apps/indexer/lib/indexer/fetcher/optimism/dispute_game.ex
  apps/indexer/lib/indexer/fetcher/optimism/eip1559_config_update.ex
  apps/indexer/lib/indexer/fetcher/optimism/output_root.ex
  apps/indexer/lib/indexer/fetcher/optimism/transaction_batch.ex
  apps/indexer/lib/indexer/fetcher/optimism/withdrawal.ex
  apps/indexer/lib/indexer/fetcher/optimism/withdrawal_event.ex
  apps/indexer/lib/indexer/fetcher/shibarium/l1.ex
  apps/indexer/lib/indexer/helper.ex
  apps/indexer/lib/indexer/supervisor.ex
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all

#11499 feat: Support filecoin addresses in search
  .dialyzer-ignore
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/explorer/lib/explorer/chain/filecoin/id.ex
  apps/explorer/lib/explorer/chain/search.ex
  apps/explorer/priv/filecoin/migrations/20241220110454_add_filecoin_addresses_indexes.exs
Labels: ci:all

#11659 fix: Ease SQL query for EIP1559ConfigUpdate fetcher
  apps/explorer/lib/explorer/chain/optimism/eip1559_config_update.ex
  apps/indexer/lib/indexer/fetcher/optimism/eip1559_config_update.ex
Labels: ci:all

#11163 feat: backfill for Arbitrum-specific information in blocks and transactions
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/block/by_number.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/blocks.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts/by_block_number.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/receipts/by_transaction_hash.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_checker.ex
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/utility/endpoint_availability_observer.ex
  apps/explorer/lib/explorer/chain/arbitrum/reader/indexer/general.ex
  apps/indexer/lib/indexer/block/fetcher/receipts.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/data_backfill.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/common.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/backfill.ex
  apps/indexer/lib/indexer/supervisor.ex
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all

#10480 chore: Deprecating of CHECKSUM_FUNCTION variable
  apps/block_scout_web/test/block_scout_web/controllers/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_internal_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_read_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_read_proxy_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_token_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_transaction_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_withdrawal_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_write_contract_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/address_write_proxy_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/smart_contract_controller_test.exs
  apps/explorer/lib/explorer/chain/address.ex
  apps/explorer/test/explorer/chain/address_test.exs
  apps/indexer/test/indexer/fetcher/rootstock_data_test.exs
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all

#11731 fix: new methods submitting Arbitrum batches supported
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/arbitrum/constants/contracts.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/rpc.ex
  apps/indexer/lib/indexer/fetcher/arbitrum/workers/new_batches.ex
Labels: ci:arbitrum

#11667 feat: Adds support for NeonVM linked Solana transactions
  .github/workflows/config.yml
  .github/workflows/pre-release-neon.yml
  .github/workflows/release-neon.yml
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain/neon/linked_solana_transactions.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/priv/neon/migrations/20241203161152_create_neon_solana_transactions.exs
  apps/indexer/lib/indexer/fetcher/on_demand/neon_solana_transactions.ex
  config/config_helper.exs
  config/runtime/dev.exs
  config/runtime/prod.exs
Labels: ci:neon

#11766 fix: Add typeless handler for call_tracer
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc/geth.ex
Labels: ci:all
