Repository blockscout/blockscout, pull requests merged in 2025-02, with the labels that each got.

#11714 fix: `EIP1559ConfigUpdate` and `Indexer.Block.Realtime.Fetcher` fetchers were unstable for L2 reorgs, `brotli` lib was replaced
  apps/explorer/lib/explorer/chain/transaction.ex
  apps/explorer/priv/optimism/migrations/20250121131928_holocene_clear.exs
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/fetcher/optimism/eip1559_config_update.ex
  apps/indexer/lib/indexer/fetcher/optimism/transaction_batch.ex
  apps/indexer/mix.exs
  mix.lock
Labels: ci:all

#11736 feat: Adds support for NeonVM linked Solana transactions (#11667)
  .github/workflows/config.yml
  .github/workflows/pre-release-neon.yml
  .github/workflows/release-neon.yml
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
  apps/ethereum_jsonrpc/lib/ethereum_jsonrpc.ex
  apps/explorer/config/dev.exs
  apps/explorer/config/prod.exs
  apps/explorer/config/test.exs
  apps/explorer/lib/explorer/chain/neon/linked_solana_transactions.ex
  apps/explorer/lib/explorer/repo.ex
  apps/explorer/priv/neon/migrations/20241203161152_create_neon_solana_transactions.exs
  apps/indexer/lib/indexer/fetcher/on_demand/neon_solana_transactions.ex
  config/config_helper.exs
  config/runtime/dev.exs
  config/runtime/prod.exs
  cspell.json
Labels: ci:neon

#11802 fix: Run Neon tests on neon chain type only
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
Labels: ci:all

#11805 fix: Fix tests
  apps/block_scout_web/lib/block_scout_web/views/api/v2/filecoin_view.ex
  apps/explorer/lib/explorer/migrator/sanitize_duplicated_log_index_logs.ex
Labels: ci:all

#11633 fix: strict mode for timestamp to block number conversion
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/block_controller.ex
  apps/explorer/lib/explorer/chain.ex
  apps/explorer/lib/explorer/chain/advanced_filter.ex
  apps/explorer/lib/explorer/chain/block/reader/general.ex
  apps/explorer/lib/explorer/chain/block_number_helper.ex
  apps/explorer/lib/explorer/chain/null_round_height.ex
  apps/explorer/lib/explorer/chain/transaction/history/historian.ex
  apps/explorer/test/explorer/chain/block/reader/general_test.exs
  apps/explorer/test/explorer/chain_test.exs
  apps/indexer/lib/indexer/fetcher/arbitrum/utils/db/common.ex
  apps/indexer/lib/indexer/fetcher/optimism/eip1559_config_update.ex
Labels: ci:all

#11807 fix: handle case when `epoch_distribution` is `nil`
  apps/block_scout_web/lib/block_scout_web/views/api/v2/celo_view.ex
Labels: ci:celo

#11810 fix: Fix scam addresses ban in quick search
  .dialyzer-ignore
  apps/explorer/lib/explorer/chain/search.ex
Labels: ci:all

#11812 fix: Hanlde invalid BLACKFORT_VALIDATOR_API_URL
  apps/explorer/lib/explorer/chain/blackfort/validator.ex
  apps/indexer/lib/indexer/block/realtime/fetcher.ex
  apps/indexer/lib/indexer/fetcher/blackfort/validator.ex
  apps/indexer/lib/indexer/fetcher/stability/validator.ex
Labels: ci:stability, ci:blackfort

#11895 fix: Add BRIDGED_TOKENS_ENABLED to custom Gnosis chain docker images
  .github/workflows/publish-docker-image-for-gnosis-chain.yml
  apps/block_scout_web/lib/block_scout_web/controllers/api/rpc/token_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_controller.ex
  apps/block_scout_web/lib/block_scout_web/etherscan.ex
  apps/block_scout_web/lib/block_scout_web/routers/tokens_api_v2_router.ex
  apps/explorer/lib/explorer/chain/token.ex
Labels: chain: Gnosis :chains:

#11915 fix: render token transfers from celo epoch logs
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/token_transfer_controller.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/token_transfer_view.ex
Labels: ci:celo

#11905 fix: Replace unique filecoin addresses indexes with not unique
  apps/explorer/priv/filecoin/migrations/20241220110454_add_filecoin_addresses_indexes.exs
  apps/explorer/priv/filecoin/migrations/20250220085529_replace_filecoin_addresses_indexes.exs
Labels: ci:filecoin
