Repository blockscout/blockscout, pull requests merged in 2025-10, with the labels that each got.

#13274 chore: OpenAPI spec for the REST API block controller
  apps/block_scout_web/lib/block_scout_web/chain.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/paging_helper.ex
  apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block/countdown.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block/response.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/error_responses.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/general.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
  apps/indexer/test/indexer/fetcher/beacon/deposit_test.exs
Labels: ci:all

#13308 fix: Fix SanitizeDuplicatedLogIndexLogs migration completion check
  apps/explorer/lib/explorer/migrator/sanitize_duplicated_log_index_logs.ex
Labels: ci:rsk

#13272 feat: Fields for OP Withdrawal Claim button
  apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
  apps/explorer/lib/explorer/chain/optimism/withdrawal.ex
  apps/explorer/lib/explorer/helper.ex
  apps/explorer/priv/optimism/migrations/20250919073011_op_withdrawal_claim_button.exs
  apps/indexer/lib/indexer/fetcher/optimism.ex
  apps/indexer/lib/indexer/fetcher/optimism/withdrawal.ex
  apps/indexer/lib/indexer/transform/optimism/withdrawals.ex
Labels: ci:core

#13324 fix: Fix web tests after hiding compile-time chain types routes
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/ethereum/deposit_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/optimism_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
Labels: ci:all

#13323 fix: enforce legacy query usage when sort by id
  apps/explorer/lib/explorer/chain/smart_contract.ex
Labels: ci:filecoin
