Repository blockscout/blockscout, pull requests merged in 2025-09, with the labels that each got.

#12985 feat: beacon deposits
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/block_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/ethereum/deposit_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/routers/api_router.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/tabs_counters.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/beacon/deposit.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/beacon/deposit/status.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/general.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/ethereum/deposit_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/ethereum_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/ethereum/deposit_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
  apps/explorer/lib/explorer/chain/address/counters.ex
  apps/explorer/lib/explorer/chain/address/metadata_preloader.ex
  apps/explorer/lib/explorer/chain/beacon/deposit.ex
  apps/explorer/lib/explorer/chain/block.ex
  apps/explorer/lib/explorer/chain/cache/counters/address_tabs_elements_count.ex
  apps/explorer/lib/explorer/chain/import/runner/blocks.ex
  apps/explorer/priv/beacon/migrations/20250813001523_create_deposits.exs
  apps/explorer/test/explorer/chain/beacon/deposit_test.exs
  apps/explorer/test/explorer/market/market_history_cache_test.exs
  apps/explorer/test/support/factory.ex
  apps/indexer/lib/indexer/fetcher/beacon/client.ex
  apps/indexer/lib/indexer/fetcher/beacon/deposit.ex
  apps/indexer/lib/indexer/fetcher/beacon/deposit/status.ex
  apps/indexer/lib/indexer/supervisor.ex
  apps/indexer/mix.exs
  apps/indexer/test/indexer/fetcher/beacon/deposit/status_test.exs
  apps/indexer/test/indexer/fetcher/beacon/deposit_test.exs
  apps/indexer/test/support/indexer/fetcher/beacon_deposit_status_supervisor_test.ex
  apps/indexer/test/support/indexer/fetcher/beacon_deposit_supervisor_case.ex
  config/runtime.exs
  cspell.json
  docker-compose/envs/common-blockscout.env
  mix.lock
Labels: ci:ethereum

#13029 feat: auto assert_schema in tests
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/address_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/ethereum/deposit_controller.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/counters.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/response.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/tabs_counters.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/token_balance.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/beacon/deposit.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/celo/election_reward.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/coin_balance.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/coin_balance_by_day.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/error_responses.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/general.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/internal_transaction.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/log.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/nft_collection.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/proxy/metadata.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/proxy/metadata_tag.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/signed_authorization.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token_instance.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token_instance_in_list.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token_transfer.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/transaction.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/transaction/fee.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/withdrawal.ex
  apps/block_scout_web/lib/block_scout_web/schemas/helper.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/ethereum/deposit_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
  apps/block_scout_web/test/support/api_schema_assertions.ex
  apps/block_scout_web/test/support/conn_case.ex
  apps/explorer/lib/explorer/application.ex
  apps/explorer/test/explorer/migrator/sanitize_duplicated_log_index_logs_test.exs
  apps/explorer/test/support/factory.ex
Labels: ci:all

#13221 chore: Refactoring reputation
  apps/block_scout_web/lib/block_scout_web/microservice_interfaces/transaction_interpretation.ex
  apps/block_scout_web/lib/block_scout_web/notifier.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/address/token_balance.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/nft_collection.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token_instance_in_list.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/token_transfer.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/address_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/advanced_filter_view.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/token_transfer_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/address_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/advanced_filter_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/token_transfer_controller_test.exs
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/transaction_controller_test.exs
  apps/explorer/lib/explorer/chain/address/current_token_balance.ex
  apps/explorer/lib/explorer/chain/advanced_filter.ex
  apps/explorer/lib/explorer/chain/search.ex
  apps/explorer/lib/explorer/chain/smart_contract.ex
  apps/explorer/lib/explorer/chain/token.ex
  apps/explorer/lib/explorer/chain/token/instance.ex
  apps/explorer/lib/explorer/chain/token_transfer.ex
  apps/explorer/lib/explorer/helper.ex
  apps/explorer/lib/explorer/migrator/sanitize_duplicated_log_index_logs.ex
Labels: ci:all

#13230 fix: some flapping explorer/indexer tests
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/search_controller_test.exs
  apps/explorer/test/explorer/history/process_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/code_compiler_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/publisher_test.exs
  apps/explorer/test/explorer/smart_contract/solidity/verifier_test.exs
  apps/indexer/test/indexer/fetcher/on_demand/coin_balance_test.exs
  apps/indexer/test/indexer/fetcher/token_instance/realtime_test.exs
Labels: ci:all

#13248 fix: Add reputation preload to celo base fee
  CHANGELOG.md
  apps/block_scout_web/lib/block_scout_web/views/api/v2/celo_view.ex
  apps/block_scout_web/test/block_scout_web/controllers/api/v2/block_controller_test.exs
Labels: ci:celo

#13249 feat: add ci:core label
  .github/workflows/config.yml
  .github/workflows/generate-swagger.yml
Labels: ci:core

#13179 feat: OP Alt-DA support for batch indexer
  .devcontainer/Dockerfile
  .devcontainer/docker-compose.yml
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/optimism_controller.ex
  apps/block_scout_web/lib/block_scout_web/controllers/api/v2/transaction_controller.ex
  apps/block_scout_web/lib/block_scout_web/schemas/api/v2/block.ex
  apps/block_scout_web/lib/block_scout_web/views/api/v2/optimism_view.ex
  apps/explorer/lib/explorer/chain/optimism/frame_sequence.ex
  apps/explorer/lib/explorer/chain/optimism/frame_sequence_blob.ex
  apps/explorer/lib/explorer/chain/optimism/transaction_batch.ex
  apps/explorer/priv/optimism/migrations/20250908073612_add_alt_da_blobs.exs
  apps/indexer/lib/indexer/fetcher/optimism/transaction_batch.ex
  apps/indexer/lib/indexer/helper.ex
  config/runtime.exs
  docker-compose/envs/common-blockscout.env
Labels: ci:all
